import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
const w=await import('../app/workflow.mjs');
const fx=path.join(import.meta.dirname,'fixtures/ep01-s01-b02');const j=f=>JSON.parse(fs.readFileSync(path.join(fx,f),'utf8'));
const project=j('project.json'),sequence=j('sequence.json'),shots=j('shots.json'),block=j('block.json'),accepted=fs.readFileSync(path.join(fx,'prompt-accepted.txt'),'utf8');
const registry={summary:'Photorealistic live-action science-fiction drama with dry understated comedy.',lighting:{red:'Practical helmet headlamps and amber emergency strips are the only sources; each face-plate is lit by the nearest lamp on the camera side and falls off fast into deep shadow; high-ISO grain.'},assets:{
 ROZ_RED:{kind:'character',character:'roz',variant:'red',file:'personajes/roz/ref/red-v02.png',proxy:'Cream',descriptor:'Older woman in the oldest sealed suit aboard, yellowed cream, shipping-line logo half worn off, helmet sticker crossed out; visor dark and reflective. 100% matches the reference.',status:'approved'},
 EARL_RED:{kind:'character',character:'earl',variant:'red',file:'personajes/earl/ref/red-v01.png',proxy:'Dark grey',descriptor:'Heavy male mechanic in a patched dark grey sealed suit, tools and keys at the belt; visor dark and reflective. 100% matches the reference.',status:'approved'},
 NNAMDI_RED:{kind:'character',character:'nnamdi',variant:'red',file:'personajes/nnamdi/ref/red-v02.png',proxy:'Orange',descriptor:'Thin Black man in a newer orange tug-company sealed suit marked NNAMDI; visor down, dark and reflective. 100% matches the reference.',status:'approved'},
 ROZ_VOICE:{kind:'voice',character:'roz',file:'assets/ep01-s01-real-v01/roz-ref.wav',descriptor:'Low, gravelly, fast.',status:'approved'},
 EARL_VOICE:{kind:'voice',character:'earl',file:'assets/ep01-s01-real-v01/earl-ref.wav',descriptor:'Bass, slow.',status:'approved'},
 NNAMDI_VOICE:{kind:'voice',character:'nnamdi',file:'assets/ep01-s01-real-v01/nnamdi-ref.wav',descriptor:'High, very fast.',status:'approved'},
 HOLD11_PLATE:{kind:'location',location:'cargo',aliases:['ep01-hold-11'],file:'ambientes/cargo/ref/interior-from-3d-v01.png',descriptor:'Depressurised cargo hold: aged ivory metal, seed containers strapped to floor rails, weathered sunset mural, amber emergency strips. Controls geometry, materials, light and atmosphere ONLY — not framing.',status:'approved'}}};
const map={prompt:'The camera is on the rail side. The MURAL fills the aft bulkhead at frame-left; the two RANKS of strapped containers run away from camera along the rails; the CRADLE sits on the centre rail in the midground; the DOOR is in the far wall at frame-right.',side:'rail side (local z < 0)',axis:'the centre rail',landmarks:[{label:'at the port rank of containers',positions:[[-1.6,1.1]]},{label:'behind the cradle',positions:[[-0.65,-1]]},{label:'at the strap of the cradle',positions:[[1.2,-1]]}]};
const scene={characters:{roz:{paragraph:'ROZ wants the containers locked before anyone spends the money; she checks strap tension with a gloved tug and gives the radio nothing but short orders.'},earl:{paragraph:'EARL wants to finish the latch; his hands stay on the cradle, he answers late and flat.'},nnamdi:{paragraph:'NNAMDI wants an audience; he hangs off the strap and narrates, helmet turning to whoever last spoke.'}},local_constraints:['Any container that opens = failed take.']};
function dlines(text){return [...text.matchAll(/At approximately ([\d.]+)s, ([A-Z]+)[^<]*<d>\[English\] (.*?)<\/d>/g)].map(m=>[Number(m[1]).toFixed(2),m[2],m[3]]);}

test('opticsLine deriva grados horizontales del FOV vertical y elige el ancla más cercana',()=>{assert.equal(Math.round(w.horizontalFov(50)),79);const line=w.opticsLine(50);assert.match(line,/^79° horizontal field of view \(about 24 mm/);assert.match(line,/One lens for the whole take/);assert.equal(w.opticsAnchor(30).mm,35);});
test('dialogueBudget cuenta cuatro palabras por segundo más un segundo de cola',()=>{assert.equal(w.dialogueBudget([]),0);assert.equal(w.dialogueBudget([{text:'one two three four',start:0}]),2);assert.equal(w.dialogueBudget([{text:'one two',start:3},{text:'a b c d e f g h',start:0}]),4.5);});
test('framePosition sitúa un punto a izquierda, centro o derecha del cuadro',()=>{const cam={position:[0,2,10],target:[0,1,0],fov:50};assert.equal(w.framePosition(cam,[0,0,0]).side,'centre');assert.equal(w.framePosition(cam,[-4,0,0]).side,'left');assert.equal(w.framePosition(cam,[4,0,0]).side,'right');assert.equal(w.framePosition(cam,[0,0,20]).visible,false);});
test('parseMapa lee el párrafo, el eje, el lado y los landmarks',()=>{const md='# Mapa\n\nLado de cámara: rail side\nEje de 180°: the centre rail\n\n```prompt\nThe MURAL at frame-left.\n```\n\n```json landmarks\n[{"label":"at the mural","positions":[[0,-12]]}]\n```\n';const m=w.parseMapa(md);assert.equal(m.prompt,'The MURAL at frame-left.');assert.equal(m.axis,'the centre rail');assert.equal(m.side,'rail side');assert.equal(m.landmarks[0].label,'at the mural');});
test('resolveRefs devuelve imágenes por tag en orden, la plate por alias y las voces de quien habla en cuadro',()=>{const r=w.resolveRefs({sequence,block,registry,shots});assert.deepEqual(r.images.map(i=>i.tag),['ROZ_RED','EARL_RED','NNAMDI_RED','HOLD11_PLATE']);assert.deepEqual(r.audios.map(a=>a.tag),['NNAMDI_VOICE','ROZ_VOICE','EARL_VOICE']);assert.deepEqual(r.errors,[]);});
test('resolveRefs señala tags ausentes o sin aprobar y el exceso de imágenes',()=>{const reg=structuredClone(registry);reg.assets.EARL_RED.status='draft';delete reg.assets.NNAMDI_VOICE;const r=w.resolveRefs({sequence,block,registry:reg,shots});assert(r.errors.some(e=>e.includes('EARL_RED')));assert(r.errors.some(e=>e.includes('NNAMDI_VOICE')));const many=w.resolveRefs({sequence,block:{...block,extraRefs:['ROZ_RED','ROZ_RED','ROZ_RED','ROZ_RED','ROZ_RED']},registry,shots});assert(many.errors.some(e=>e.startsWith('Demasiadas')));});
test('blockPrompt reproduce las secciones en orden fijo, los descriptores verbatim y sin huecos',()=>{const {prompt,warnings,requested}=w.blockPrompt({project,sequence,shots,block,registry,map,scene});const order=['subject_definitions:','summary:','retention_analysis:','detailed_description:','LOCATION MAP:','FIRST FRAME:','OPTICS:','CAMERA:','ACTION TIMING:','CHARACTER ACTING:','PHYSICS:','LIGHTING:','STYLE:','QUALITY:','POSITIVE CONSTRAINTS:','overall_soundscape:','non_diegetic_music:'];let last=-1;for(const k of order){const i=prompt.indexOf(k);assert(i>last,`${k} fuera de orden`);last=i;}for(const a of Object.values(registry.assets))if(a.kind!=='voice')assert(prompt.includes(a.descriptor),'descriptor no verbatim: '+a.descriptor.slice(0,30));assert(!prompt.includes('[['),'quedan huecos');assert.deepEqual(warnings,[]);assert.equal(requested,15);assert.match(prompt,/Image 1 \(@ROZ_RED\)/);assert.match(prompt,/Cream proxy in Video 1/);assert.match(prompt,/<Audio 1> is the voice identity reference for NNAMDI only/);assert.match(prompt,/STYLE: Dirty documentary realism/);});
test('blockPrompt genera las mismas líneas <d> y tiempos que el prompt aceptado de b02',()=>{const {prompt}=w.blockPrompt({project,sequence,shots,block,registry,map,scene});assert.deepEqual(dlines(prompt),dlines(accepted));assert.match(prompt,/Finish all words by 14\.0s/);});
test('blockPrompt deja huecos y avisa cuando faltan escena o mapa',()=>{const {prompt,warnings}=w.blockPrompt({project,sequence,shots,block,registry});assert.match(prompt,/\[\[ACTING\]\]/);assert.match(prompt,/\[\[LOCAL\]\]/);assert.match(prompt,/\[\[LOCATION MAP\]\]/);assert.deepEqual(warnings,[]);});
test('blockPrompt avisa si el diálogo no cabe, si hay palabras de emoción o negativos fuera de la lista blanca',()=>{const heavy=structuredClone(block);heavy.duration=6;const r=w.blockPrompt({project,sequence,shots,block:heavy,registry,map,scene});assert(r.warnings.some(x=>x.includes('R12')));const sad=structuredClone(scene);sad.characters.roz.paragraph='ROZ is sad and angry at the door.';sad.local_constraints=['No smiling. Do not add any other words.'];const r2=w.blockPrompt({project,sequence,shots,block,registry,map,scene:sad});assert(r2.warnings.some(x=>x.includes('sad')&&x.includes('angry')));assert(r2.warnings.some(x=>x.includes('Negativos')&&x.includes('No smiling')));assert.deepEqual(w.strayNegatives('Do not add any other words. No empty establishing frame.'),[]);});
test('las líneas fuera de campo y de megafonía no se generan: van como evento sin <d> y sin voz',()=>{const b=structuredClone(block);b.parts[0].lines.unshift({character:'pa',text:'Good morning, passengers.',channel:'pa',offscreen:true,start:0.1});b.parts[0].lines.push({character:'brady',text:'Hold eleven, report.',channel:'radio',offscreen:true,start:5});const {prompt,refs}=w.blockPrompt({project,sequence,shots,block:b,registry,map,scene});assert(!prompt.includes('Good morning'));assert(!prompt.includes('Hold eleven'));assert.match(prompt,/offscreen PA announcement from TOLEDO plays/);assert.match(prompt,/offscreen radio line from BRADY/);assert.deepEqual(refs.audios.map(a=>a.character),['nnamdi','roz','earl']);});
test('firstFrameLine ata cada cuerpo a un lado del cuadro y a un landmark del mapa',()=>{const line=w.firstFrameLine({sequence,shot:shots['ep01-s1-p2'],project,map});assert.match(line,/ROZ .*frame-(left|right|centre)/);assert.match(line,/behind the cradle/);assert.match(line,/Exactly 3 people visible/);});
test('cameraLine distingue cámara fija, movimiento continuo y estaciones de cobertura',()=>{const fixed={camera:{position:[0,2,5],target:[0,1,0],fov:50},cameraEnd:{position:[0,2,5],target:[0,1,0],fov:50}};assert.match(w.cameraLine(fixed),/Locked-off camera at 2\.0 m/);const move={camera:fixed.camera,cameraEnd:{position:[0,2,3],target:[0,1,0],fov:50}};assert.match(w.cameraLine(move),/continuous handheld move.*ending closer/);assert.match(w.cameraLine(shots['ep01-s1-p2']),/cuts between 4 locked-off camera stations/);});
