import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
const w=await import('../app/workflow.mjs');
const fx=path.join(import.meta.dirname,'fixtures/ep01-s01-b02');
// Datos de b02 (fixtures/ep01-s01-b02/datos.mjs): conTextos lleva el catálogo y los textos de prompt de dead-air (#42); bare es el proyecto sin catálogo.
import {project as bare,base,conTextos} from './fixtures/ep01-s01-b02/datos.mjs';import {casos} from './fixtures/ep01-s01-b02/casos-42.mjs';
const {project,sequence,shots,block,registry,map,scene}=conTextos,accepted=fs.readFileSync(path.join(fx,'prompt-accepted.txt'),'utf8');
function dlines(text){return [...text.matchAll(/At approximately ([\d.]+)s, ([A-Z]+)[^<]*<d>\[English\] (.*?)<\/d>/g)].map(m=>[Number(m[1]).toFixed(2),m[2],m[3]]);}

test('opticsLine deriva grados horizontales del FOV vertical y elige el ancla más cercana',()=>{assert.equal(Math.round(w.horizontalFov(50)),79);const line=w.opticsLine(50);assert.match(line,/^79° horizontal field of view \(about 24 mm/);assert.match(line,/One lens for the whole take/);assert.equal(w.opticsAnchor(30).mm,35);});
test('dialogueBudget cuenta cuatro palabras por segundo más un segundo de cola',()=>{assert.equal(w.dialogueBudget([]),0);assert.equal(w.dialogueBudget([{text:'one two three four',start:0}]),2);assert.equal(w.dialogueBudget([{text:'one two',start:3},{text:'a b c d e f g h',start:0}]),4.5);});
test('framePosition sitúa un punto a izquierda, centro o derecha del cuadro',()=>{const cam={position:[0,2,10],target:[0,1,0],fov:50};assert.equal(w.framePosition(cam,[0,0,0]).side,'centre');assert.equal(w.framePosition(cam,[-4,0,0]).side,'left');assert.equal(w.framePosition(cam,[4,0,0]).side,'right');assert.equal(w.framePosition(cam,[0,0,20]).visible,false);});
test('parseMapa lee el párrafo, el eje, el lado y los landmarks',()=>{const md='# Mapa\n\nLado de cámara: rail side\nEje de 180°: the centre rail\n\n```prompt\nThe MURAL at frame-left.\n```\n\n```json landmarks\n[{"label":"at the mural","positions":[[0,-12]]}]\n```\n';const m=w.parseMapa(md);assert.equal(m.prompt,'The MURAL at frame-left.');assert.equal(m.axis,'the centre rail');assert.equal(m.side,'rail side');assert.equal(m.landmarks[0].label,'at the mural');});
test('resolveRefs devuelve imágenes por tag en orden, la plate por alias y las voces de quien habla en cuadro',()=>{const r=w.resolveRefs({sequence,block,registry,shots});assert.deepEqual(r.images.map(i=>i.tag),['ROZ_RED','EARL_RED','NNAMDI_RED','HOLD11_PLATE']);assert.deepEqual(r.audios.map(a=>a.tag),['NNAMDI_VOICE','ROZ_VOICE','EARL_VOICE']);assert.deepEqual(r.errors,[]);});
test('resolveRefs señala tags ausentes o sin aprobar y el exceso de imágenes',()=>{const reg=structuredClone(registry);reg.assets.EARL_RED.status='draft';delete reg.assets.NNAMDI_VOICE;const r=w.resolveRefs({sequence,block,registry:reg,shots});assert(r.errors.some(e=>e.includes('EARL_RED')));assert(r.errors.some(e=>e.includes('NNAMDI_VOICE')));const many=w.resolveRefs({sequence,block:{...block,extraRefs:['ROZ_RED','ROZ_RED','ROZ_RED','ROZ_RED','ROZ_RED']},registry,shots});assert(many.errors.some(e=>e.startsWith('Demasiadas')));});
test('blockPrompt reproduce las secciones en orden fijo, los descriptores verbatim y sin huecos',()=>{const {prompt,warnings,requested}=w.blockPrompt({project,sequence,shots,block,registry,map,scene});const order=['subject_definitions:','summary:','retention_analysis:','detailed_description:','LOCATION MAP:','FIRST FRAME:','OPTICS:','CAMERA:','ACTION TIMING:','CHARACTER ACTING:','PHYSICS:','LIGHTING:','STYLE:','QUALITY:','POSITIVE CONSTRAINTS:','overall_soundscape:','non_diegetic_music:'];let last=-1;for(const k of order){const i=prompt.indexOf(k);assert(i>last,`${k} fuera de orden`);last=i;}for(const a of Object.values(registry.assets))if(a.kind!=='voice')assert(prompt.includes(a.descriptor),'descriptor no verbatim: '+a.descriptor.slice(0,30));assert(!prompt.includes('[['),'quedan huecos');assert.deepEqual(warnings,[]);assert.equal(requested,15);assert.match(prompt,/Image 1 \(@ROZ_RED\)/);assert.match(prompt,/Cream proxy in Video 1/);assert.match(prompt,/<Audio 1> is the voice identity reference for NNAMDI only/);assert.match(prompt,/STYLE: Dirty documentary realism/);});
test('blockPrompt genera las mismas líneas <d> y tiempos que el prompt aceptado de b02',()=>{const {prompt}=w.blockPrompt({project,sequence,shots,block,registry,map,scene});assert.deepEqual(dlines(prompt),dlines(accepted));assert.match(prompt,/Finish all words by 14\.0s/);});
test('PHYSICS del prompt: staging.swarm da el mismo texto que la clave heredada potatoes (#21)',()=>{const up=Object.fromEntries(Object.entries(shots).map(([k,t])=>[k,{...t,staging:w.upgradeStaging(t.staging)}]));assert.ok(Object.values(up).some(t=>t.staging?.swarm==='none'&&!('potatoes' in t.staging)));const a=w.blockPrompt({project,sequence,shots,block,registry,map,scene}).prompt,b=w.blockPrompt({project,sequence,shots:up,block,registry,map,scene}).prompt;assert.equal(b,a);assert.match(a,/PHYSICS: .* Seed potatoes: all containers sealed, none visible\./);});
test('blockPrompt deja huecos y avisa cuando faltan escena o mapa',()=>{const {prompt,warnings}=w.blockPrompt({project,sequence,shots,block,registry});assert.match(prompt,/\[\[ACTING\]\]/);assert.match(prompt,/\[\[LOCAL\]\]/);assert.match(prompt,/\[\[LOCATION MAP\]\]/);assert.deepEqual(warnings,[]);});
test('blockPrompt avisa si el diálogo no cabe, si hay palabras de emoción o negativos fuera de la lista blanca',()=>{const heavy=structuredClone(block);heavy.duration=6;const r=w.blockPrompt({project,sequence,shots,block:heavy,registry,map,scene});assert(r.warnings.some(x=>x.includes('R12')));const sad=structuredClone(scene);sad.characters.roz.paragraph='ROZ is sad and angry at the door.';sad.local_constraints=['No smiling. Do not add any other words.'];const r2=w.blockPrompt({project,sequence,shots,block,registry,map,scene:sad});assert(r2.warnings.some(x=>x.includes('sad')&&x.includes('angry')));assert(r2.warnings.some(x=>x.includes('Negativos')&&x.includes('No smiling')));assert.deepEqual(w.strayNegatives('Do not add any other words. No empty establishing frame.'),[]);});
test('las líneas fuera de campo y de megafonía no se generan: van como evento sin <d> y sin voz',()=>{const b=structuredClone(block);b.parts[0].lines.unshift({character:'pa',text:'Good morning, passengers.',channel:'pa',offscreen:true,start:0.1});b.parts[0].lines.push({character:'brady',text:'Hold eleven, report.',channel:'radio',offscreen:true,start:5});const {prompt,refs}=w.blockPrompt({project,sequence,shots,block:b,registry,map,scene});assert(!prompt.includes('Good morning'));assert(!prompt.includes('Hold eleven'));assert.match(prompt,/offscreen PA announcement from TOLEDO plays/);assert.match(prompt,/offscreen radio line from BRADY/);assert.deepEqual(refs.audios.map(a=>a.character),['nnamdi','roz','earl']);});
test('firstFrameLine ata cada cuerpo a un lado del cuadro y a un landmark del mapa',()=>{const line=w.firstFrameLine({sequence,shot:shots['ep01-s1-p2'],project,map});assert.match(line,/ROZ .*frame-(left|right|centre)/);assert.match(line,/behind the cradle/);assert.match(line,/Exactly 3 people visible/);});
test('cameraLine distingue cámara fija, movimiento continuo y estaciones de cobertura',()=>{const fixed={camera:{position:[0,2,5],target:[0,1,0],fov:50},cameraEnd:{position:[0,2,5],target:[0,1,0],fov:50}};assert.match(w.cameraLine(fixed),/Locked-off camera at 2\.0 m/);const move={camera:fixed.camera,cameraEnd:{position:[0,2,3],target:[0,1,0],fov:50}};assert.match(w.cameraLine(move),/continuous handheld move.*ending closer/);assert.match(w.cameraLine(shots['ep01-s1-p2']),/cuts between 4 locked-off camera stations/);});

test('framePrompt: el fotograma del storyboard es el primero, la línea va con su tiempo, huecos de cámara y acción, sin cascos ni gravedad',async()=>{const {framePrompt}=await import('../app/workflow.mjs');
const project={characters:[{id:'odila',name:'Odila'},{id:'ancel',name:'Ancel'}]};
const shots={s1:{id:'s1',title:'A23 · «Ahí no»',duration:4,storyboardRender:'storyboards/sb/render/A23.png',lines:[{id:'l1',character:'odila',text:'Not there.',start:.5,offscreen:false}]}};
const block={id:'b01',mode:'fotograma',duration:5,length:4,parts:[{shot:'s1',from:0,to:4,at:0,lines:[{id:'l1',character:'odila',text:'Not there.',start:.5,offscreen:false}]}]};
const registry={summary:'Medieval drama.',lighting:{default:'Flat grey winter light.'},assets:{ODILA_BASE:{kind:'character',character:'odila',descriptor:'ODILA: a laundress.',status:'approved'},ODILA_VOICE:{kind:'voice',character:'odila',descriptor:'Matte dry voice.',status:'approved'}}};
const r=framePrompt({project,sequence:{title:'El Ahorcado',ambiencePrompt:'Wind.'},shots,block,registry,map:{prompt:'The crossroads.'},scene:{characters:{odila:{paragraph:'ODILA states it once.'}},local_constraints:['No birds.']},cast:['odila']});
assert.equal(r.image,'storyboards/sb/render/A23.png');assert.equal(r.requested,5);
assert.match(r.prompt,/The supplied image IS frame zero/);assert.match(r.prompt,/At approximately 0\.50s, ODILA says exactly: <d>\[English\] Not there\.<\/d>/);
assert.match(r.prompt,/\[\[CAMERA\]\]/);assert.match(r.prompt,/\[\[ACTION\]\]/);assert.match(r.prompt,/PEOPLE: ODILA: a laundress\./);assert.match(r.prompt,/ODILA's voice: Matte dry voice\./);
assert.match(r.prompt,/\[\[LOCAL\]\]/);assert.match(r.prompt,/Shot A23\. The supplied/);assert.doesNotMatch(r.prompt,/@ODILA|«/);assert.doesNotMatch(r.prompt,/No birds\.|horses? shift/);assert.doesNotMatch(r.prompt,/helmet|gravity|Video 1/i);assert.deepEqual(r.warnings,[]);assert.deepEqual(r.names,['ODILA']);
const noFrame=framePrompt({project,sequence:{title:'x'},shots:{s1:{...shots.s1,storyboardRender:undefined,cameraEn:'Static.',actionEn:'She speaks.'}},block,registry,map:null,scene:null,cast:['odila','ancel']});
assert.ok(noFrame.warnings.some(w=>/fotograma/.test(w)));assert.ok(noFrame.warnings.some(w=>/ancel/.test(w)));assert.doesNotMatch(noFrame.prompt,/\[\[CAMERA\]\]|\[\[ACTION\]\]/);});

// #41: el catálogo de canales y variantes sale del proyecto. Las referencias se capturaron con el código anterior a #41.
const ref=f=>fs.readFileSync(path.join(fx,f),'utf8');
const withExt=()=>{const b=structuredClone(block);b.parts[0].lines.push({id:'ext-1',character:'brady',text:'Hold eleven, confirm the seal.',channel:'ext',offscreen:false,start:5});return b;};
test('blockPrompt de b02 es byte a byte el de antes de #41 con el catálogo y los textos de dead-air (#41, #42)',()=>{
 assert.equal(w.blockPrompt({project,sequence,shots,block,registry,map,scene}).prompt,ref('prompt-ref-41.txt'));
 assert.equal(w.blockPrompt({project,sequence,shots,block:withExt(),registry,map,scene}).prompt,ref('prompt-ref-41-ext.txt'));});
test('una línea ext es fuera de campo con el catálogo de dead-air y hablada en un proyecto sin catálogo (#41)',()=>{const b=withExt();
 const neutral=w.blockPrompt({project:bare,sequence,shots,block:b,registry,map,scene});assert.match(neutral.prompt,/BRADY[^<]*says exactly: <d>\[English\] Hold eleven, confirm the seal\.<\/d>/);assert.ok(neutral.refs.errors.includes('Falta en el registro: BRADY_VOICE'));
 const r=w.blockPrompt({project,sequence,shots,block:b,registry,map,scene});assert.doesNotMatch(r.prompt,/Hold eleven/);assert.deepEqual(r.refs.errors,[]);});
test('la zona del prompt: la variante de la secuencia, si no la variante por defecto del catálogo, si no ninguna (#41, #42)',()=>{const run=(p,s)=>w.blockPrompt({project:p,sequence:s,shots,block,registry,map,scene}).prompt,summary=(p,s)=>/\(ep01-hold-11, (\w+) zone/.exec(run(p,s))?.[1];const s0={...sequence,variant:''},C=project.stage;
 assert.equal(summary(project,sequence),sequence.variant);assert.equal(summary(project,s0),'green');assert.equal(summary({...project,stage:{...C,defaultVariant:'yellow'}},s0),'yellow');
 for(const p of [{...project,stage:{...C,defaultVariant:'nope'}},bare]){assert.equal(summary(p,s0),undefined);assert.match(run(p,s0),/\(ep01-hold-11, gravity normal\)/);}});

// #42: los textos de prompt salen del registro y del catálogo. ref-42 se capturó con el código anterior a #42 (capturar-42.mjs sobre base).
test('blockPrompt reproduce byte a byte los casos de referencia de la #42',()=>{for(const {name,args} of casos(conTextos))assert.equal(w.blockPrompt(args).prompt,ref(`ref-42/${name}.txt`),name);});
test('una instantánea sin textos de canal toma los del proyecto vivo y el registro se lee en vivo (#42)',()=>{const stale=w.stageFallback(base.project,conTextos.project);assert.ok(stale.stage.channels.every(c=>c.prompt));assert.equal(base.project.stage.channels.some(c=>c.prompt),false);
 for(const n of ['red','offscreen']){const {args}=casos({...base,project:stale,registry:conTextos.registry}).find(c=>c.name===n);assert.equal(w.blockPrompt(args).prompt,ref(`ref-42/${n}.txt`),n);}});
