import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {validateEvents,appearance,voiceDirection} from '../app/workflow.mjs';import {digest,newShot,validate} from '../app/store.mjs';
function project(){const t=newShot();t.lines=[{id:'l',character:'pa',text:'Good morning.',start:1,offscreen:true,channel:'pa'}];return {id:'test',name:'Test',type:'serie',language:'en',ideas:[],characters:[{id:'a',name:'Roz',description:'Captain',voice:'a',variants:{red:{description:'Cream sealed suit',image:'red.png'}}},{id:'pa',name:'PA',kind:'voice',voice:'pa-1'}],locations:[],episodes:[{id:'ep',sequences:[{id:'seq',variant:'red',cast:[{character:'a',x:0,z:0,yaw:0}],shots:[t]}]}]};}
test('PA can speak without becoming a physical actor; cannot be placed in cast',()=>{const p=project();assert.doesNotThrow(()=>validate(p));p.episodes[0].sequences[0].cast.push({character:'pa',x:1,z:0,yaw:0});assert.throws(()=>validate(p),/físico/);});
test('offscreen voice, zone and overlap policy invalidate prior approval hash',()=>{for(const mutate of [p=>p.characters[1].voice='pa-2',p=>p.episodes[0].sequences[0].variant='green',p=>p.episodes[0].sequences[0].shots[0].allowOverlap=true]){const p=project(),id=p.episodes[0].sequences[0].shots[0].id,old=digest(p,id);mutate(p);assert.notEqual(digest(p,id),old);}});
test('red variant never silently falls back to unhelmeted identity',()=>{const c={description:'Person',image:'bare.png',variants:{red:{description:'Helmet',image:'red.png'}}};assert.equal(appearance(c,{variant:'red'}).image,'red.png');assert.equal(appearance(c,{variant:'yellow'}).image,null);assert.equal(appearance(c,{}).image,'bare.png');});
test('overlap is opt-in and self-overlap is always rejected, including nested intervals',()=>{const e=[{character:'a',start:0,end:5},{character:'b',start:1,end:2},{character:'a',start:3,end:4}];assert.throws(()=>validateEvents(e,{duration:6}),/solapadas/);assert.throws(()=>validateEvents(e,{duration:6,allowOverlap:true}),/sí mismo/);assert.doesNotThrow(()=>validateEvents(e.slice(0,2),{duration:6,allowOverlap:true}));assert.throws(()=>validateEvents([{character:'a',start:4,end:7}],{duration:6}),/fuera/);});
test('PA and radio prompts explicitly prevent inappropriate mouth motion',()=>{const p=project();assert.match(voiceDirection(p,{character:'pa',channel:'pa'}),/OFFSCREEN/);assert.match(voiceDirection(p,{character:'a',channel:'radio'}),/helmet stays sealed/);});

// ---- Storyboards
import {storyboardPrompt,storyboardToEpisode,storyboardShot} from '../app/workflow.mjs';
function withStoryboard(){const p=project();p.locations=[{id:'loc',name:'Galley',description:'Kitchen'}];p.storyboards=[{id:'sb',title:'Apertura',sequences:[{id:'sb-s',title:'Cocina',location:'loc',shots:[{id:'sb-t1',code:'A1',title:'Mesa',duration:40,zone:'green',camera:'35 mm',action:'Seven at the table.',sketch:'a.png',cast:['a'],references:[{path:'r.png',role:'set'}],dialogue:[{who:'Roz',channel:'',text:'Hi.'},{who:'PA',channel:'pa',text:'Good morning.'},{who:'Calloway',channel:'ext',text:'Unknown voice.'}]},{id:'sb-t2',code:'A2',title:'Negro',duration:0,zone:'space',action:'Black.',dialogue:[]}]}]}];return p;}
test('storyboards validate as project entities with unique ids and known cast',()=>{const p=withStoryboard();assert.doesNotThrow(()=>validate(p));const dup=withStoryboard();dup.storyboards[0].sequences[0].shots[0].id='ep';assert.throws(()=>validate(dup),/duplicado/);const bad=withStoryboard();bad.storyboards[0].sequences[0].shots[0].cast=['nobody'];assert.throws(()=>validate(bad),/desconocido/);assert.equal(storyboardShot(p,'sb-t2').shot.code,'A2');assert.throws(()=>storyboardShot(p,'nope'),/no encontrado/);});
test('storyboard prompt composes sketch rule, style and cast, or uses the explicit prompt verbatim',()=>{const p=withStoryboard();p.style='Dirty realism.';const {storyboard:b,sequence:s,shot:t}=storyboardShot(p,'sb-t1');const text=storyboardPrompt(p,b,s,t);assert.match(text,/^Image 1 is a rough storyboard/);assert.match(text,/Dirty realism/);assert.match(text,/Roz: Captain/);assert.match(text,/35 mm/);t.prompt='  Exact prompt.  ';assert.equal(storyboardPrompt(p,b,s,t),'Exact prompt.');const t2=storyboardShot(p,'sb-t2').shot;assert.match(storyboardPrompt(p,b,s,t2),/No people in this frame/);assert.doesNotMatch(storyboardPrompt(p,b,s,t2),/Image 1/);});
test('a storyboard converts into a valid episode: durations clamped, speakers resolved, unknown voices dropped, lines offscreen',()=>{const p=withStoryboard();let n=0;const e=storyboardToEpisode(p,p.storyboards[0],()=>'gen-'+(n++));p.episodes.push(e);assert.doesNotThrow(()=>validate(p));assert.equal(e.storyboard,'sb');assert.equal(e.sequences[0].location,'loc');assert.equal(e.sequences[0].variant,'green');const [t1,t2]=e.sequences[0].shots;assert.equal(t1.duration,15);assert.equal(t2.duration,5);assert.equal(t1.title,'A1 · Mesa');assert.deepEqual(t1.lines.map(l=>[l.character,l.channel,l.offscreen]),[['a',undefined,true],['pa','pa',true]]);assert.ok(t1.lines.every(l=>l.start<t1.duration));assert.equal(t1.storyboardShot,'sb-t1');});

test('hoja.md incluye Interpretación y Voice prompt cuando el personaje los tiene, y visualBrief los ignora',async()=>{const store=await import('../app/store.mjs');const w=await import('../app/workflow.mjs');const p=store.create('Perfiles','serie');p.characters.push({id:'ana',name:'Ana',description:'Piloto.\n**Acting:** no debería salir\n**Voice prompt:** tampoco',acting:'ANA wants…',voicePrompt:'A 40-year-old…'});store.save(p);const md=fs.readFileSync(path.join(store.dir(p.id),'personajes/ana/hoja.md'),'utf8');assert.match(md,/## Interpretación\nANA wants…/);assert.match(md,/## Voice prompt\nA 40-year-old…/);assert.equal(w.visualBrief(p.characters[0]),'Piloto.');});
