import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';
const w=await import('../app/workflow.mjs');const {DATA}=await import('../lib/paths.mjs');
// Esqueleto de framePrompt como en bloques.test.mjs: un plano con fotograma y una línea de ODILA.
const project={characters:[{id:'odila',name:'Odila'},{id:'ancel',name:'Ancel'}]};
const shots={s1:{id:'s1',title:'A23 · «Ahí no»',duration:4,storyboardRender:'storyboards/sb/render/A23.png',lines:[{id:'l1',character:'odila',text:'Not there.',start:.5,offscreen:false}]}};
const block={id:'b01',mode:'fotograma',duration:5,length:4,parts:[{shot:'s1',from:0,to:4,at:0,lines:[{id:'l1',character:'odila',text:'Not there.',start:.5,offscreen:false}]}]};
const registry={summary:'Medieval drama.',lighting:{default:'Flat grey winter light.'},assets:{ODILA_BASE:{kind:'character',character:'odila',descriptor:'ODILA: a laundress.',status:'approved'},ODILA_VOICE:{kind:'voice',character:'odila',descriptor:'Matte dry voice.',status:'approved'}}};
const frame=(cast=['odila'],over={},reg=registry)=>w.framePrompt({project,sequence:{title:'x',ambiencePrompt:'Wind.'},shots:{s1:{...shots.s1,...over}},block,registry:reg,map:{prompt:'The crossroads.'},scene:null,cast});
const locks=['Anyone entering = failed take (C01).',{text:'Any look into the lens = failed take (C04).',when:'cast'},'Any bird = failed take (C07).'];
const d={camera:'Locked-off wide shot.',action:'She points at the ditch.',acting:'ODILA points once and lowers her hand.',local:'The mule stays still.'};

test('applyDireccion rellena CAMERA, ACTION y LOCAL con el reparto, local y las coletillas en orden',()=>{const r=frame();const a=w.applyDireccion(r.prompt,d,{names:r.names,locks,image:r.image});
 assert.match(a.prompt,/^CAMERA: Locked-off wide shot\.$/m);assert.match(a.prompt,/^\[0\.00s–5\.00s\] She points at the ditch\.$/m);
 assert.ok(a.prompt.includes('POSITIVE CONSTRAINTS: Eyes lead the head and settle on people or landmarks; nobody looks at the lens. Only the people of the first frame appear; nobody enters the frame unless the action says so. Every person 100% matches the first frame in every frame. The people in the scene are only ODILA; nobody else enters the frame. The mule stays still. Anyone entering = failed take (C01). Any look into the lens = failed take (C04). Any bird = failed take (C07).\n'));
 assert.doesNotMatch(a.prompt,/\[\[/);assert.deepEqual(a.refsPatch,{});assert.deepEqual(a.warnings,[]);});
test('applyDireccion: people sustituye el recuento del resumen y la frase de reparto',()=>{const r=frame();const a=w.applyDireccion(r.prompt,{...d,people:'ODILA and two distant riders'},{names:r.names,locks});
 assert.match(a.prompt,/People in the scene: ODILA and two distant riders\./);assert.doesNotMatch(a.prompt,/Exactly 1 person/);assert.match(a.prompt,/The people in the scene are only ODILA and two distant riders; nobody else/);});
test('applyDireccion: when cast solo con reparto; admite cadenas y objetos',()=>{const r=frame([]);const a=w.applyDireccion(r.prompt,{camera:'Static.'},{names:r.names,locks:[...locks,{text:'Always (C09).',when:'always'}]});
 assert.ok(a.prompt.includes('in every frame. Anyone entering = failed take (C01). Any bird = failed take (C07). Always (C09).\n'));assert.doesNotMatch(a.prompt,/C04|The people in the scene/);});
test('applyDireccion: CHARACTER ACTING hasta la sección siguiente, con PHYSICS o sin ella (#43), sin tocar el resto',()=>{
 for(const [reg,next] of [[registry,'LIGHTING: '],[{...registry,texts:{frame:{physics:'Real weight.'}}},'PHYSICS: ']]){const r=frame(['odila'],{},reg);const a=w.applyDireccion(r.prompt,{acting:'ODILA looks at the ditch.'},{names:r.names});assert.deepEqual(a.warnings,[]);
  const before=r.prompt.split('\n'),after=a.prompt.split('\n');assert.equal(after.length,before.length);assert.ok(before[before.findIndex(l=>l.startsWith('CHARACTER ACTING: '))+1].startsWith(next),next);
  after.forEach((l,i)=>{if(before[i].startsWith('CHARACTER ACTING: '))assert.equal(l,'CHARACTER ACTING: ODILA looks at the ditch.');else if(before[i].startsWith('POSITIVE CONSTRAINTS: '))assert.ok(l.startsWith(before[i].replace('[[LOCAL]]','')));else assert.equal(l,before[i]);});}
 const none=w.applyDireccion('summary:\nx\nCHARACTER ACTING: [[ACTING]]\nSTYLE: y',{acting:'Z.'});assert.match(none.warnings[0],/falta CHARACTER ACTING antes de PHYSICS o LIGHTING/);});
test('applyDireccion: fin pone endImage; sin fin nada; fin sin fotograma avisa',()=>{const r=frame();assert.deepEqual(w.applyDireccion(r.prompt,{...d,fin:true},{names:r.names,image:r.image}).refsPatch,{endImage:'storyboards/sb/render/A23.png'});
 assert.deepEqual(w.applyDireccion(r.prompt,{...d,fin:false},{names:r.names,image:r.image}).refsPatch,{});
 assert.ok(w.applyDireccion(r.prompt,{...d,fin:true},{names:r.names,image:null}).warnings.some(x=>/fin sin fotograma/.test(x)));});
test('applyDireccion no interpreta $ en los textos',()=>{const r=frame();const a=w.applyDireccion(r.prompt,{camera:"Pan $& and $' and $1.",acting:'Pays $$ twice.'},{names:r.names});
 assert.match(a.prompt,/^CAMERA: Pan \$& and \$' and \$1\.$/m);assert.match(a.prompt,/^CHARACTER ACTING: Pays \$\$ twice\.$/m);});
test('applyDireccion avisa si el esqueleto ya trae el campo y conserva el hueco de un campo ausente',()=>{const r=frame(['odila'],{cameraEn:'Static from the ditch.'});const a=w.applyDireccion(r.prompt,{camera:'Other.',local:'x.'},{names:r.names});
 assert.match(a.prompt,/^CAMERA: Static from the ditch\.$/m);assert.ok(a.warnings.includes('direccion.camera no se aplica: el esqueleto ya trae CAMERA'));assert.match(a.prompt,/\[\[ACTION\]\]/);assert.match(a.prompt,/\[\[ACTING\]\]/);
 assert.ok(w.applyDireccion(frame().prompt,{acting:'ODILA is sad.'},{names:['ODILA']}).warnings.some(x=>/emoción.*sad/.test(x)));});
test('direccionErrors: formato antiguo, tipos de campos y locks',()=>{assert.deepEqual(w.direccionErrors({locks,blocks:{b01:{...d,fin:true,historial:[{camera:'x',hasta:'intento 1'}],otra:1}},_nota:'x'}),[]);assert.deepEqual(w.direccionErrors({}),[]);
 assert.deepEqual(w.direccionErrors({_nota:'x',b01:d}),['formato antiguo: mueve los bloques a "blocks" y las coletillas a "locks"']);assert.deepEqual(w.direccionErrors([]),['debe ser un objeto']);
 assert.deepEqual(w.direccionErrors({blocks:[]}),['blocks debe ser un objeto {bNN: {...}}']);
 assert.deepEqual(w.direccionErrors({blocks:{b01:{camera:3,fin:'sí'},b02:'x'}}),['blocks.b01.camera debe ser texto','blocks.b01.fin debe ser true o false','blocks.b02 debe ser un objeto']);
 assert.deepEqual(w.direccionErrors({blocks:{},locks:'x'}),['locks debe ser una lista']);assert.deepEqual(w.direccionErrors({blocks:{},locks:['a',{text:'b',when:'nunca'},{when:'cast'},3]}),['locks[1] debe ser texto o {text, when: "cast"|"always"}','locks[2] debe ser texto o {text, when: "cast"|"always"}','locks[3] debe ser texto o {text, when: "cast"|"always"}']);});
test('direccionBlock lee el formato nuevo y el antiguo',()=>{assert.equal(w.direccionBlock({blocks:{b01:d}},'b01'),d);assert.equal(w.direccionBlock({blocks:{b01:d}},'b02'),null);assert.equal(w.direccionBlock({blocks:{},b01:d},'b01'),null);assert.equal(w.direccionBlock({b01:d},'b01'),d);assert.equal(w.direccionBlock(null,'b01'),null);});
test('promptTargets: tabla completa',()=>{const G='prompt.generated.txt',P='prompt.txt';
 for(const exists of [false,true])for(const force of [false,true])for(const hasDireccion of [false,true])for(const directed of [false,true])for(const named of [false,true]){const r=w.promptTargets({exists,force,hasDireccion,directed,named});const skip=hasDireccion&&!directed&&exists&&!named;
  assert.deepEqual(r,skip?{skip:true,promptFile:null,writeRefs:false}:{skip:false,promptFile:exists&&!force?G:P,writeRefs:true},JSON.stringify({exists,force,hasDireccion,directed,named}));}});
test('mergeRefs: con dirección manda fin; sin dirección conserva endImage; endImage al final',()=>{const fresh={mode:'fotograma',image:'a.png',cast:[]},old={mode:'fotograma',image:'a.png',endImage:'old.png',x:1};
 assert.deepEqual(w.mergeRefs(fresh,old),{...fresh,endImage:'old.png'});assert.deepEqual(Object.keys(w.mergeRefs(fresh,old)).at(-1),'endImage');assert.deepEqual(w.mergeRefs(fresh,null),fresh);
 assert.deepEqual(w.mergeRefs(fresh,old,{directed:true,patch:{}}),fresh);assert.deepEqual(w.mergeRefs(fresh,null,{directed:true,patch:{endImage:'a.png'}}),{...fresh,endImage:'a.png'});
 assert.deepEqual(w.mergeRefs({...fresh,endImage:'z'},null),fresh);});
test('characterName: prefijo del descriptor base antes que variante; si no, shortName',()=>{const reg={assets:{X_RED:{kind:'character',character:'x',variant:'red',descriptor:'REDX: v.'},X_BASE:{kind:'character',character:'x',variant:'',descriptor:"THE FIRST MAN: b."},Y_RED:{kind:'character',character:'y',variant:'red',descriptor:'YVES: v.'},Z_BASE:{kind:'character',character:'z',descriptor:'a man.'}}};
 assert.equal(w.characterName(reg,project,'x'),'THE FIRST MAN');assert.equal(w.characterName(reg,project,'y'),'YVES');assert.equal(w.characterName(reg,{characters:[{id:'z',name:'Zoe Ann'}]},'z'),'ZOE');assert.equal(w.characterName(reg,null,'odila'),'ODILA');assert.deepEqual(frame(['odila','ancel']).names,['ODILA','ANCEL']);});
const base='GIRART: a hard man, upright in the saddle; a mail hauberk, a sword belt, boots; on the ring finger a ring of gold. Quiet authority.';
const reg={assets:{GIRART_BASE:{kind:'character',character:'girart',variant:'',descriptor:base,states:{foot:{drop:[', upright in the saddle'],note:'on foot'},bare:{drop:[', upright in the saddle',', a sword belt','; on the ring finger a ring of gold'],note:'dead; no ring'},calm:{note:'seated'}}},GIRART_RED:{kind:'character',character:'girart',variant:'red',descriptor:'x'}}};
test('parseCastRef y resolveDescriptor: quita en orden, añade la nota y señala errores',()=>{assert.deepEqual(w.parseCastRef('girart@foot'),{id:'girart',state:'foot'});assert.deepEqual(w.parseCastRef('girart'),{id:'girart',state:null});
 assert.deepEqual(w.resolveDescriptor(reg,'girart'),{id:'girart',state:null,tag:'GIRART_BASE',name:'GIRART',descriptor:base,errors:[]});
 assert.equal(w.resolveDescriptor(reg,'girart@foot').descriptor,'GIRART: a hard man; a mail hauberk, a sword belt, boots; on the ring finger a ring of gold. Quiet authority; on foot');
 assert.equal(w.resolveDescriptor(reg,'girart@bare').descriptor,'GIRART: a hard man; a mail hauberk, boots. Quiet authority; dead; no ring');assert.equal(w.resolveDescriptor(reg,'girart@calm').descriptor,base.slice(0,-1)+'; seated');
 assert.deepEqual(w.resolveDescriptor(reg,'girart@volando').errors,['GIRART_BASE: estado desconocido «volando» (hay foot, bare, calm)']);assert.deepEqual(w.resolveDescriptor(reg,'nadie').errors,['Sin entrada de registro para nadie']);
 const bad=structuredClone(reg);bad.assets.GIRART_BASE.states.foot.drop=[', riding'];assert.deepEqual(w.resolveDescriptor(bad,'girart@foot').errors,['GIRART_BASE@foot: no se encuentra «, riding» en el descriptor']);});
test('stateErrors: drops que no están, estados vacíos y tipos',()=>{assert.deepEqual(w.stateErrors('GIRART_BASE',reg.assets.GIRART_BASE),[]);assert.deepEqual(w.stateErrors('X',{descriptor:'a'}),[]);
 assert.deepEqual(w.stateErrors('X',{descriptor:'a, b.',states:{v:{},m:{drop:[', c']},n:{drop:'x',note:3},o:'x'}}),['X@v: sin drop ni note','X@m: no se encuentra «, c» en el descriptor','X@n: drop debe ser una lista de textos','X@n: note debe ser texto','X@o: debe ser un objeto {drop, note}']);
 assert.deepEqual(w.stateErrors('X',{states:[]}),['X: states debe ser un objeto']);});

// Integración: prompt.mjs sobre un lote temporal en RODAJE_DATA (test/setup.mjs).
const P='direccion-test',LOTE='sb-t01',root=path.join(DATA,P),out=path.join(root,'assets',LOTE);
const put=(rel,v)=>{const f=path.join(root,rel);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');};
const read=rel=>fs.readFileSync(path.join(out,rel),'utf8');
const snap=d=>fs.readdirSync(d,{recursive:true}).sort().map(f=>{const p=path.join(d,f);return fs.statSync(p).isDirectory()?f+'/':f+' '+createHash('sha256').update(fs.readFileSync(p)).digest('hex');});
const run=(...args)=>{const env={...process.env,RODAJE_DATA:DATA};delete env.RODAJE_PROJECT;return spawnSync(process.execPath,[path.join(import.meta.dirname,'..','scripts','bloques','prompt.mjs'),LOTE,...args,'--project',P],{encoding:'utf8',env,timeout:30000});};
function lote(){fs.rmSync(root,{recursive:true,force:true});
 const sh=id=>({id,title:`A0${id.slice(1)} · x`,duration:4,storyboardShot:'v'+id,storyboardRender:`storyboards/sb/render/A0${id.slice(1)}.png`,lines:[],camera:{position:[0,2,5],target:[0,1,0],fov:50}});
 const seq={id:'q1',title:'Q',location:'cruce',ambiencePrompt:'Wind.',shots:['s1','s2','s3'].map(sh)};
 const snapshot={id:P,characters:[{id:'odila',name:'Odila'}],locations:[],episodes:[{id:'e1',sequences:[seq]}],storyboards:[{id:'sb',sequences:[{id:'x',shots:['s1','s2','s3'].map(s=>({id:'v'+s,cast:['odila']}))}]}]};
 put('proyecto.json',{id:P,name:P,characters:snapshot.characters,locations:[],episodes:[]});put('registro.json',registry);put('ambientes/cruce/MAPA.md','# Mapa\n\n```prompt\nThe crossroads.\n```\n');
 put(`assets/${LOTE}/plan.json`,[...['b01','b02','b03'].map((b,i)=>({id:b,mode:'fotograma',duration:5,length:4,parts:[{shot:'s'+(i+1),from:0,to:4,at:0,lines:[]}]})),{id:'b04',mode:'block',cast:[],duration:5,length:4,parts:[{shot:'s1',from:0,to:4,at:0,lines:[]}]}]);
 put(`assets/${LOTE}/project-snapshot.json`,snapshot);put(`assets/${LOTE}/lote.json`,{episode:'e1',sequence:'q1'});
 put(`assets/${LOTE}/direccion.json`,{_nota:'x',locks,blocks:{b01:{...d,fin:true},b03:d,b04:d}});
 put(`assets/${LOTE}/b01/prompt.txt`,'VIEJO\n');put(`assets/${LOTE}/b02/prompt.txt`,'A MANO\n');put(`assets/${LOTE}/b04/prompt.txt`,'GUIA 3D\n');put(`assets/${LOTE}/b02/refs.json`,{mode:'fotograma',image:'storyboards/sb/render/A02.png',endImage:'storyboards/sb/render/A02.png'});}

test('prompt.mjs aplica direccion.json, conserva los bloques sin entrada y su endImage, y rechaza el formato antiguo',()=>{lote();const b02=[read('b02/prompt.txt'),read('b02/refs.json')];
 let r=run();assert.equal(r.status,0,r.stderr);assert.equal(read('b01/prompt.txt'),'VIEJO\n');const gen=read('b01/prompt.generated.txt');assert.doesNotMatch(gen,/\[\[/);assert.match(gen,/^CAMERA: Locked-off wide shot\.$/m);
 assert.match(r.stdout,/b02: sin dirección en direccion\.json; se conserva/);assert.match(r.stdout,/\nSin dirección: b02\n/);assert.match(r.stdout,/b04: dirección ignorada: solo modo fotograma/);assert.doesNotMatch(r.stdout,/b04: sin dirección/);assert.equal(read('b04/prompt.txt'),'GUIA 3D\n');assert.ok(fs.existsSync(path.join(out,'b03','prompt.txt')));
 r=run('--force');assert.equal(r.status,0,r.stderr);assert.equal(read('b01/prompt.txt'),gen);assert.equal(JSON.parse(read('b01/refs.json')).endImage,'storyboards/sb/render/A01.png');
 assert.doesNotMatch(read('b03/prompt.txt'),/\[\[/);assert.equal(JSON.parse(read('b03/refs.json')).endImage,undefined);assert.deepEqual([read('b02/prompt.txt'),read('b02/refs.json')],b02);assert.ok(!fs.existsSync(path.join(out,'b02','prompt.generated.txt')));
 r=run('b02','--force');assert.equal(r.status,0,r.stderr);assert.match(read('b02/prompt.txt'),/\[\[CAMERA\]\]/);const refs=JSON.parse(read('b02/refs.json'));assert.equal(refs.endImage,'storyboards/sb/render/A02.png');assert.equal(Object.keys(refs).at(-1),'endImage');assert.equal(refs.duration,5);
 put(`assets/${LOTE}/direccion.json`,{_nota:'x',b01:d});const before=snap(out);r=run('--force');assert.equal(r.status,1);assert.match(r.stderr,/formato antiguo/);assert.equal(r.stdout,'');assert.deepEqual(snap(out),before);
 fs.rmSync(root,{recursive:true,force:true});});
test('registro.mjs describe imprime el descriptor con estado; check y render conocen los estados',()=>{const Q='estados-test',dir=path.join(DATA,Q);fs.rmSync(dir,{recursive:true,force:true});fs.mkdirSync(dir,{recursive:true});
 fs.writeFileSync(path.join(dir,'proyecto.json'),JSON.stringify({id:Q,name:Q,characters:[],locations:[],episodes:[]}));fs.writeFileSync(path.join(dir,'registro.json'),JSON.stringify(reg));
 const env={...process.env,RODAJE_DATA:DATA};delete env.RODAJE_PROJECT;const reg1=(...a)=>spawnSync(process.execPath,[path.join(import.meta.dirname,'..','scripts','registro.mjs'),...a],{encoding:'utf8',env,timeout:30000});
 let r=reg1('describe',Q,'girart@foot','girart');assert.equal(r.status,0,r.stderr);assert.equal(r.stdout,w.resolveDescriptor(reg,'girart@foot').descriptor+'\n'+base+'\n');assert.match(r.stderr,/Proyecto: estados-test \(argumento\)/);
 r=reg1('describe','girart@foot','--project',Q);assert.equal(r.status,0,r.stderr);assert.match(r.stderr,/\(--project\)/);
 r=reg1('describe','girart@volando','--project',Q);assert.equal(r.status,1);assert.match(r.stderr,/girart@volando: GIRART_BASE: estado desconocido/);
 r=reg1('render','--project',Q);assert.equal(r.status,0,r.stderr);const md=fs.readFileSync(path.join(dir,'REGISTRO.md'),'utf8');assert.match(md,/## Estados/);assert.match(md,/\| `girart@bare` \| `GIRART_BASE` \| «, upright in the saddle»<br>«, a sword belt»<br>«; on the ring finger a ring of gold» \| dead; no ring \|/);
 const bad=structuredClone(reg);bad.assets.GIRART_BASE.states.foot.drop=[', riding'];fs.writeFileSync(path.join(dir,'registro.json'),JSON.stringify(bad));r=reg1('check','--project',Q);assert.equal(r.status,1);assert.match(r.stderr,/GIRART_BASE@foot: no se encuentra «, riding»/);
 fs.rmSync(dir,{recursive:true,force:true});});
