import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import * as T from 'three';
const {DATA}=await import('../app/store.mjs');const e3=await import('../lib/entorno3d.mjs');
const id='e3d-'+process.pid,base=path.join(DATA,id);
const builder=`export function build(T,data,{state}={}){const root=new T.Group();root.name='caja-raiz';for(const b of [...data.boxes,...(state?.extra||[])]){const m=new T.Mesh(new T.BoxGeometry(...b.size),new T.MeshBasicMaterial());m.name=b.name;m.position.set(...b.pos);root.add(m);}return root;}\n`;
// Dos cajas separadas en el estado por defecto; el preset añade una que comparte la cara x+ de «a».
const model={boxes:[{name:'a',pos:[0,1,0],size:[1,1,1]},{name:'b',pos:[3,1,0],size:[1,1,1]}],presets:[{id:'pegada',state:{extra:[{name:'c',pos:[0,1,0.2],size:[1,1,1]}]}}]};
fs.mkdirSync(path.join(base,'3d'),{recursive:true});fs.writeFileSync(path.join(base,'3d/b.js'),builder);fs.writeFileSync(path.join(base,'3d/m.json'),JSON.stringify(model));
fs.writeFileSync(path.join(base,'proyecto.json'),JSON.stringify({id,name:'Entornos',type:'serie',ideas:[],characters:[],locations:[],episodes:[],environments:[{id:'caja',builder:'3d/b.js',data:'3d/m.json'},{id:'solo-glb',glb:'x.glb'},{id:'sin-datos',builder:'3d/b.js'}]}));
const box=(name,pos,size=[1,1,1])=>{const m=new T.Mesh(new T.BoxGeometry(...size),new T.MeshBasicMaterial());m.name=name;m.position.set(...pos);return m;};
const group=(...ms)=>{const g=new T.Group();g.add(...ms);return g;};
const files=()=>fs.readdirSync(base,{recursive:true}).sort();

test('descubre solo los entornos con constructor y datos',()=>{assert.ok(e3.projectIds().includes(id));assert.deepEqual(e3.environmentsWithBuilder().filter(x=>x.projectId===id),[{projectId:id,envId:'caja'}]);});
test('loadEnvironment da errores claros',async()=>{await assert.rejects(e3.loadEnvironment(id,'nada'),/Entorno no encontrado: nada/);await assert.rejects(e3.loadEnvironment(id,'solo-glb'),/no tiene constructor/);await assert.rejects(e3.loadEnvironment(id,'sin-datos'),/no tiene constructor/);const ctx=await e3.loadEnvironment(id,'caja');assert.equal(ctx.env.id,'caja');assert.equal(ctx.base,base);assert.equal(typeof ctx.build,'function');assert.equal(ctx.data.boxes.length,2);});
test('exportGlb devuelve un GLB estable sin escribir en disco',async()=>{const ctx=await e3.loadEnvironment(id,'caja'),before=files();const a=await e3.exportGlb(e3.buildEnvironment(ctx,{textures:false}),{quiet:true});const b=await e3.exportGlb(e3.buildEnvironment(ctx,{textures:false}));assert.equal(a.buffer.subarray(0,4).toString(),'glTF');assert.equal(a.meshes,2);assert.equal(a.bytes,a.buffer.length);assert.match(a.sha256,/^[0-9a-f]{64}$/);assert.equal(a.sha256,b.sha256);const c=await e3.exportGlb(e3.buildEnvironment(ctx,{state:ctx.data.presets[0].state}),{quiet:true});assert.equal(c.meshes,3);assert.notEqual(c.sha256,a.sha256);assert.deepEqual(files(),before);});
test('quiet silencia console.warn solo durante la exportación',async()=>{const warn=console.warn;await e3.exportGlb(group(box('a',[0,1,0])),{quiet:true});assert.equal(console.warn,warn);});
test('coplanarPairs detecta caras solapadas y respeta el suelo',()=>{const pegadas=e3.coplanarPairs(group(box('a',[0,1,0]),box('b',[0,1,0.5])));assert.ok(pegadas.size>=1);assert.ok([...pegadas.keys()].every(k=>k.startsWith('a ↔ b (')));
 const cara=e3.coplanarPairs(group(box('a',[0,1,0]),box('b',[0.5,0.5,0.5],[1,2,1])));assert.deepEqual([...cara.keys()],['a ↔ b (y+ 1.50)']);
 assert.equal(e3.coplanarPairs(group(box('a',[0,1,0]),box('b',[3,1,0]))).size,0);
 assert.equal(e3.coplanarPairs(group(box('a',[0,0.5,0]),box('b',[0.5,1,0.5],[1,2,1]))).size,0);assert.deepEqual([...e3.coplanarPairs(group(box('a',[0,1.5,0]),box('b',[0.5,2,0.5],[1,2,1]))).keys()],['a ↔ b (y− 1.00)']);});
test('coplanarReport suma defecto y presets con --todos',async()=>{const ctx=await e3.loadEnvironment(id,'caja');const r=e3.coplanarReport(ctx,'--todos');assert.deepEqual(r.porPreset,{defecto:0,pegada:e3.coplanarReport(ctx,'pegada').total});assert.ok(r.porPreset.pegada>0);assert.equal(r.total,r.porPreset.defecto+r.porPreset.pegada);assert.deepEqual([...r.pares.keys()],['defecto','pegada']);assert.deepEqual(e3.coplanarReport(ctx).porPreset,{defecto:0});assert.throws(()=>e3.coplanarReport(ctx,'otro'),/Preset no encontrado: otro/);});
