// lib/media.mjs (issue #5): semántica de ffprobe/ffmpeg con los binarios falsos de test/fixtures/bin, en subproceso.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
const ROOT=path.resolve(import.meta.dirname,'..'),media=await import('../lib/media.mjs');
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'rodaje-media-'));
// Ejecuta código con lib/media importado como `m` y ffmpeg/ffprobe falsos en PATH. Devuelve {status,stdout,stderr,log}.
function withShim(code,env={}){const d=tmp(),log=path.join(d,'log.jsonl');const r=spawnSync(process.execPath,['--input-type=module','-e',`const m=await import(${JSON.stringify(new URL('../lib/media.mjs',import.meta.url).href)});const d=${JSON.stringify(d)};${code}`],{encoding:'utf8',env:{...process.env,RODAJE_MOCK_LOG:log,PATH:[path.join(ROOT,'test/fixtures/bin'),path.dirname(process.execPath),process.env.PATH].join(path.delimiter),...env}});return {...r,log:fs.existsSync(log)?fs.readFileSync(log,'utf8').split('\n').filter(Boolean).map(l=>JSON.parse(l)):[]};}
test('probeDuration lanza si ffprobe falla; probeDurationOrNull devuelve null',()=>{const r=withShim(`import('node:fs').then(fs=>{fs.writeFileSync(d+'/voz-2.5s.wav','x');let lanza=false;try{m.probeDuration(d+'/no.wav');}catch{lanza=true;}console.log(JSON.stringify({lanza,nulo:m.probeDurationOrNull(d+'/no.wav'),dur:m.probeDuration(d+'/voz-2.5s.wav'),dur2:m.probeDurationOrNull(d+'/voz-2.5s.wav')}));});`);
 assert.equal(r.status,0,r.stderr);assert.deepEqual(JSON.parse(r.stdout),{lanza:true,nulo:null,dur:2.5,dur2:2.5});assert.deepEqual(r.log[0],{kind:'exec',bin:'ffprobe',argv:['-v','error','-show_entries','format=duration','-of','default=nw=1:nk=1',r.log[0].argv.at(-1)]});});
test('ffmpeg captura por defecto (stderr en el error) y hereda con inherit; ffmpegStdout sin -y devuelve stdout',()=>{
 const cap=withShim(`try{m.ffmpeg(['-i','a',1.5,d+'/o.wav']);console.log('no lanza');}catch(e){console.log('msg:'+/falla simulada/.test(e.message));}`,{RODAJE_MOCK_FFMPEG_FAIL:'1'});assert.equal(cap.stdout.trim(),'msg:true');assert.deepEqual(cap.log[0].argv.slice(0,5),['-y','-v','error','-i','a']);assert.equal(cap.log[0].argv[5],'1.5');
 const inh=withShim(`try{m.ffmpeg(['-i','a',d+'/o.wav'],{inherit:true});}catch(e){console.log('msg:'+/falla simulada/.test(e.message));}`,{RODAJE_MOCK_FFMPEG_FAIL:'1'});assert.equal(inh.stdout.trim(),'msg:false');assert.match(inh.stderr,/falla simulada/);
 const out=withShim(`import('node:fs').then(fs=>{fs.writeFileSync(d+'/a.png','x');console.log(m.ffmpegStdout(['-i',d+'/a.png','-f','rawvideo','-']).length);});`);assert.equal(out.stdout.trim(),String(96*64));assert.deepEqual(out.log[0].argv.slice(0,2),['-v','error']);});
test('lib/media: 10 MB de captura y sin timeouts',()=>{assert.deepEqual(media.CAPTURE,{maxBuffer:10485760});assert.doesNotMatch(fs.readFileSync(path.join(ROOT,'lib/media.mjs'),'utf8'),/\btimeout\s*:/);});
test('ffmpeg y ffprobe síncronos solo desde lib/media (salvo ffmpeg -version de server.mjs)',()=>{const files=[...['app','scripts'].flatMap(d=>fs.readdirSync(path.join(ROOT,d),{recursive:true}).filter(f=>f.endsWith('.mjs')).map(f=>path.join(d,f))),...fs.readdirSync(path.join(ROOT,'lib')).filter(f=>f.endsWith('.mjs')&&f!=='media.mjs').map(f=>path.join('lib',f))];
 const bad=files.flatMap(f=>[...fs.readFileSync(path.join(ROOT,f),'utf8').matchAll(/execFileSync\(\s*['"]ff(?:mpeg|probe)['"]\s*,\s*(\[[^\]]*\])/g)].filter(m=>!(f===path.join('app','server.mjs')&&m[1]==="['-version']")).map(m=>f+': '+m[0]));assert.deepEqual(bad,[]);});
// lib/fal.mjs y lib/tts.mjs (issue #25).
const fal=await import('../lib/fal.mjs'),tts=await import('../lib/tts.mjs');
test('falKey: config.local.json > FAL_KEY del entorno > .env, sin mutar process.env',()=>{const d=tmp(),envFile=path.join(d,'.env');fs.writeFileSync(envFile,'FAL_KEY=de-env-file\n');const before={...process.env};
 assert.equal(fal.falKey({settings:{falKey:'a',FAL_KEY:'b'},env:{FAL_KEY:'c'},envFile}),'a');assert.equal(fal.falKey({settings:{FAL_KEY:'b'},env:{FAL_KEY:'c'},envFile}),'b');
 assert.equal(fal.falKey({settings:{},env:{FAL_KEY:'c'},envFile}),'c');assert.equal(fal.falKey({settings:{},env:{FAL_KEY:''},envFile}),'de-env-file');
 assert.equal(fal.falKey({settings:{},env:{},envFile:path.join(d,'no.env')}),'');assert.ok(JSON.stringify({...process.env})===JSON.stringify(before),'falKey no debe mutar process.env');
 const s=path.join(d,'config.local.json');assert.deepEqual(fal.readSettings(s),{});fs.writeFileSync(s,'{"falKey":"k"}');assert.deepEqual(fal.readSettings(s),{falKey:'k'});});
test('RODAJE_CONFIG_DIR fija config.local.json y .env; importar lib/fal no toca el disco',()=>{const d=path.join(tmp(),'no','existe');const r=spawnSync(process.execPath,['--input-type=module','-e',`const f=await import(${JSON.stringify(new URL('../lib/fal.mjs',import.meta.url).href)});console.log(JSON.stringify([f.CONFIG_DIR,f.SETTINGS_FILE,f.ENV_FILE]))`],{encoding:'utf8',env:{...process.env,RODAJE_CONFIG_DIR:d,RODAJE_DATA:d}});
 assert.equal(r.status,0,r.stderr);assert.deepEqual(JSON.parse(r.stdout),[d,path.join(d,'config.local.json'),path.join(d,'.env')]);assert.equal(fs.existsSync(path.dirname(d)),false);assert.equal(fal.SETTINGS_FILE,path.join(process.env.RODAJE_CONFIG_DIR,'config.local.json'));});
test('falClient: sin clave lanza el mensaje de cada llamador; con clave devuelve un cliente',async()=>{await assert.rejects(fal.falClient({key:''}),{message:'Falta FAL_KEY (.env o config.local.json)'});assert.equal(fal.MISSING_KEY,'Falta FAL_KEY (.env o config.local.json)');
 await assert.rejects(fal.falClient({key:'',message:'Añade tu clave fal.ai en Ajustes'}),{message:'Añade tu clave fal.ai en Ajustes'});const c=await fal.falClient({key:'test:dummy'});assert.equal(typeof c.queue.submit,'function');});
test('lib/fal: envoltorios de cola, subida, URL de salida y descarga',async()=>{const calls=[];const client={queue:{submit:(...a)=>calls.push(['submit',...a]),status:(...a)=>calls.push(['status',...a]),result:(...a)=>calls.push(['result',...a])},subscribe:(...a)=>calls.push(['subscribe',...a]),storage:{upload:f=>f}};
 fal.submit(client,'e',{x:1});fal.status(client,'e','r1');fal.result(client,'e','r1');fal.subscribe(client,'e',{y:2});assert.deepEqual(calls,[['submit','e',{input:{x:1}}],['status','e',{requestId:'r1',logs:false}],['result','e',{requestId:'r1'}],['subscribe','e',{input:{y:2}}]]);
 const d=tmp(),f=path.join(d,'a.wav');fs.writeFileSync(f,'abc');const u=fal.uploadFile(client,f);assert.equal(u.name,'a.wav');assert.equal(u.type,'');assert.equal(await u.text(),'abc');assert.equal(fal.uploadFile(client,f,{type:'audio/wav'}).type,'audio/wav');
 assert.equal(fal.outputUrl({video:{url:'v'},audio:{url:'a'}}),'v');assert.equal(fal.outputUrl({audio:{url:'a'},images:[{url:'i'}]}),'a');assert.equal(fal.outputUrl({images:[{url:'i'}]}),'i');assert.equal(fal.outputUrl({}),undefined);
 const orig=globalThis.fetch;try{globalThis.fetch=async url=>url==='ok'?new Response('bytes'):new Response('',{status:404});assert.equal((await fal.download('ok')).toString(),'bytes');
  await assert.rejects(fal.download('mal'),{message:'No se pudo descargar el resultado'});await assert.rejects(fal.download('mal',{error:'Descarga fallida b01'}),{message:'Descarga fallida b01'});}finally{globalThis.fetch=orig;}});
test('lib/tts: payloads exactos (orden de claves incluido) y endpoints por fal',()=>{const j=v=>JSON.stringify(v);
 assert.equal(j(tts.elevenV3Input({text:'Hi',voice:'v',stability:.4,language:'en'})),'{"text":"Hi","voice":"v","stability":0.4,"language_code":"en"}');
 assert.equal(j(tts.soundEffectsInput('rain')),'{"text":"rain","duration_seconds":22,"loop":true,"prompt_influence":0.3,"output_format":"mp3_44100_128"}');
 assert.equal(j(tts.minimaxSpeechInput({text:'[calm] Hi [soft]there',voice:'m',speed:1.1})),'{"text":"Hi there","voice_setting":{"voice_id":"m","speed":1.1},"language_boost":"English","output_format":"url"}');
 assert.equal(j(tts.voiceChangerInput({audioUrl:'u',voice:'v'})),'{"audio_url":"u","voice":"v","remove_background_noise":true}');
 assert.equal(j(tts.voiceDesignInput({prompt:'p',previewText:'t'})),'{"prompt":"p","preview_text":"t"}');
 assert.deepEqual([tts.ELEVEN_V3,tts.ELEVEN_SFX,tts.ELEVEN_VOICE_CHANGER,tts.MINIMAX_SPEECH,tts.MINIMAX_VOICE_DESIGN],['fal-ai/elevenlabs/tts/eleven-v3','fal-ai/elevenlabs/sound-effects/v2','fal-ai/elevenlabs/voice-changer','fal-ai/minimax/speech-02-hd','fal-ai/minimax/voice-design']);
 for(const [k,v] of Object.entries(tts))if(typeof v==='string'&&/elevenlabs/i.test(v))assert.match(v,/^fal-ai\/elevenlabs\//,k);});
test('lib/tts: speak, changeVoice y designVoice con sus valores por defecto y mensajes',async()=>{const calls=[];const mk=data=>({subscribe:async(e,o)=>{calls.push([e,o.input]);return {data};},storage:{upload:async f=>'up:'+f.name}});const orig=globalThis.fetch;
 try{globalThis.fetch=async url=>new Response('mp3:'+url);const c=mk({audio:{url:'u'}});
  assert.equal((await tts.speak(c,{text:'Hi',voice:'v',language:'en'})).toString(),'mp3:u');assert.equal((await tts.speak(c,{model:'minimax',text:'[x] Hi',voice:'m'})).toString(),'mp3:u');
  const d=tmp(),f=path.join(d,'g.wav');fs.writeFileSync(f,'x');await tts.changeVoice(c,{file:f,voice:'v'});
  assert.deepEqual(calls,[['fal-ai/elevenlabs/tts/eleven-v3',{text:'Hi',voice:'v',stability:.5,language_code:'en'}],['fal-ai/minimax/speech-02-hd',{text:'Hi',voice_setting:{voice_id:'m',speed:1},language_boost:'English',output_format:'url'}],['fal-ai/elevenlabs/voice-changer',{audio_url:'up:g.wav',voice:'v',remove_background_noise:true}]]);
  const none=mk({});await assert.rejects(tts.speak(none,{text:'a',voice:'v'}),{message:'ElevenLabs no devolvió audio'});await assert.rejects(tts.speak(none,{model:'minimax',text:'a',voice:'v'}),{message:'MiniMax no devolvió audio'});
  await assert.rejects(tts.changeVoice(none,{file:f,voice:'v'}),{message:'El cambiador de voz no devolvió audio'});await assert.rejects(tts.designVoice(none,{prompt:'p',previewText:'t'}),{message:'MiniMax no devolvió custom_voice_id'});
  assert.deepEqual(await tts.designVoice(mk({custom_voice_id:'id1'}),{prompt:'p',previewText:'t'}),{id:'id1',url:null});assert.deepEqual(await tts.designVoice(mk({custom_voice_id:'id1',audio:{url:'m'}}),{prompt:'p',previewText:'t'}),{id:'id1',url:'m'});}finally{globalThis.fetch=orig;}});
const sources=()=>[...['app','scripts'].flatMap(d=>fs.readdirSync(path.join(ROOT,d),{recursive:true}).filter(f=>f.endsWith('.mjs')).map(f=>path.join(d,f))),...fs.readdirSync(path.join(ROOT,'lib')).filter(f=>f.endsWith('.mjs')).map(f=>path.join('lib',f))];
test('cliente de fal y endpoints de voz solo desde lib/',()=>{const bad=sources().filter(f=>!f.startsWith('lib'+path.sep)).flatMap(f=>[...fs.readFileSync(path.join(ROOT,f),'utf8').matchAll(/createFalClient\(|client\.subscribe\(\s*['"]fal-ai\/(?:elevenlabs|minimax)|['"]@fal-ai\/client['"]/g)].map(m=>f+': '+m[0]));assert.deepEqual(bad,[]);});
test('guarda comercial: ElevenLabs solo por fal (sin su API directa en app, lib ni scripts)',()=>{const files=[...sources(),...fs.readdirSync(path.join(ROOT,'app')).filter(f=>f.endsWith('.source.js')).map(f=>path.join('app',f))];
 const bad=files.flatMap(f=>[...fs.readFileSync(path.join(ROOT,f),'utf8').matchAll(/api\.elevenlabs\.io|xi-api-key|ELEVENLABS_API/gi)].map(m=>f+': '+m[0]));assert.deepEqual(bad,[]);});
