// lib/media.mjs (issue #5): semántica de ffprobe/ffmpeg con los binarios falsos de test/fixtures/bin, en subproceso.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
const ROOT=path.resolve(import.meta.dirname,'..'),media=await import('../lib/media.mjs');
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'rodaje-media-'));
// Ejecuta código con lib/media importado como `m` y ffmpeg/ffprobe falsos en PATH. Devuelve {status,stdout,stderr,log}.
function withShim(code,env={}){const d=tmp(),log=path.join(d,'log.jsonl');const r=spawnSync(process.execPath,['--input-type=module','-e',`const m=await import(${JSON.stringify(new URL('../lib/media.mjs',import.meta.url).href)});const d=${JSON.stringify(d)};${code}`],{encoding:'utf8',env:{...process.env,RODAJE_MOCK_LOG:log,PATH:[path.join(ROOT,'test/fixtures/bin'),path.dirname(process.execPath),process.env.PATH].join(path.delimiter),...env}});return {...r,log:fs.existsSync(log)?fs.readFileSync(log,'utf8').split('\n').filter(Boolean).map(l=>JSON.parse(l)):[]};}
test('probeDuration lanza si ffprobe falla; probeDurationOrNull devuelve null',()=>{const r=withShim(`import('node:fs').then(fs=>{fs.writeFileSync(d+'/voz-2.5s.wav','x');let lanza=false;try{m.probeDuration(d+'/no.wav');}catch{lanza=true;}console.log(JSON.stringify({lanza,nulo:m.probeDurationOrNull(d+'/no.wav'),dur:m.probeDuration(d+'/voz-2.5s.wav'),dur2:m.probeDurationOrNull(d+'/voz-2.5s.wav')}));});`);
 assert.equal(r.status,0,r.stderr);assert.deepEqual(JSON.parse(r.stdout),{lanza:true,nulo:null,dur:2.5,dur2:2.5});assert.deepEqual(r.log[0],{kind:'exec',bin:'ffprobe',argv:['-v','error','-show_entries','format=duration','-of','default=nw=1:nk=1',r.log[0].argv.at(-1)]});});
test('ffmpeg captura por defecto (stderr en el error) y hereda con inherit; ffmpegStdout sin -y devuelve stdout',()=>{
 const cap=withShim(`try{m.ffmpeg(['-i','a',1.5,d+'/o.wav']);console.log('no lanza');}catch(e){console.log('msg:'+/falla simulada/.test(e.message));}`,{RODAJE_MOCK_FFMPEG_FAIL:'1'});assert.equal(cap.stdout.trim(),'msg:true');assert.deepEqual(cap.log[0].argv.slice(0,5),['-y','-v','error','-i','a']);assert.equal(cap.log[0].argv[5],'1.5');
 const inh=withShim(`try{m.ffmpeg(['-i','a',d+'/o.wav'],{inherit:true});}catch(e){console.log('msg:'+/falla simulada/.test(e.message));}`,{RODAJE_MOCK_FFMPEG_FAIL:'1'});assert.equal(inh.stdout.trim(),'msg:false');assert.match(inh.stderr,/falla simulada/);
 const out=withShim(`import('node:fs').then(fs=>{fs.writeFileSync(d+'/a.png','x');console.log(m.ffmpegStdout(['-i',d+'/a.png','-f','rawvideo','-']).length);});`);assert.equal(out.stdout.trim(),String(96*64));assert.deepEqual(out.log[0].argv.slice(0,2),['-v','error']);});
test('lib/media: 10 MB de captura y sin timeouts',()=>{assert.deepEqual(media.CAPTURE,{maxBuffer:10485760});assert.doesNotMatch(fs.readFileSync(path.join(ROOT,'lib/media.mjs'),'utf8'),/\btimeout\s*:/);});
test('ffmpeg y ffprobe síncronos solo desde lib/media (salvo ffmpeg -version de server.mjs)',()=>{const files=[...['app','scripts'].flatMap(d=>fs.readdirSync(path.join(ROOT,d),{recursive:true}).filter(f=>f.endsWith('.mjs')).map(f=>path.join(d,f))),...fs.readdirSync(path.join(ROOT,'lib')).filter(f=>f.endsWith('.mjs')&&f!=='media.mjs').map(f=>path.join('lib',f))];
 const bad=files.flatMap(f=>[...fs.readFileSync(path.join(ROOT,f),'utf8').matchAll(/execFileSync\(\s*['"]ff(?:mpeg|probe)['"]\s*,\s*(\[[^\]]*\])/g)].filter(m=>!(f===path.join('app','server.mjs')&&m[1]==="['-version']")).map(m=>f+': '+m[0]));assert.deepEqual(bad,[]);});
