import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';process.env.RODAJE_DATA=fs.mkdtempSync(path.join(os.tmpdir(),'rodaje-providers-'));const {create,save,dir,newShot,digest}=await import('../app/store.mjs');const {inputFor}=await import('../app/jobs.mjs');
test('H3 receives exact approved motion, audio, frame and reference order',async()=>{const p=create('Adapter check');for(const f of ['ref.png','env.png','snap.png','frame.png','motion.mp4','audio.wav'])fs.writeFileSync(path.join(dir(p.id),'assets',f),'fixture');p.characters=[{id:'c',name:'Sol',description:'A pilot',image:'assets/ref.png',voice:'voice-1'}];p.locations=[{id:'l',name:'Hangar',image:'assets/env.png'}];const t=newShot('Take'),s={id:'s',location:'l',cast:[{character:'c',x:0,z:0,yaw:0}],silent:true,shots:[t]};p.episodes=[{id:'e',sequences:[s]}];t.duration=6.2;t.lines=[{id:'line',character:'c',text:'Hello',start:1}];const hash=digest(p,t.id);t.preview={hash,snapshot:'assets/snap.png',padded:'assets/motion.mp4',paddedAudio:'assets/audio.wav'};t.keyframe={hash,file:'assets/frame.png'};save(p);const j={project:p.id,target:t.id,type:'video',snapshot:p,hash},client={storage:{upload:async f=>'https://test.invalid/'+f.name}};const r=await inputFor(j,client);assert.equal(r.endpoint,'minimax/h3-max/reference-to-video');assert.equal(r.input.duration,7);assert.deepEqual(r.input.reference_image_urls,['https://test.invalid/frame.png','https://test.invalid/ref.png','https://test.invalid/env.png']);assert.deepEqual(r.input.reference_video_urls,['https://test.invalid/motion.mp4']);assert.deepEqual(r.input.reference_audio_urls,['https://test.invalid/audio.wav']);t.keyframe.hash='old';await assert.rejects(inputFor(j,client),/fotograma/);});
test('speech request uses selected voice, language and exact line',async()=>{const p=create('Voice adapter');p.language='es';p.characters=[{id:'c',voice:'selected-voice'}];const t=newShot();t.lines=[{id:'l',character:'c',text:'Gracias por venir.',start:1}];p.episodes=[{id:'e',sequences:[{id:'s',shots:[t]}]}];const r=await inputFor({type:'line',snapshot:p,target:t.id,extra:{line:'l'}},{});assert.equal(r.input.voice,'selected-voice');assert.equal(r.input.language_code,'es');assert.equal(r.input.text,'Gracias por venir.');});
test('cover request sends the sequence prompt as a single 16:9 image without references',async()=>{const p=create('Cover adapter');p.style='Muted.';p.episodes=[{id:'e',title:'Acto I',sequences:[{id:'s',title:'La carga',text:'Dawn charge.',coverPrompt:'A knight at dawn.',cast:[],shots:[]}]}];const r=await inputFor({type:'cover',snapshot:p,target:'s'},{});assert.equal(r.endpoint,'fal-ai/nano-banana-pro');assert.equal(r.input.prompt,'A knight at dawn.');assert.equal(r.input.aspect_ratio,'16:9');assert.equal(r.input.image_urls,undefined);});


// ---- Golden de peticiones y argv de ffmpeg/ffprobe (issue #5), sin red ni coste: harness.mjs y golden/ en test/fixtures/providers/.
// Grabar solo sobre el código anterior al refactor: RODAJE_GOLDEN=grabar node --import ./test/setup.mjs --test test/providers.test.mjs
const H=await import('./fixtures/providers/harness.mjs');
test('el golden no se regraba sobre el código refactorizado',()=>assert.equal(H.RECORD_BLOCKED,null));
const APP_JOBS=['character','character-ref','location','voice','line','ambience','keyframe','video','storyboard','cover','outline','export','preview'];
let app;const appRun=()=>app??=H.runApp();
for(const name of APP_JOBS)test(`golden app: ${name}`,()=>{const got=appRun().log(name);assert.ok(got.length,'sin registro para '+name);assert.deepEqual(got,H.golden(`app/${name}.jsonl`,got));});
test('golden app: resumen de run()',()=>{const got=appRun().summary;assert.deepEqual(got,H.golden('app/resumen.json',got));});
const cli=(name,script,args,data=H.cliData())=>test(`golden cli: ${name}`,()=>{const r=H.runCli(typeof data==='function'?data():data,script,args,{name});assert.equal(r.status,0,r.stderr);assert.deepEqual(r.lines,H.golden(`cli/${name}.jsonl`,r.lines));});
cli('voces-prueba','scripts/bloques/voces.mjs',['prueba','--voz','voz-ana','--texto','Hello there.','--yes']);
cli('voces-prueba-minimax','scripts/bloques/voces.mjs',['prueba','--voz','voz-beto','--texto','Hello there.','--modelo','minimax','--yes']);
cli('voces-lineas','scripts/bloques/voces.mjs',['lineas','ep01','s01','--yes']);
{const d=H.cliData();cli('voces-cambiar','scripts/bloques/voces.mjs',['cambiar','ep01','s01','l01',path.join(d,H.CLI_PROJECT,'grabacion.wav'),'--yes'],d);}
cli('voces-disenar','scripts/bloques/voces.mjs',['disenar','--personaje','ana','--descripcion','Warm low voice','--texto','We leave at dawn.','--yes']);
// Cadena sobre la misma copia: enviar referencia → enviar fotograma (la caché evita subir dos veces el mismo fotograma) → estado → montar.
{const d=H.cliData();cli('enviar-b01','scripts/bloques/enviar.mjs',['lote-a','b01','--yes'],d);cli('enviar-b02','scripts/bloques/enviar.mjs',['lote-a','b02','--yes'],d);cli('estado','scripts/bloques/estado.mjs',['lote-a'],d);cli('montar','scripts/bloques/montar.mjs',['lote-a'],d);}
test('golden cli: fusionar',async()=>{const got=await H.runFusionar(H.cliData());assert.deepEqual(got,H.golden('cli/fusionar.jsonl',got));});
test('app sin clave: el trabajo falla con el mensaje de Ajustes y no hay peticiones',{skip:fs.existsSync(path.join(H.ROOT,'config.local.json'))&&'hay config.local.json en el repositorio'},()=>{const r=H.runApp({jobs:['character'],env:{FAL_KEY:''}});assert.equal(r.summary[0].status,'failed');assert.equal(r.summary[0].error,'Añade tu clave fal.ai en Ajustes');assert.deepEqual(r.log('character'),[]);});
test('app: un ffmpeg fallido en la exportación deja su stderr en j.error',()=>{const r=H.runApp({jobs:['export'],env:{RODAJE_MOCK_FFMPEG_FAIL:'1'}});assert.equal(r.summary[0].status,'failed');assert.match(r.summary[0].error,/falla simulada/);});
test('montar: un ffmpeg fallido sale con código distinto de 0, su stderr heredado y una línea propia, sin traza de Node',()=>{const r=H.runCli(H.cliData(),'scripts/bloques/montar.mjs',['lote-a'],{env:{RODAJE_MOCK_FFMPEG_FAIL:'1'}});assert.notEqual(r.status,0);assert.match(r.stderr,/falla simulada/);
 assert.doesNotMatch(r.stderr,/Node\.js v/);assert.doesNotMatch(r.stderr,/^\s+at /m);const tail=r.stderr.trim().split('\n').slice(-3);assert.match(tail.at(-1),/^montar: ffmpeg falló \(código 1\) en b01 /);assert.ok(tail.includes('falla simulada'),tail.join('\n'));});
test('el golden solo contiene hosts simulados y la clave de prueba, sin ElevenLabs directo',()=>{const files=fs.readdirSync(H.GOLDEN,{recursive:true}).filter(f=>f.endsWith('.jsonl'));assert.ok(files.length>=23);
 for(const f of files){const text=fs.readFileSync(path.join(H.GOLDEN,f),'utf8');assert.doesNotMatch(text,/api\.elevenlabs|xi-api/i,f);
  for(const line of text.split('\n').filter(Boolean)){const e=JSON.parse(line);if(e.kind!=='fetch')continue;assert.ok(['rest.fal.ai','queue.fal.run'].includes(new URL(e.url).hostname)||new URL(e.url).hostname.endsWith('.mock.invalid'),e.url);assert.ok(e.auth===null||e.auth==='Key test:dummy',f);}}});
test('montar: concat.txt con rutas relativas a la carpeta del montaje',async()=>{const {ABS_RE}=await import('../lib/proyecto-check.mjs');const d=H.cliData(),r=H.runCli(d,'scripts/bloques/montar.mjs',['lote-a']);assert.equal(r.status,0,r.stderr);
 const text=fs.readFileSync(path.join(d,H.CLI_PROJECT,'assets/lote-a/montaje/concat.txt'),'utf8'),lines=text.trimEnd().split('\n');
 assert.doesNotMatch(text,ABS_RE);assert.ok(text.endsWith('\n'));assert.ok(lines.length>0);for(const l of lines)assert.match(l,/^file '\.\.\/b0\d\/edit\.mp4'$/);});
// #45: montaje por secuencia del storyboard. La instantánea de lote-a enlaza b01–b02 con sq-1 y b03 con sq-2; b01 y b03 van en guía 3D
// y b02 no tiene nada (missing), así que no entra.
test('montar: un mp4 por secuencia del storyboard, unido sin recodificar, y sequences en cut.json',()=>{const d=H.cliData(),lote=path.join(d,H.CLI_PROJECT,'assets/lote-a'),mj=path.join(lote,'montaje');
 const rd=f=>JSON.parse(fs.readFileSync(path.join(lote,f),'utf8')),wr=(f,v)=>fs.writeFileSync(path.join(lote,f),JSON.stringify(v,null,1));
 const snap=rd('project-snapshot.json'),seq=snap.episodes[0].sequences[0],[p01]=seq.shots;seq.shots=[{...p01,storyboardShot:'v1'},{...p01,id:'p02',storyboardShot:'v3'}];
 snap.storyboards=[{id:'sb-a',title:'A',sequences:[{id:'sq-1',title:'Cruce',shots:[{id:'v1'},{id:'v2'}]},{id:'sq-2',title:'Pie',shots:[{id:'v3'}]}]}];wr('project-snapshot.json',snap);
 const plan=rd('plan.json');plan[2].parts=plan[2].parts.map(x=>({...x,shot:'p02'}));wr('plan.json',plan);
 const r=H.runCli(d,'scripts/bloques/montar.mjs',['lote-a']);assert.equal(r.status,0,r.stderr);
 const cut=rd('montaje/lote-a-cut-v00.cut.json');assert.deepEqual(cut.sequences.map(s=>[s.storyboard,s.sequence,s.file,s.at,s.blocks.map(b=>[b.block,b.at])]),[['sb-a','sq-1','lote-a-cut-v00.sq-1.mp4',0,[['b01',0]]],['sb-a','sq-2','lote-a-cut-v00.sq-2.mp4',9.5,[['b03',0]]]]);
 for(const s of cut.sequences){assert.ok(fs.existsSync(path.join(mj,s.file)),s.file);assert.equal(s.duration,9.5);}
 const concats=r.lines.map(l=>JSON.parse(l)).filter(e=>e.bin==='ffmpeg'&&e.argv.includes('concat'));assert.equal(concats.length,3);
 for(const e of concats)assert.deepEqual(e.argv.slice(e.argv.indexOf('-c'),e.argv.indexOf('-c')+2),['-c','copy']);
 assert.deepEqual(concats.slice(1).map(e=>path.basename(e.argv.at(-1))),['lote-a-cut-v00.sq-1.mp4','lote-a-cut-v00.sq-2.mp4']);
 assert.equal(fs.existsSync(path.join(mj,'concat.sec.txt')),false);assert.match(JSON.parse(r.lines.at(-1)).stdout,/secuencias: 2 \(/);
 const r2=H.runCli(d,'scripts/bloques/montar.mjs',['lote-a']);assert.equal(r2.status,0,r2.stderr);
 assert.deepEqual(fs.readdirSync(mj).filter(f=>f.endsWith('.cut.json')).sort(),['lote-a-cut-v00.cut.json','lote-a-cut-v01.cut.json']);assert.ok(fs.existsSync(path.join(mj,'lote-a-cut-v01.sq-2.mp4')));});
test('montar: lote sin storyboard deja sequences vacío y ningún mp4 más',()=>{const d=H.cliData(),mj=path.join(d,H.CLI_PROJECT,'assets/lote-a/montaje'),r=H.runCli(d,'scripts/bloques/montar.mjs',['lote-a']);assert.equal(r.status,0,r.stderr);
 assert.deepEqual(JSON.parse(fs.readFileSync(path.join(mj,'lote-a-cut-v00.cut.json'),'utf8')).sequences,[]);assert.deepEqual(fs.readdirSync(mj).sort(),['concat.txt','lote-a-cut-v00.cut.json','lote-a-cut-v00.mp4']);});
