import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {rehearsalConfig,rehearsalStageErrors,exteriorPartAt,stageFallback,speechLocale} from '../app/workflow.mjs';
const drum={shape:'cylinder',radius:2.2,height:1.8,segments:32,color:'#c4bfa7',position:[0,2,0],rotation:[0,0,Math.PI/2],drift:[.08,0,0],spin:[.06,0,0]};
const project=()=>({language:'en',stage:{rehearsal:{animations:{library:'assets/lib',clips:{idle:'breathe',talk:'talk',walk:'walk'}},voicePitch:{pa:1.12},exteriors:{depart:{background:'#03070d',parts:[drum,{shape:'box',size:[1,1,1],color:'#89918e',position:[4,2,-4]}]}}}}});
const shot=(extra={})=>({id:'p1',rehearsal:true,staging:{exterior:'depart'},...extra});

test('rehearsalConfig: sin stage no hay animaciones ni exterior y el tono queda vacío',()=>{const r=rehearsalConfig({language:'es'},shot());assert.deepEqual(r,{animations:null,exterior:null,exteriorKey:null,voicePitch:{},speech:{base:'es',locale:'es-ES'}});assert.deepEqual(rehearsalConfig(null).animations,null);});
test('rehearsalConfig: rutas por rol y solo en planos de ensayo',()=>{const p=project();assert.deepEqual(rehearsalConfig(p,shot()).animations,{files:{idle:'assets/lib/breathe.fbx',talk:'assets/lib/talk.fbx',walk:'assets/lib/walk.fbx'}});assert.equal(rehearsalConfig(p,shot({rehearsal:false})).animations,null);assert.ok(rehearsalConfig(p).animations);delete p.stage.rehearsal.animations.clips.walk;assert.equal(rehearsalConfig(p,shot()).animations,null);p.stage.rehearsal.animations='x';assert.equal(rehearsalConfig(p,shot()).animations,null);});
test('rehearsalConfig: exterior por staging.exterior; clave desconocida o plano sin ensayo → null',()=>{const p=project(),before=structuredClone(p);const r=rehearsalConfig(p,shot());assert.equal(r.exteriorKey,'depart');assert.equal(r.exterior.background,'#03070d');assert.equal(r.exterior.parts.length,2);assert.equal(rehearsalConfig(p,shot({staging:{exterior:'otro'}})).exterior,null);assert.equal(rehearsalConfig(p,shot({staging:{}})).exteriorKey,null);assert.equal(rehearsalConfig(p,shot({rehearsal:false})).exterior,null);assert.equal(rehearsalConfig(p,shot({staging:{exterior:'toString'}})).exterior,null);assert.deepEqual(r.voicePitch,{pa:1.12});r.voicePitch.pa=2;assert.deepEqual(p,before);});
test('rehearsalStageErrors: acepta la configuración válida y señala cada campo mal formado',()=>{assert.deepEqual(rehearsalStageErrors(project().stage.rehearsal),[]);assert.deepEqual(rehearsalStageErrors(undefined),[]);assert.deepEqual(rehearsalStageErrors('x'),['stage.rehearsal debe ser un objeto']);
 const bad={animations:{library:3,clips:{idle:'a',talk:''}},voicePitch:{pa:3,ed:'1'},exteriors:{e:{background:'red',parts:[{shape:'cone',color:'#fff',position:[0,0]},{shape:'box',size:[1,1],color:'#000000',position:[0,0,0],drift:[1,'0',0]},{shape:'cylinder',radius:0,color:'#000000',position:[0,0,0]},{shape:'sphere',color:'#000000',position:[0,0,0],spin:[0,0,0,0]}]}}};
 const e=rehearsalStageErrors(bad);for(const f of ['animations.library','animations.clips.talk','animations.clips.walk','voicePitch.pa','voicePitch.ed','exteriors.e.background','parts[0].shape','parts[0].color','parts[0].position','parts[1].size','parts[1].drift','parts[2].radius','parts[2].height','parts[3].radius','parts[3].spin'])assert.ok(e.some(x=>x.includes(f)),f);assert.ok(!e.some(x=>x.includes('clips.idle')));});
test('exteriorPartAt reproduce la deriva y el giro del ensayo de hoy bit a bit',()=>{for(const elapsed of [0,1.7,5.1,13.13]){const q=exteriorPartAt(drum,elapsed);assert.equal(q.position[0],0+elapsed*.08);assert.equal(q.position[1],2);assert.equal(q.rotation[0],elapsed*.06);assert.equal(q.rotation[1],0);assert.equal(q.rotation[2],Math.PI/2);const left=exteriorPartAt({...drum,position:[-5,2,0],spin:undefined},elapsed);assert.equal(left.position[0],-5+elapsed*.08);assert.equal(left.rotation,null);}assert.deepEqual(exteriorPartAt({position:[4,2,-4]},9),{position:[4,2,-4],rotation:null});});
test('stageFallback: la instantánea con stage manda; sin él se completa con el vivo sin mutar',()=>{const snap={id:'x',stage:{rehearsal:{a:1}}},live={stage:{rehearsal:{b:2}}};assert.equal(stageFallback(snap,live),snap);const old={id:'x'},r=stageFallback(old,live);assert.deepEqual(r,{id:'x',stage:live.stage});assert.deepEqual(old,{id:'x'});assert.equal(stageFallback(old,null).stage,undefined);});
test('speechLocale: base y locale a partir del idioma del proyecto',()=>{assert.deepEqual(speechLocale('en'),{base:'en',locale:'en-US'});assert.deepEqual(speechLocale('es'),{base:'es',locale:'es-ES'});assert.deepEqual(speechLocale('en-GB'),{base:'en',locale:'en-GB'});assert.deepEqual(speechLocale(''),{base:'en',locale:'en-US'});assert.deepEqual(speechLocale(undefined),{base:'en',locale:'en-US'});});
test('stage.js y rehearsal.source.js no llevan datos de un proyecto concreto',()=>{for(const f of ['app/stage.js','app/rehearsal.source.js']){const src=fs.readFileSync(new URL('../'+f,import.meta.url),'utf8');for(const bad of ["'dead-air'",'mixamo-library','sourceScene===','[5,12]','/15',"'en-US'","'earl'"])assert.ok(!src.includes(bad),`${f} contiene ${bad}`);}assert.ok(fs.readFileSync(new URL('../app/stage.js',import.meta.url),'utf8').includes('group.add(label);'));});
