import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
process.env.RODAJE_DATA=fs.mkdtempSync(path.join(os.tmpdir(),'rodaje-test-'));const m=await import('../app/store.mjs');
function fixture(){const p=m.create('Nueva película','pelicula');p.characters.push({id:'person',name:'Ada',description:'Piloto',image:'assets/a.png',voice:'voice-1'});p.locations.push({id:'set',name:'Hangar',kind:'interior'});p.episodes.push({id:'ep',title:'Acto 1',sequences:[{id:'seq',location:'set',silent:true,cast:[{character:'person',x:0,z:0,yaw:0}],shots:[m.newShot('Plano')]}]});return m.save(p);}
function approve(p){const t=p.episodes[0].sequences[0].shots[0];t.preview={job:'render',hash:m.digest(p,t.id)};t.approval={hash:t.preview.hash,preview:'render'};return t;}
test('approval invalidates on camera, voice, ambience and props changes',()=>{for(const edit of [p=>p.characters[0].voice='voice2',p=>p.episodes[0].sequences[0].shots[0].camera.position[0]=10,p=>p.episodes[0].sequences[0].ambience='assets/sound.wav',p=>p.episodes[0].sequences[0].props=[{type:'box',x:3}]]){const p=fixture(),t=approve(p);assert(m.approved(p,t.id));edit(p);assert.equal(m.approved(p,t.id),false);}});
test('project title does not invalidate production and wrong preview cannot approve',()=>{const p=fixture(),t=approve(p);p.name='Nuevo título';assert(m.approved(p,t.id));t.approval.preview='other';assert.equal(m.approved(p,t.id),false);});
test('stale saves fail and prior versions survive',()=>{const p=fixture(),old=structuredClone(p);m.save(p,p.revision);assert.throws(()=>m.save(old,old.revision),/cambió/);assert(fs.readdirSync(path.join(m.dir(p.id),'versiones')).length>=3);});
test('reject traversal and symlink escape',()=>{assert.throws(()=>m.safe(m.DATA,'../config.local.json'));const outside=fs.mkdtempSync(path.join(os.tmpdir(),'rodaje-outside-'));fs.symlinkSync(outside,path.join(m.DATA,'link'));assert.throws(()=>m.safe(m.DATA,'link/key.txt'));});
test('invalid dialogue and duration rejected',()=>{const p=fixture(),t=p.episodes[0].sequences[0].shots[0];t.duration=0;assert.throws(()=>m.save(p),/dur(ar|ación)/);t.duration=5;t.lines=[{character:'missing',start:1,text:'Hello'}];assert.throws(()=>m.save(p),/hablante/);});
test('export requires current approved render and final',()=>{const p=fixture(),t=approve(p);assert.throws(()=>m.exportReady(p,'ep'),/Falta vídeo/);t.final={hash:m.digest(p,t.id),file:'out.mp4'};assert.equal(m.exportReady(p,'ep').length,1);t.description='Different action';assert.throws(()=>m.exportReady(p,'ep'),/Falta vídeo/);});
