import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
process.env.RODAJE_DATA=fs.mkdtempSync(path.join(os.tmpdir(),'rodaje-test-'));const m=await import('../app/store.mjs');
function fixture(){const p=m.create('Nueva película','pelicula');p.characters.push({id:'person',name:'Ada',description:'Piloto',image:'assets/a.png',voice:'voice-1'});p.locations.push({id:'set',name:'Hangar',kind:'interior'});p.episodes.push({id:'ep',title:'Acto 1',sequences:[{id:'seq',location:'set',silent:true,cast:[{character:'person',x:0,z:0,yaw:0}],shots:[m.newShot('Plano')]}]});return m.save(p);}
function approve(p){const t=p.episodes[0].sequences[0].shots[0];t.preview={job:'render',hash:m.digest(p,t.id)};t.approval={hash:t.preview.hash,preview:'render'};return t;}
test('approval invalidates on camera, voice, ambience and props changes',()=>{for(const edit of [p=>p.characters[0].voice='voice2',p=>p.episodes[0].sequences[0].shots[0].camera.position[0]=10,p=>p.episodes[0].sequences[0].ambience='assets/sound.wav',p=>p.episodes[0].sequences[0].props=[{type:'box',x:3}],p=>p.episodes[0].sequences[0].environment={spot:'sala'}]){const p=fixture(),t=approve(p);assert(m.approved(p,t.id));edit(p);assert.equal(m.approved(p,t.id),false);}});
test('project title does not invalidate production and wrong preview cannot approve',()=>{const p=fixture(),t=approve(p);p.name='Nuevo título';assert(m.approved(p,t.id));t.approval.preview='other';assert.equal(m.approved(p,t.id),false);});
test('stale saves fail and prior versions survive',()=>{const p=fixture(),old=structuredClone(p);m.save(p,p.revision);assert.throws(()=>m.save(old,old.revision),/cambió/);assert(fs.readdirSync(path.join(m.dir(p.id),'versiones')).length>=3);});
test('reject traversal and symlink escape',()=>{assert.throws(()=>m.safe(m.DATA,'../config.local.json'));const outside=fs.mkdtempSync(path.join(os.tmpdir(),'rodaje-outside-'));fs.symlinkSync(outside,path.join(m.DATA,'link'));assert.throws(()=>m.safe(m.DATA,'link/key.txt'));});
test('invalid dialogue and duration rejected',()=>{const p=fixture(),t=p.episodes[0].sequences[0].shots[0];t.duration=0;assert.throws(()=>m.save(p),/dur(ar|ación)/);t.duration=5;t.lines=[{character:'missing',start:1,text:'Hello'}];assert.throws(()=>m.save(p),/hablante/);});
test('export requires current approved render and final',()=>{const p=fixture(),t=approve(p);assert.throws(()=>m.exportReady(p,'ep'),/Falta vídeo/);t.final={hash:m.digest(p,t.id),file:'out.mp4'};assert.equal(m.exportReady(p,'ep').length,1);t.description='Different action';assert.throws(()=>m.exportReady(p,'ep'),/Falta vídeo/);});
const wf=await import('../app/workflow.mjs');
test('outline numbers sequences across episodes with running minutes and finds them by id',()=>{const p=fixture();p.episodes[0].sequences.push({id:'seq2',title:'Dos',minutes:4,cast:[],shots:[]});p.episodes.push({id:'ep2',title:'Acto 2',sequences:[{id:'seq3',title:'Tres',minutes:'6',cast:[],shots:[]}]});const rows=wf.outline(p);assert.deepEqual(rows.map(r=>[r.code,r.minutes,r.start,r.episode.id]),[['01',0,0,'ep'],['02',4,0,'ep'],['03',6,4,'ep2']]);assert.equal(wf.outlineSequence(p,'seq3').episode.id,'ep2');assert.throws(()=>wf.outlineSequence(p,'nope'),/no encontrada/);});
test('cover prompt uses the explicit prompt verbatim or composes style, title and outline text',()=>{const p=fixture();p.style='Muted medieval realism.';const s=p.episodes[0].sequences[0];s.title='El fuego';s.text='Brasas. Gilbert cuenta.';const text=wf.coverPrompt(p,p.episodes[0],s);assert.match(text,/^Muted medieval realism\./);assert.match(text,/"El fuego" \(Acto 1\): Brasas\. Gilbert cuenta\./);assert.match(text,/16:9 film still/);s.coverPrompt='  Exact cover.  ';assert.equal(wf.coverPrompt(p,p.episodes[0],s),'Exact cover.');});


test('issues: parseIssues reads open and closed points with severity from headings',()=>{const md='# Análisis\n\n## Abierto\n\n### Graves: rompen la causalidad\n\n**A2. El punto medio no tiene giro.** Primera línea.\nSegunda línea.\n\n### Ritmo\n\n**A21. Tres tramos planos.**\n\n| Tramo | Min |\n|---|---|\n| I | 26 |\n\n## Cerrado\n\n- **C1. El pleito se pierde por poder, no por Gilbert.** Decidido.\n';const items=wf.parseIssues(md);assert.deepEqual(items.map(i=>[i.code,i.title,i.status,i.severity]),[['A2','El punto medio no tiene giro','abierto','grave'],['A21','Tres tramos planos','abierto','ritmo'],['C1','El pleito se pierde por poder, no por Gilbert','cerrado','nota']]);assert.equal(items[0].text,'Primera línea.\nSegunda línea.');assert.match(items[1].text,/^\| Tramo/);assert.equal(items[2].text,'Decidido.');});
test('issues: upsertIssues adds by code, updates text and only closes from the document',()=>{const p={issues:[]};let n=0;const opts={newId:()=>'i'+(++n),now:()=>'T'};assert.deepEqual(wf.upsertIssues(p,[{code:'A2',title:'Uno',text:'x',severity:'grave',status:'abierto'},{code:'C1',title:'Dos',text:'y',status:'cerrado'}],opts),{added:2,updated:0});assert.equal(p.issues[1].closed,'T');p.issues[0].status='en-curso';assert.deepEqual(wf.upsertIssues(p,[{code:'A2',title:'Uno bis',text:'z',severity:'medio',status:'abierto'}],opts),{added:0,updated:1});assert.deepEqual([p.issues[0].title,p.issues[0].text,p.issues[0].severity,p.issues[0].status],['Uno bis','z','medio','en-curso']);wf.upsertIssues(p,[{code:'A2',title:'Uno',text:'z',status:'cerrado'}],opts);assert.equal(p.issues[0].status,'cerrado');assert.equal(p.issues.length,2);});
test('issues: board groups by state and moveIssue reorders within and across columns',()=>{const p={issues:[{id:'a',title:'A',status:'abierto'},{id:'b',title:'B',status:'abierto'},{id:'c',title:'C',status:'cerrado',closed:'X'}]};assert.deepEqual(wf.issueBoard(p).map(c=>[c.key,c.items.map(i=>i.id)]),[['abierto',['a','b']],['en-curso',[]],['cerrado',['c']]]);assert.equal(wf.moveIssue(p,'a','abierto','a'),false);assert(wf.moveIssue(p,'a','abierto','b')===true);assert.deepEqual(p.issues.map(i=>i.id),['a','b','c']);assert(wf.moveIssue(p,'b','abierto','a'));assert.deepEqual(p.issues.map(i=>i.id),['b','a','c']);assert(wf.moveIssue(p,'c','abierto',undefined,()=>'N'));assert.deepEqual(p.issues.map(i=>i.id),['b','a','c']);assert.equal(p.issues[2].closed,undefined);assert(wf.moveIssue(p,'b','cerrado',undefined,()=>'N'));assert.deepEqual(p.issues.map(i=>[i.id,i.status]),[['a','abierto'],['c','abierto'],['b','cerrado']]);assert.equal(p.issues[2].closed,'N');assert.throws(()=>wf.moveIssue(p,'zz','abierto'),/no encontrado/);assert.throws(()=>wf.moveIssue(p,'a','nada'),/Estado/);});
test('issues: store validates issues and create starts with an empty board',()=>{const p=m.create('Con pendientes','pelicula');assert.deepEqual(p.issues,[]);p.issues.push({id:'i1',title:'Uno',status:'abierto'});m.save(p);p.issues.push({id:'i2',title:'',status:'abierto'});assert.throws(()=>m.save(p),/título/);p.issues[1]={id:'i1',title:'Dup',status:'abierto'};assert.throws(()=>m.save(p),/duplicado/);p.issues[1]={id:'i2',title:'Dos',status:'raro'};assert.throws(()=>m.save(p),/Estado de pendiente/);});
test('environmentViewer: viewer texto (legado), constructor, GLB o nada',()=>{
 assert.deepEqual(wf.environmentViewer({viewer:'a/explore.js',builder:'b.js',data:'m.json',glb:'c.glb'}),{kind:'legacy',module:'a/explore.js'});
 assert.deepEqual(wf.environmentViewer({viewer:{plugins:['v.js']},builder:'b.js',data:'m.json',glb:'c.glb'}),{kind:'mount'});
 assert.deepEqual(wf.environmentViewer({builder:'b.js',data:'m.json'}),{kind:'mount'});
 assert.deepEqual(wf.environmentViewer({viewer:'',builder:'b.js',glb:'c.glb'}),{kind:'glb',url:'c.glb'});
 assert.deepEqual(wf.environmentViewer({data:'m.json'}),{kind:'none'});assert.deepEqual(wf.environmentViewer(undefined),{kind:'none'});
 const l=wf.environmentList({environments:[{id:'g',builder:'b.js',data:'m.json',viewer:{plugins:['v.js']},glb:'c.glb'}]});assert.equal(l[0].kind,'constructor');assert.equal(l[0].viewer,'');});
test('hasPlantaEditor y plantaEditorUrl: editor de plantas para entornos con constructor y datos',()=>{assert.equal(wf.hasPlantaEditor({builder:'a.js',data:'m.json'}),true);for(const e of [{builder:'a.js'},{data:'m.json'},{glb:'x.glb'},null,undefined])assert.equal(wf.hasPlantaEditor(e),false);
 assert.equal(wf.plantaEditorUrl('conj','caseron'),'/viewer/planta.html?project=conj&env=caseron');assert.equal(wf.plantaEditorUrl('a b','x&y=z'),'/viewer/planta.html?project=a%20b&env=x%26y%3Dz');});
test('environmentList lists project environments and the ship model',()=>{const p={environments:[{id:'caseron',name:'Caserón',viewer:'a/explore.js',glb:'a/c.glb'},{id:'solo',glb:'b.glb'},{id:'nada'}],shipModel:{name:'Toledo',viewer:'x.js',snapshots:[{file:'s.png'}]}};const l=wf.environmentList(p);assert.deepEqual(l.map(e=>[e.id,e.kind,e.action]),[['caseron','visor','env-open:caseron'],['solo','glb','env-open:solo'],['nada','vacío','env-open:nada'],['ship','visor','nav:ship']]);assert.equal(l[1].name,'solo');assert.equal(l[3].image,'s.png');assert.deepEqual(wf.environmentList({}),[]);});
test('locationEnvironment and environmentChoice',()=>{const p={locations:[{id:'c',environment:'caseron'},{id:'b'}],environments:[{id:'caseron'}]};assert.equal(wf.locationEnvironment(p,'c').id,'caseron');assert.equal(wf.locationEnvironment(p,'b'),null);assert.equal(wf.locationEnvironment(p,'x'),null);assert.deepEqual(wf.environmentChoice({envSpot:'sala',envPreset:'a3-22-agua',envRotation:'-90'}),{spot:'sala',preset:'a3-22-agua',rotation:270});assert.equal(wf.environmentChoice({envSpot:'',envPreset:'',envRotation:''}),undefined);});
test('sortKeys ordena las claves en todos los niveles y conserva el orden de los arrays',()=>{const input={b:1,a:{d:[{z:1,y:2},3],c:null}};const out=wf.sortKeys(input);assert.equal(JSON.stringify(out),'{"a":{"c":null,"d":[{"y":2,"z":1},3]},"b":1}');assert.equal(JSON.stringify(input),'{"b":1,"a":{"d":[{"z":1,"y":2},3],"c":null}}');assert.equal(wf.sortKeys('x'),'x');assert.equal(wf.sortKeys(0),0);assert.deepEqual(wf.sortKeys([2,1]),[2,1]);});
