#!/usr/bin/env node
// Informe del lote (PROCESO.md, paso 7): intentos, aceptación, reglas más violadas, segundos y coste.
//   node scripts/bloques/informe.mjs <lote> [--project dead-air]
// Falla si un intento rechazado no cita reglas o si un reintento no declara su línea cambiada (R26).
import fs from 'node:fs';import path from 'node:path';
import {parseArgs,loadLote,loadAttempts,prices} from './lib.mjs';
const {args:[lote],opts}=parseArgs(process.argv.slice(2));if(!lote){console.error('Uso: informe.mjs <lote>');process.exit(2);}
const L=loadLote(opts.project||'dead-air',lote);const price=prices();const rate=e=>price[e]?.price||0;
const rows=[],rules={},errors=[];let attempts=0,accepted=0,first=0,seconds=0,cost=0,inference=0;
for(const b of L.plan){const list=loadAttempts(L.paths.out,b.id);attempts+=list.length;const ok=list.find(a=>a.verdict==='accepted');if(ok){accepted++;if(ok.n===1)first++;}
 for(const a of list){seconds+=a.durationRequested||0;cost+=(a.durationRequested||0)*rate(a.endpoint||'minimax/h3-max/reference-to-video');inference+=a.inferenceSeconds||0;for(const r of a.failedRules||[])rules[r]=(rules[r]||0)+1;
  if(a.verdict==='rejected'&&!(a.failedRules||[]).length)errors.push(`${b.id} intento ${a.n}: rechazado sin regla`);if(a.n>=2&&!a.changedLine)errors.push(`${b.id} intento ${a.n}: sin changedLine (R26)`);if(a.n>6)errors.push(`${b.id}: más de 6 intentos (R26)`);}
 rows.push(`| ${b.id} | ${b.length.toFixed(1)} | ${list.length} | ${ok?'✓ v'+ok.n:list.length?'—':'sin enviar'} | ${list.flatMap(a=>a.failedRules||[]).join(', ')} | ${list.map(a=>a.changedLine?`v${a.n}: ${a.changedLine.slice(0,70)}`:'').filter(Boolean).join('<br>')} |`);}
const md=`# Informe del lote ${lote}\n\nGenerado ${new Date().toISOString().slice(0,16)} por \`scripts/bloques/informe.mjs\`. Episodio \`${L.meta.episode}\`, secuencia \`${L.meta.sequence}\`.\n\n| Bloques | Intentos | Aceptados | Al primer intento | Segundos pedidos | Inferencia | Coste estimado |\n|---|---|---|---|---|---|---|\n| ${L.plan.length} | ${attempts} | ${accepted} | ${first} | ${seconds} | ${Math.round(inference)} s | ${cost.toFixed(2)} $ |\n\nAceptación al primer intento: ${L.plan.length?Math.round(first/L.plan.length*100):0} % · intentos por bloque aceptado: ${accepted?(attempts/accepted).toFixed(2):'—'}.\n\n## Reglas más violadas\n\n${Object.entries(rules).sort((a,b)=>b[1]-a[1]).map(([r,n])=>`- ${r}: ${n}`).join('\n')||'- (ninguna registrada)'}\n\n## Bloques\n\n| Bloque | s | Intentos | Aceptado | Reglas incumplidas | Líneas cambiadas |\n|---|---|---|---|---|---|\n${rows.join('\n')}\n\n${errors.length?'## Protocolo roto\n\n'+errors.map(e=>'- '+e).join('\n')+'\n':''}Precio aplicado: ${rate('minimax/h3-max/reference-to-video')} $/s (\`precios.json\`, comprobado ${price['minimax/h3-max/reference-to-video']?.checked||'—'}).\n`;
fs.writeFileSync(path.join(L.paths.out,'INFORME.md'),md);console.log(`INFORME.md: ${attempts} intentos, ${accepted}/${L.plan.length} aceptados, ${cost.toFixed(2)} $`);if(errors.length){console.error(errors.join('\n'));process.exit(1);}
