// Vista Animación (#50): un plano con su cámara (t.cameraRig), reloj propio, diálogo con la voz del navegador y grabación de la cámara a 24 Hz.
// Libre tiene dos cámaras (#52): la órbita de OrbitControls y el vuelo con teclado y ratón (flyStep), que cada fotograma se aplica con stage.setCamera.
// «Renderizar vídeo» (#51): guarda si hay cambios y lanza el trabajo anim3d del plano (renderVideo); renderJob da su último trabajo para el progreso.
import {createStage} from './stage.js';
import {rehearsalConfig,projectChannels,cameraAt,cameraContext,cameraPresets,shotCast,CAMERA_RIG_TYPES,CAMERA_EASINGS,episodeSpeakers,ttsVoiceURI,ttsParams,TIMELINE_FPS,TRACK_SMOOTHING_DEFAULT,snapTime,clockTick,lineSchedule,lineToLaunch,activeLineAt,timelineMarks,recordSamples,trimTrack,recordedRig,rigFromShot,rigWithCamera,rigWithType,rigControls,stageSequence,shotRigIssues,anim3dReady,anim3dButton,flyKey,flyFromCamera,flyStep,flyCamera,flyPrefs,flySpeedStep} from './workflow.mjs';
import {loadVoicePrefs,saveVoicePrefs,speakLine} from './tts.source.js';
const CAM_PREFS='rodaje-anim-camera',TYPE_LABELS={fixed:'Fija',move:'Movimiento (inicio → fin)',follow:'Seguimiento de un personaje',track:'Pista grabada',handheld:'Cámara en mano'},EASING_LABELS={linear:'Lineal',smooth:'Suave','ease-in':'Arranque lento','ease-out':'Frenada lenta'};
export async function mountAnim(root,{getProject,ids,save,markDirty,toast,isDirty=()=>false,renderVideo=null,renderJob=()=>null}){
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const find=()=>{const p=getProject(),e=p?.episodes.find(e=>e.id===ids.episodeId),s=e?.sequences.find(s=>s.id===ids.sequenceId),t=s?.shots.find(t=>t.id===ids.shotId);return {p,e,s,t};};
 let {p,e,s,t}=find();if(!t)throw Error('Plano no encontrado');
 const R=rehearsalConfig(p,t),speech=R.speech,CH=projectChannels(p),synth=window.speechSynthesis,saved=loadVoicePrefs(p.id),speakerIds=episodeSpeakers(e),nameOf=id=>p.characters.find(c=>c.id===id)?.name||id;
 const cast=shotCast(t,s),positioned=[...new Set([...(s.cast||[]).map(a=>a.character),...Object.keys(t.staging?.proxies||{})])],followable=positioned.filter(id=>cast.includes(id));
 let ctx=cameraContext({shot:t,sequence:s,R}),draft=rigFromShot(t),rawTrack=draft.type==='track'?structuredClone(draft.track):null,stage=null,disposed=false;
 const prefs=(()=>{try{return flyPrefs(JSON.parse(localStorage.getItem(CAM_PREFS)));}catch{return flyPrefs(null);}})();
 let cam=prefs.mode,flySpeed=prefs.speed,fly=null,keys=new Set(),look=[0,0],drag=null;const touches=new Set();
 let time=0,playing=false,loop=false,mode='result',raf=0,last=0,launchFrom=0,voice=null,voices=[],speaker=null,recording=false,samples=[],countdown=null,renderTimer=0;
 const D=()=>t.duration,schedule=()=>lineSchedule(t.lines,D(),CH),lineOf=id=>t.lines.find(l=>l.id===id);
 root.innerHTML=`<div class="anim"><div class="anim-stage"><div class="stagebox"><div class="anim-view"><div data-viewport class="anim-viewport" tabindex="0" aria-label="Visor 3D: en Vuelo, WASD o flechas para moverse" style="aspect-ratio:16/9"></div><div data-countdown class="anim-countdown" hidden></div></div><div data-subtitle class="rehearsal-subtitle" aria-live="polite"></div><div class="stagefoot anim-transport"><button data-play aria-label="Reproducir">▶</button><button data-pause aria-label="Pausa">⏸</button><button data-stop aria-label="Parar">■</button><button data-loop aria-pressed="false" title="Repetir en bucle">⟳ Bucle</button><label class="anim-check"><input data-silent type="checkbox"> Solo subtítulos</label><output data-time>0,00 s</output></div></div>
 <div class="anim-timeline"><input data-scrub type="range" min="0" max="${D()}" step="${1/TIMELINE_FPS}" value="0" aria-label="Tiempo del plano"><div class="anim-marks" data-marks></div></div>
 <p data-status role="status" class="tiny"></p><details class="panel"><summary>Voces del navegador por personaje</summary><div class="grid" data-voices></div></details></div>
 <aside class="panel anim-side"><div class="row"><button data-mode="free" aria-pressed="false">Libre</button><button data-mode="result" aria-pressed="true">Ver resultado</button></div><div data-cambox hidden><div class="row"><button data-cam="orbit" aria-pressed="true">Órbita</button><button data-cam="fly" aria-pressed="false">Vuelo</button></div><label data-flyspeed>Velocidad de vuelo · <span data-out="fly"></span> m/s<input data-speed type="range" min="${Math.log2(.25)}" max="${Math.log2(20)}" step="0.01"></label></div><p class="tiny">Libre · Órbita: arrastra para orbitar y rueda (o pellizca) para acercar. Libre · Vuelo: clic en el visor; WASD o flechas, Q/E sube y baja, Mayús rápido, arrastra para mirar, rueda para la velocidad (en táctil, órbita). Ver resultado: la cámara del plano en cada instante.</p><div data-controls></div><div class="actions"><button data-render class="primary">Renderizar vídeo</button></div><p class="tiny">Renderizar vídeo: el plano guardado, con su cámara y las voces que tengan audio, a un vídeo de la viñeta con versión nueva (se ve en su tarjeta del storyboard).</p></aside></div>`;
 const $=q=>root.querySelector(q),status=x=>$('[data-status]').textContent=x;
 stage=await createStage($('[data-viewport]'),{project:p,sequence:stageSequence(s,t),shot:t});
 if(disposed){stage.dispose();return {dispose(){}};}
 // Voz del navegador: mismas preferencias y voces por defecto que el Ensayo.
 const lineSpeakers=[...new Set(t.lines.map(l=>l.character))];
 function refreshVoices(){voices=synth?.getVoices()||[];$('[data-voices]').innerHTML=lineSpeakers.map(id=>{const sel=ttsVoiceURI({voices,speakerIds,id,saved,base:speech.base});return `<label>${esc(nameOf(id))}<select data-person="${esc(id)}"><option value="">Voz predeterminada</option>${voices.map(v=>`<option value="${esc(v.voiceURI)}" ${sel===v.voiceURI?'selected':''}>${esc(v.name)} · ${esc(v.lang)}</option>`).join('')}</select></label>`;}).join('')||'<p class="tiny">Este plano no tiene diálogo.</p>';root.querySelectorAll('[data-person]').forEach(el=>el.onchange=()=>{saved[el.dataset.person]=el.value;saveVoicePrefs(p.id,saved);});if(!playing)status(!synth?'Este navegador no dispone de síntesis de voz: usa Solo subtítulos.':!voices.length?'Esperando voces del navegador. Si no aparecen, activa Solo subtítulos.':'Voces del navegador listas. No se generan archivos de audio.');}
 refreshVoices();synth?.addEventListener('voiceschanged',refreshVoices);
 const setSpeaker=l=>{if(speaker===l)return;speaker=l;stage.setSpeaker(l);};
 function hush(){voice?.cancel();voice=null;synth?.cancel();speaker=undefined;setSpeaker(null);}
 function launch(item){const l=lineOf(item.id);if(!l||$('[data-silent]').checked||!synth)return;voice?.cancel();const q=ttsParams(l,{speech,voicePitch:R.voicePitch,voiceURI:ttsVoiceURI({voices,speakerIds,id:l.character,saved,base:speech.base})});
  const mine=voice=speakLine(synth,q,voices,{onstart:()=>{if(voice===mine)setSpeaker(l);},onend:err=>{if(voice!==mine)return;voice=null;setSpeaker(null);if(err)status(err.message);}});}
 // Pinta el instante actual: actores, cámara (si se ve el resultado), subtítulo, gesto de hablar en modo silencioso y scrub.
 function update(){stage.pose(time,false);if(mode==='result')stage.setCamera(cameraAt(draft,time,D(),ctx));const a=activeLineAt(schedule(),time);$('[data-subtitle]').textContent=a?`${nameOf(a.character)}${a.offscreen?' · FUERA DE CAMPO':''}\n${a.text}`:(t.lines.length?'':'ACCIÓN · '+(t.description||''));
  if(playing&&$('[data-silent]').checked)setSpeaker(a?lineOf(a.id)||null:null);$('[data-scrub]').value=time;$('[data-time]').textContent=`${time.toFixed(2).replace('.',',')} s · ${Math.round(time*TIMELINE_FPS)}/${Math.round(D()*TIMELINE_FPS)}`;}
 // Vuelo: un paso por fotograma con el dt real (flyStep lo recorta), antes del reloj para que la grabación tome la cámara ya movida.
 function frame(now){raf=requestAnimationFrame(frame);const rawDt=(now-last)/1000,dt=Math.min(1,rawDt);last=now;
  if(!disposed&&flying()&&fly){fly=flyStep(fly,{keys,look,speed:flySpeed},rawDt);look=[0,0];stage.setCamera(flyCamera(fly,stage.camera().fov));}
  if(!playing||disposed)return;const r=clockTick({time,duration:D(),loop:loop&&!recording},dt);if(r.wrapped)hush();const from=r.wrapped?-1e-6:launchFrom;time=r.time;launchFrom=time;
  const l=lineToLaunch(schedule(),from,time);if(l)launch(l);update();if(recording)samples=recordSamples(samples,time,stage.camera(),{duration:D()});if(r.ended){playing=false;if(recording)finishRecording();else hush();}}
 function play(){if(playing||countdown)return;if(time>=D()-1e-9)time=0;playing=true;launchFrom=time-1e-6;last=performance.now();}
 function pause(){playing=false;hush();}
 function stopAll(){if(recording||countdown)return abortRecording('Grabación cancelada. La cámara anterior se conserva.');pause();time=0;update();}
 function setMode(m){const was=mode;mode=m;if(m!=='free')releaseKeys();else if(was!=='free'&&cam==='fly')fly=flyFromCamera(stage.camera());stage.orbit(m==='free'&&cam==='orbit');root.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===m)));camUI();update();}
 // Órbita/Vuelo dentro de Libre: el cambio no mueve la cámara; al volver a la órbita, su centro es el punto al que se mira.
 const flying=()=>mode==='free'&&cam==='fly'&&!touches.size,savePrefs=()=>{try{localStorage.setItem(CAM_PREFS,JSON.stringify({mode:cam,speed:flySpeed}));}catch{}};
 function releaseKeys(){keys.clear();look=[0,0];if(fly)fly={...fly,velocity:[0,0,0]};}
 function setCam(c){releaseKeys();if(mode==='free'&&c==='fly'&&cam!=='fly'){fly=flyFromCamera(stage.camera());stage.orbit(false);}else if(mode==='free'&&c==='orbit'&&cam==='fly'){if(fly)stage.setCamera(flyCamera(fly,stage.camera().fov));stage.orbit(true);}cam=c;savePrefs();camUI();}
 function setSpeed(v){flySpeed=flySpeedStep(v,0);savePrefs();camUI();}
 function camUI(){$('[data-cambox]').hidden=mode!=='free';root.querySelectorAll('[data-cam]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.cam===cam)));$('[data-flyspeed]').hidden=cam!=='fly';$('[data-out="fly"]').textContent=flySpeed.toFixed(2).replace('.',',');$('[data-speed]').value=Math.log2(flySpeed);}
 // Cada edición confirmada escribe el borrador en el plano y marca el proyecto como modificado (sin guardar).
 function commit(rig){draft=rig;t.cameraRig=structuredClone(draft);markDirty();controls();update();}
 function issues(){return shotRigIssues(s,{...t,cameraRig:draft});}
 // Grabación: cuenta atrás de 3 s, modo libre, reloj desde 0 con la voz y una muestra de stage.camera() por fotograma de 1/24 s.
 function record(){if(recording||countdown)return;pause();let n=3;const box=$('[data-countdown]');box.hidden=false;$('.anim-view').scrollIntoView?.({block:'nearest'});box.textContent=n;countdown=setInterval(()=>{n--;if(n>0){box.textContent=n;return;}clearInterval(countdown);countdown=null;box.hidden=true;setMode('free');time=0;samples=recordSamples([],0,stage.camera(),{duration:D()});recording=true;transport();play();},1000);transport();}
 function finishRecording(){recording=false;releaseKeys();hush();rawTrack=samples;samples=[];commit(recordedRig(rawTrack,{smoothing:TRACK_SMOOTHING_DEFAULT}));setMode('result');transport();status(`Grabadas ${rawTrack.length} muestras. Ajusta el suavizado o recorta y guarda.`);}
 function abortRecording(msg){releaseKeys();if(countdown){clearInterval(countdown);countdown=null;$('[data-countdown]').hidden=true;}recording=false;samples=[];pause();time=0;transport();update();status(msg);}
 const onVisibility=()=>{if(document.hidden)releaseKeys();if(document.hidden&&(recording||countdown))abortRecording('Grabación cancelada: la pestaña quedó oculta. La cámara anterior se conserva.');else if(document.hidden&&playing)pause();};
 document.addEventListener('visibilitychange',onVisibility);
 function transport(){const busy=recording||!!countdown;$('[data-scrub]').disabled=busy;$('[data-loop]').disabled=busy;$('[data-loop]').setAttribute('aria-pressed',String(loop));root.querySelectorAll('[data-mode]').forEach(el=>el.disabled=busy);root.querySelectorAll('[data-controls] button,[data-controls] select,[data-controls] input').forEach(el=>{if(busy)el.disabled=true;});if(!busy)controls();}
 // Panel de la cámara según el tipo del borrador (rigControls).
 function controls(){const c=rigControls(draft.type),iss=issues(),box=$('[data-controls]'),num=(v,d=2)=>Number(v).toFixed(d),hold=Array.isArray(draft.hold)?draft.hold:[0,1];
  const presets=cameraPresets(stage.camera(),{characters:followable.map(id=>({id,name:nameOf(id)}))});
  box.innerHTML=`<div class="row"><button data-set="start" ${draft.type==='track'?'disabled':''}>Fijar inicio</button><button data-set="end" ${['fixed','move','handheld'].includes(draft.type)?'':'disabled'}>Fijar fin</button></div>
  <label>Tipo de cámara<select data-type>${CAMERA_RIG_TYPES.map(k=>`<option value="${k}" ${k===draft.type?'selected':''}>${TYPE_LABELS[k]}</option>`).join('')}</select></label>
  <label>Partir de un tipo de grabación (desde la cámara actual)<select data-preset><option value="">Elige…</option>${presets.map(x=>`<option value="${esc(x.id)}">${esc(x.label)}</option>`).join('')}</select></label>
  ${c.easing?`<label>Curva<select data-easing>${CAMERA_EASINGS.map(k=>`<option value="${k}" ${k===(draft.easing||'smooth')?'selected':''}>${EASING_LABELS[k]}</option>`).join('')}</select></label>`:''}
  ${c.hold?`<div class="two anim-two"><label>Empieza a moverse (fracción)<input data-hold="0" type="number" min="0" max="1" step="0.05" value="${hold[0]}"></label><label>Termina (fracción)<input data-hold="1" type="number" min="0" max="1" step="0.05" value="${hold[1]}"></label></div>`:''}
  ${c.follow?`<label>Personaje<select data-follow="character">${followable.map(id=>`<option value="${esc(id)}" ${id===draft.follow?.character?'selected':''}>${esc(nameOf(id))}</option>`).join('')}</select></label><label>Modo<select data-follow="mode">${[['look','Panorámica (la cámara no se desplaza)'],['track','Acompañar (se desplaza con él)']].map(([k,l])=>`<option value="${k}" ${k===(draft.follow?.mode||'look')?'selected':''}>${l}</option>`).join('')}</select></label><label>Suavizado del seguimiento · <span data-out="fs">${num(draft.follow?.smoothing??.5)}</span><input data-follow="smoothing" type="range" min="0" max="1" step="0.05" value="${draft.follow?.smoothing??.5}"></label>`:''}
  ${c.shake?`<label>Temblor · <span data-out="shake">${num(draft.shake??.03)}</span> m<input data-shake type="range" min="0" max="0.5" step="0.01" value="${draft.shake??.03}"></label>`:''}
  ${c.trackSmoothing?`<label>Suavizado · <span data-out="ts">${num(draft.trackSmoothing??0)}</span><input data-smoothing type="range" min="0" max="1" step="0.05" value="${draft.trackSmoothing??0}"></label>`:''}
  ${c.trim&&rawTrack?.length>1?`<div class="two anim-two"><label>Recortar desde · s<input data-trim="from" type="number" min="0" max="${D()}" step="${1/TIMELINE_FPS}" value="${num(draft.track[0].t,3)}"></label><label>hasta · s<input data-trim="to" type="number" min="0" max="${D()}" step="${1/TIMELINE_FPS}" value="${num(draft.track.at(-1).t,3)}"></label></div><button data-trim-apply>Aplicar recorte</button><p class="tiny">El recorte parte de la última grabación (${rawTrack.length} muestras); fuera del tramo la cámara queda quieta.</p>`:''}
  <div class="actions"><button data-record class="lime">${draft.type==='track'&&rawTrack?.length>1?'● Regrabar':'● Grabar'}</button><button data-save class="primary" ${iss.errors.length?'disabled':''}>Guardar</button></div>
  ${iss.errors.length?`<p class="error">${iss.errors.map(esc).join('\n')}</p>`:''}${iss.warnings.length?`<p class="tiny">${iss.warnings.map(esc).join('<br>')}</p>`:''}<p class="tiny">Grabar: cuenta atrás de 3 s y el plano suena desde 0; mueve la cámara con el ratón o el dedo, o volando con el teclado (Libre · Vuelo), hasta el final. Guardar crea una versión del proyecto y cambia la huella del plano (la previsualización aprobada queda pendiente).</p>`;
  const on=(q,ev,fn)=>box.querySelectorAll(q).forEach(el=>el[ev]=()=>fn(el));const apply=r=>{if(r.error){toast(r.error);controls();}else commit(r.rig);};
  on('[data-set]','onclick',el=>apply(rigWithCamera(draft,el.dataset.set,stage.camera())));
  on('[data-type]','onchange',el=>{const r=rigWithType(draft,el.value,{positioned:followable});if(!r.error&&r.rig.type==='track')rawTrack=structuredClone(r.rig.track);apply(r);});
  on('[data-preset]','onchange',el=>{const x=presets.find(x=>x.id===el.value);if(!x)return;if(x.rig.type==='track')rawTrack=structuredClone(x.rig.track);commit(structuredClone(x.rig));});
  on('[data-easing]','onchange',el=>commit({...draft,easing:el.value}));
  on('[data-hold]','onchange',()=>{const h=[0,1].map(i=>Number(box.querySelector(`[data-hold="${i}"]`).value));const {hold:_,...rest}=draft;commit(h[0]===0&&h[1]===1?rest:{...rest,hold:h});});
  on('[data-follow]','onchange',el=>commit({...draft,follow:{...draft.follow,[el.dataset.follow]:el.dataset.follow==='smoothing'?Number(el.value):el.value}}));
  on('[data-follow="smoothing"]','oninput',el=>{box.querySelector('[data-out="fs"]').textContent=num(el.value);});
  on('[data-shake]','oninput',el=>{box.querySelector('[data-out="shake"]').textContent=num(el.value);draft={...draft,shake:Number(el.value)};update();});on('[data-shake]','onchange',el=>commit({...draft,shake:Number(el.value)}));
  on('[data-smoothing]','oninput',el=>{box.querySelector('[data-out="ts"]').textContent=num(el.value);draft={...draft,trackSmoothing:Number(el.value)};update();});on('[data-smoothing]','onchange',el=>commit({...draft,trackSmoothing:Number(el.value)}));
  on('[data-trim-apply]','onclick',()=>{const [a,b]=['from','to'].map(k=>snapTime(box.querySelector(`[data-trim="${k}"]`).value,D()));try{commit(recordedRig(trimTrack(rawTrack,a,b,{duration:D()}),{smoothing:draft.trackSmoothing}));}catch(err){toast(err.message);}});
  on('[data-record]','onclick',record);on('[data-save]','onclick',doSave);renderButton();}
 // Guardar con el save() de la app (control de revisión). Si falla, el proyecto sigue en local con la pista.
 async function doSave(){const b=$('[data-save]');if(b)b.disabled=true;try{t.cameraRig=structuredClone(draft);await save();({p,e,s,t}=find());if(!t)throw Error('El plano ya no existe en el proyecto guardado');ctx=cameraContext({shot:t,sequence:s,R});stage.updateShot(t);speaker=undefined;update();return true;}catch(err){toast(err.message);return false;}finally{if(!disposed)controls();}}
 // Botón «Renderizar vídeo»: etiqueta y estado de anim3dButton con los errores del plano (anim3dReady) y su último trabajo.
 function renderButton(){const b=$('[data-render]');if(!b)return;const errors=renderVideo?anim3dReady(getProject(),ids.shotId).errors:['Esta vista no puede lanzar trabajos'],x=anim3dButton(renderJob(),errors);b.textContent=x.label;b.disabled=x.disabled;b.title=errors.join('\n');}
 async function renderClick(){const b=$('[data-render]');b.disabled=true;try{if(isDirty()&&!await doSave())return;await renderVideo();status('Vídeo en cola: el progreso sale en el botón y el resultado en la tarjeta de la viñeta.');}catch(err){toast(err.message);}finally{if(!disposed)renderButton();}}
 $('[data-play]').onclick=play;$('[data-pause]').onclick=()=>recording||countdown?abortRecording('Grabación cancelada con la pausa. La cámara anterior se conserva.'):pause();$('[data-stop]').onclick=stopAll;$('[data-loop]').onclick=()=>{loop=!loop;transport();};
 $('[data-silent]').onchange=()=>{if($('[data-silent]').checked)hush();};
 $('[data-scrub]').oninput=ev=>{pause();time=snapTime(ev.target.value,D());update();};
 root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
 const CHM=Object.fromEntries(schedule().map(l=>[l.id,l]));$('[data-marks]').innerHTML=timelineMarks(schedule(),D()).map(m=>`<button type="button" class="anim-mark" style="left:${m.pct}%" data-at="${m.at}" title="${esc(nameOf(CHM[m.id]?.character)+': '+m.label)}" aria-label="Ir a ${esc(nameOf(CHM[m.id]?.character))} en ${m.at} s"></button>`).join('');
 root.querySelectorAll('.anim-mark').forEach(b=>b.onclick=()=>{if(recording||countdown)return;pause();time=snapTime(b.dataset.at,D());update();});
 // Teclado y ratón del vuelo: solo con el visor enfocado (clic en él) y nunca escribiendo; sin bloquear el puntero. En táctil, el dedo orbita.
 const vp=$('[data-viewport]'),typing=el=>el&&(/^(INPUT|SELECT|TEXTAREA)$/.test(el.tagName)||el.isContentEditable);
 const onKey=ev=>{if(typing(ev.target))return;const k=flyKey(ev.key);if(ev.type==='keyup'){if(k)keys.delete(k);if(k&&flying())ev.preventDefault();return;}
  if(!flying()||ev.ctrlKey||ev.metaKey||ev.altKey)return;if(k){keys.add(k);ev.preventDefault();}else if(ev.key===' ')ev.preventDefault();};
 const onDown=ev=>{vp.focus({preventScroll:true});if(ev.pointerType==='touch'||ev.button!==0||!flying())return;drag=ev.pointerId;vp.setPointerCapture?.(ev.pointerId);};
 const onMove=ev=>{if(ev.pointerId===drag&&flying())look=[look[0]+ev.movementX,look[1]+ev.movementY];};
 const onUp=ev=>{if(ev.pointerId===drag){drag=null;if(vp.hasPointerCapture?.(ev.pointerId))vp.releasePointerCapture(ev.pointerId);}if(touches.delete(ev.pointerId)&&!touches.size&&mode==='free'&&cam==='fly'){fly=flyFromCamera(stage.camera());stage.orbit(false);}};
 const onTouch=ev=>{if(ev.pointerType!=='touch'||mode!=='free'||cam!=='fly')return;touches.add(ev.pointerId);releaseKeys();stage.orbit(true);};
 const onWheel=ev=>{if(!flying())return;ev.preventDefault();setSpeed(flySpeedStep(flySpeed,ev.deltaY));};
 const onBlur=()=>{releaseKeys();drag=null;},listeners=[[vp,'keydown',onKey],[vp,'keyup',onKey],[vp,'pointerdown',onDown],[vp,'pointerdown',onTouch,{capture:true}],[vp,'pointermove',onMove],[vp,'pointerup',onUp],[vp,'pointercancel',onUp],[vp,'wheel',onWheel,{passive:false}],[vp,'blur',onBlur],[vp,'focusout',onBlur],[window,'blur',onBlur]];
 for(const [el,ev,fn,o] of listeners)el.addEventListener(ev,fn,o);
 root.querySelectorAll('[data-cam]').forEach(b=>b.onclick=()=>setCam(b.dataset.cam));$('[data-speed]').oninput=ev=>setSpeed(2**Number(ev.target.value));
 $('[data-render]').onclick=renderClick;renderTimer=setInterval(renderButton,2000);
 stage.setCamera(cameraAt(draft,0,D(),ctx));setMode('result');controls();last=performance.now();raf=requestAnimationFrame(frame);
 return {dispose(){disposed=true;releaseKeys();for(const [el,ev,fn,o] of listeners)el.removeEventListener(ev,fn,o);cancelAnimationFrame(raf);clearInterval(renderTimer);if(countdown)clearInterval(countdown);voice?.cancel();synth?.cancel();synth?.removeEventListener('voiceschanged',refreshVoices);document.removeEventListener('visibilitychange',onVisibility);stage?.dispose();},get draft(){return draft;},get stage(){return stage;},get time(){return time;}};
}
