import {createStage} from './stage.js';import {rehearsalConfig,stageReuseKey} from './workflow.mjs';
export async function mountRehearsal(root,{project,episode}){
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const shots=episode.sequences.flatMap((s,si)=>s.shots.map((t,ti)=>({s,t,si,ti})));let index=0,stage,disposed=false,playing=false,token=0,raf,abortWait,loadVersion=0,stageKey=null;
 const cfg=rehearsalConfig(project),speech=cfg.speech;const synth=window.speechSynthesis;let voices=[];let saved={};try{saved=JSON.parse(localStorage.getItem('rodaje-tts-'+project.id)||'{}');}catch{}
 root.innerHTML=`<div class="panel"><div class="row"><label>Escena<select data-scene>${episode.sequences.map((s,i)=>`<option value="${i}">${esc(s.title)}</option>`).join('')}</select></label><label>Plano<select data-shot></select></label></div><div class="stagebox"><div data-viewport style="aspect-ratio:16/9"></div><div data-subtitle class="rehearsal-subtitle" aria-live="polite"></div></div><div class="actions"><button data-prev>← Anterior</button><button data-play class="primary">▶ Ensayar capítulo</button><button data-stop>■ Parar</button><button data-next>Siguiente →</button><label>Velocidad <select data-rate><option value=".9">0,9×</option><option value="1">1×</option><option value="1.1" selected>1,1×</option></select></label><label><input data-silent type="checkbox" style="width:auto"> Solo subtítulos</label></div><p data-status role="status"></p><details><summary>Voces del navegador por personaje</summary><div class="grid" data-voices></div></details><h3 style="margin-top:20px" data-title></h3><div data-script class="rehearsal-script"></div></div>`;
 const $=s=>root.querySelector(s),status=t=>$('[data-status]').textContent=t;
 const speakerIds=[...new Set(shots.flatMap(x=>x.t.lines.map(l=>l.character)))];
 function refreshVoices(){voices=synth?.getVoices()||[];const english=voices.filter(v=>new RegExp('^'+speech.base+'\\b','i').test(v.lang));$('[data-voices]').innerHTML=speakerIds.map((id,i)=>{const c=project.characters.find(c=>c.id===id);const selected=saved[id]||english[i%Math.max(1,english.length)]?.voiceURI||'';return `<label>${esc(c.name)}<select data-person="${id}"><option value="">Voz predeterminada</option>${voices.map(v=>`<option value="${esc(v.voiceURI)}" ${selected===v.voiceURI?'selected':''}>${esc(v.name)} · ${esc(v.lang)}</option>`).join('')}</select></label>`;}).join('');root.querySelectorAll('[data-person]').forEach(el=>el.onchange=()=>{saved[el.dataset.person]=el.value;try{localStorage.setItem('rodaje-tts-'+project.id,JSON.stringify(saved));}catch{}});if(!playing)status(!synth?'Este navegador no dispone de síntesis de voz. Puedes ensayar con subtítulos.':!voices.length?'Esperando voces del navegador. Si no aparecen, abre este ensayo en Chrome con voces disponibles o activa Solo subtítulos.':'Voces del navegador listas. No se generan archivos de audio.');}
 refreshVoices();synth?.addEventListener('voiceschanged',refreshVoices);
 function stop(){playing=false;stage?.setSpeaker?.(null);token++;synth?.cancel();if(abortWait){abortWait();abortWait=null;}cancelAnimationFrame(raf);$('[data-play]').disabled=false;}
 async function load(i){const version=++loadVersion;status('Cargando decorado 3D…');$('[data-play]').disabled=true;index=Math.max(0,Math.min(shots.length-1,i));const {s,t,si,ti}=shots[index];$('[data-scene]').value=si;$('[data-shot]').innerHTML=s.shots.map((shot,j)=>`<option value="${j}" ${j===ti?'selected':''}>${j+1} · ${esc(shot.title)}</option>`).join('');$('[data-title]').textContent=`${si+1}/${episode.sequences.length} · Plano ${ti+1}/${s.shots.length} · ${s.title}`;$('[data-script]').textContent=t.description;$('[data-subtitle]').textContent=t.lines.length?'Pulsa Ensayar para escuchar el diálogo.':'ACCIÓN · '+t.description;const key=stageReuseKey(project,s,t);let st;if(stage&&stageKey===key){st=stage;st.updateShot(t);}else{stage?.dispose();stage=null;st=await createStage($('[data-viewport]'),{project,sequence:{...s,location:t.location||s.location},shot:t});}stageKey=key;if(disposed||version!==loadVersion){st.dispose();return;}stage=st;stage.setSpeaker(null);stage.pose(0);$('[data-play]').disabled=playing;status(`${index+1}/${shots.length} planos · tiempos orientativos; cada réplica termina antes de avanzar.`);}
 function animate(from,to,duration){const at=performance.now();cancelAnimationFrame(raf);function tick(){if(!playing||disposed)return;const f=Math.min(.999,(performance.now()-at)/(duration*1000));stage?.pose(from+(to-from)*f);raf=requestAnimationFrame(tick);}tick();}
 function wait(ms){return new Promise(resolve=>{const timer=setTimeout(done,ms);function done(){clearTimeout(timer);abortWait=null;resolve();}abortWait=done;});}
 async function say(l,t,myToken){const c=project.characters.find(c=>c.id===l.character),duration=l.estimatedDuration||3;const name=c?.name||l.character;$('[data-subtitle]').textContent=`${name} · ${l.channel.toUpperCase()}${l.offscreen?' · FUERA DE CAMPO':''}\n${l.spokenText||l.text}`;animate(l.start,Math.min(t.duration-.01,l.start+duration-.01),duration/Number($('[data-rate]').value));if($('[data-silent]').checked){stage?.setSpeaker?.(l);await wait(duration*1000/Number($('[data-rate]').value));stage?.setSpeaker?.(null);return;}
 await new Promise((resolve,reject)=>{const u=new SpeechSynthesisUtterance(l.spokenText||l.text);u.lang=speech.locale;u.rate=Number($('[data-rate]').value);const uri=root.querySelector(`[data-person="${l.character}"]`)?.value;u.voice=voices.find(v=>v.voiceURI===uri)||null;u.pitch=cfg.voicePitch[l.character]??1;let done=false;const timeout=setTimeout(()=>finish(new Error('La voz del navegador no ha terminado. Selecciona otra voz o usa Solo subtítulos.')),Math.max(30000,duration*4000));function finish(err){if(done)return;done=true;stage?.setSpeaker?.(null);clearTimeout(timeout);abortWait=null;if(err&&myToken===token)reject(err);else resolve();}abortWait=()=>finish();u.onstart=()=>{if(myToken===token)stage?.setSpeaker?.(l);};u.onend=()=>finish();u.onerror=e=>finish(new Error('La voz no se ha podido reproducir: '+e.error));synth.speak(u);});}
 async function play(){if(playing||!stage)return;if(!$('[data-silent]').checked&&(!synth||!voices.length)){status('No hay voces disponibles en este navegador. Selecciona Solo subtítulos o abre el ensayo en un navegador con voces instaladas.');return;}playing=true;const myToken=++token;$('[data-play]').disabled=true;try{while(playing&&!disposed&&myToken===token){const {t}=shots[index];if(t.lines.length){for(const l of t.lines){if(!playing||myToken!==token)break;await say(l,t,myToken);if(playing&&myToken===token)await wait(60);}}else{animate(0,t.duration,t.duration);await wait(t.duration*1000);}if(!playing||myToken!==token)break;cancelAnimationFrame(raf);if(index===shots.length-1){stop();status('Fin del capítulo.');break;}await load(index+1);}}catch(e){stop();status(e.message);}}
 $('[data-play]').onclick=play;$('[data-stop]').onclick=()=>{stop();status('Ensayo detenido. Puedes repetir el plano actual.');};$('[data-prev]').onclick=()=>{stop();load(index-1).catch(e=>status(e.message));};$('[data-next]').onclick=()=>{stop();load(index+1).catch(e=>status(e.message));};$('[data-scene]').onchange=e=>{stop();load(shots.findIndex(x=>x.si===Number(e.target.value))).catch(e=>status(e.message));};$('[data-shot]').onchange=e=>{stop();load(shots.findIndex(x=>x.si===Number($('[data-scene]').value)&&x.ti===Number(e.target.value))).catch(e=>status(e.message));};
 await load(0);refreshVoices();return {dispose(){disposed=true;loadVersion++;stop();synth?.removeEventListener('voiceschanged',refreshVoices);stage?.dispose();},get time(){return stage?.time||0;}};
}
