import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {randomBytes} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {ROOT,DATA,read,write,dir,load,save,create,shot,digest,readiness,approved,safe,uid,merge,reconcileAudio,versionFile} from './store.mjs';import {jobs,enqueue,publicJob,settings,settingsFile,run} from './jobs.mjs';
const token=randomBytes(24).toString('hex'),port=Number(process.env.PORT||4320);process.env.PORT=String(port);
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.mp4':'video/mp4','.wav':'audio/wav','.mp3':'audio/mpeg','.fbx':'application/octet-stream','.md':'text/plain'};
function file(req,res,p){if(!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end();}const size=fs.statSync(p).size;const headers={'Content-Type':mime[path.extname(p)]||'application/octet-stream','X-Content-Type-Options':'nosniff','Cache-Control':'no-cache','Accept-Ranges':'bytes'};if(req.headers.range){const m=/^bytes=(\d+)-(\d*)$/.exec(req.headers.range);if(!m||Number(m[1])>=size){res.writeHead(416,{'Content-Range':`bytes */${size}`});return res.end();}const start=Number(m[1]),end=Math.min(m[2]?Number(m[2]):size-1,size-1);if(end<start){res.writeHead(416);return res.end();}res.writeHead(206,{...headers,'Content-Range':`bytes ${start}-${end}/${size}`,'Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.writeHead(200,{...headers,'Content-Length':size});fs.createReadStream(p).pipe(res);}}
async function body(req){let n=0,chunks=[];for await(const c of req){n+=c.length;if(n>75*1024*1024)throw Error('Archivo demasiado grande (máximo 50 MB)');chunks.push(c);}return JSON.parse(Buffer.concat(chunks).toString()||'{}');}
export const server=http.createServer(async(req,res)=>{const json=(data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};try{if(!['127.0.0.1:'+port,'localhost:'+port].includes(req.headers.host))return json({error:'Host no permitido'},403);const u=new URL(req.url,'http://127.0.0.1:'+port);if(req.method!=='GET'&&req.method!=='HEAD'){if(req.headers['x-rodaje-token']!==token)return json({error:'Sesión no válida'},403);if(req.headers.origin&&!['http://127.0.0.1:'+port,'http://localhost:'+port].includes(req.headers.origin))return json({error:'Origen no permitido'},403);}let b=req.method==='POST'?await body(req):null;
if(u.pathname==='/api/state'){let ffmpeg=true;try{execFileSync('ffmpeg',['-version'],{stdio:'ignore'});}catch{ffmpeg=false;}return json({token,projects:fs.readdirSync(DATA).filter(id=>fs.existsSync(path.join(DATA,id,'proyecto.json'))).map(id=>{const p=load(id);return {id:p.id,name:p.name,type:p.type,updated:p.updated,episodes:p.episodes.length,characters:p.characters.length};}),jobs:[...jobs.values()].map(publicJob),settings:{configured:!!(settings().falKey||process.env.FAL_KEY),textModel:settings().textModel||'google/gemini-2.5-pro'},health:{ffmpeg,chrome:fs.existsSync(process.env.CHROME_PATH||'/usr/bin/google-chrome')}});}
if(u.pathname==='/api/settings'&&b){const old=settings();if(b.falKey)old.falKey=b.falKey.trim();if(b.textModel)old.textModel=b.textModel;write(settingsFile,old);fs.chmodSync(settingsFile,0o600);return json({ok:true});}
if(u.pathname==='/api/projects'&&b)return json(create(b.name,b.type),201);
if(u.pathname==='/api/project'){if(b){const old=load(b.id);if(b.revision!==undefined&&old.revision!==b.revision){const base=versionFile(b.id,b.revision);if(!fs.existsSync(base))throw Object.assign(Error('El proyecto cambió. Recarga antes de guardar.'),{status:409});const before=read(base);b=reconcileAudio(before,b,merge(before,b,old));b.revision=old.revision;}for(const e of b.episodes||[])for(const s of e.sequences||[])for(const t of s.shots||[]){let prev;try{prev=shot(old,t.id).shot;}catch{}for(const key of ['approval','preview','keyframe','final','history'])if(prev)t[key]=prev[key];else delete t[key];}return json(save(b,b.revision));}return json(load(u.searchParams.get('id')));}
if(u.pathname==='/api/asset')return file(req,res,safe(dir(u.searchParams.get('project')),u.searchParams.get('file')));
if(u.pathname==='/api/upload'&&b){load(b.project);const ext=path.extname(b.name||'').toLowerCase();if(!['.png','.jpg','.jpeg','.webp','.mp3','.wav','.mp4'].includes(ext))throw Error('Formato admitido: PNG, JPG, WEBP, MP3, WAV o MP4');const buf=Buffer.from(b.data||'','base64');if(!buf.length||buf.length>50*1024*1024)throw Error('Archivo vacío o mayor de 50 MB');const rel='assets/'+uid()+ext;fs.writeFileSync(safe(dir(b.project),rel),buf);let seconds;try{if(['.wav','.mp3','.mp4'].includes(ext))seconds=Number(execFileSync('ffprobe',['-v','error','-show_entries','format=duration','-of','default=nw=1:nk=1',safe(dir(b.project),rel)],{encoding:'utf8'}));}catch{throw Error('No se reconoce el archivo de audio/vídeo');}return json({file:rel,duration:seconds});}
if(u.pathname==='/api/job'&&b)return json(enqueue(b.project,b.type,b.target,b.extra),202);
if(u.pathname==='/api/resume'&&b){const j=jobs.get(b.id);if(!j?.requestId)throw Error('Este trabajo no tiene una solicitud remota recuperable');if(!['failed','interrupted'].includes(j.status))throw Error('El trabajo ya está activo o terminado');j.status='remote';j.error=null;void run(j);return json({ok:true});}
if(u.pathname==='/api/approve'&&b){const p=load(b.project),t=shot(p,b.shot).shot;if(!t.preview||t.preview.hash!==digest(p,b.shot))throw Error('La previsualización está desactualizada');const issues=readiness(p,b.shot);if(issues.length)throw Error(issues.join('; '));t.approval={hash:digest(p,b.shot),preview:t.preview.job,at:new Date().toISOString()};return json(save(p));}
if(u.pathname==='/api/render-data'){const j=jobs.get(u.searchParams.get('job'));if(!j)throw Error('Trabajo no encontrado');const {sequence:s,shot:t}=shot(j.snapshot,j.target);return json({project:j.snapshot,sequence:s,shot:t,events:j.events||[]});}
if(u.pathname==='/api/shot-state'){const p=load(u.searchParams.get('project'));const id=u.searchParams.get('shot');return json({hash:digest(p,id),approved:approved(p,id),issues:readiness(p,id)});}
if(u.pathname.startsWith('/three/'))return file(req,res,safe(path.join(ROOT,'node_modules/three'),u.pathname.slice(7)));
if(u.pathname==='/assets/y_bot.fbx')return file(req,res,path.join(ROOT,'assets/y_bot.fbx'));
const staticFiles={'/':'index.html','/index.html':'index.html','/app.js':'app.js','/style.css':'style.css','/stage.js':'stage.js','/workflow.mjs':'workflow.mjs','/render.html':'render.html'};if(staticFiles[u.pathname])return file(req,res,path.join(ROOT,'app',staticFiles[u.pathname]));return json({error:'No encontrado'},404);
}catch(e){json({error:e.message},e.status||400);}});
server.listen(port,'127.0.0.1',()=>console.log(`Rodaje · http://127.0.0.1:${port}`));
