import http from 'node:http';import https from 'node:https';import os from 'node:os';import fs from 'node:fs';import path from 'node:path';import {randomBytes} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {ROOT,DATA,read,write,dir,load,save,create,shot,digest,readiness,approved,safe,uid,merge,reconcileAudio,versionFile,listProjects} from './store.mjs';import {jobs,enqueue,publicJob,settings,settingsFile,run} from './jobs.mjs';import {listLotes,loteDetail,review,montar} from './montaje.mjs';import {stageFallback,previewIssues} from './workflow.mjs';import {writeActiveProject} from '../lib/proyecto-activo.mjs';import {probeDuration} from '../lib/media.mjs';import {chromePath} from '../lib/chrome.mjs';import {readPlanta,savePlanta} from '../lib/planta.mjs';import {falKey} from '../lib/fal.mjs';
const token=randomBytes(24).toString('hex'),port=Number(process.env.PORT||4320);process.env.PORT=String(port);
// Con RODAJE_LAN=1 el servidor escucha en todas las interfaces y admite las direcciones privadas de esta máquina (móvil en la misma wifi). Sin ella, solo localhost.
// Con RODAJE_TLS_CERT y RODAJE_TLS_KEY se abre además un puerto HTTPS (RODAJE_TLS_PORT, por defecto el siguiente): la copia sin conexión del móvil (movil.html) exige una dirección segura. RODAJE_HOSTS admite otros hosts separados por comas, con esquema si difiere (p. ej. https://pc.tailnet.ts.net).
const lan=process.env.RODAJE_LAN==='1',lanIps=lan?Object.values(os.networkInterfaces()).flat().filter(i=>i&&i.family==='IPv4'&&!i.internal).map(i=>i.address):[];const names=['127.0.0.1','localhost',...lanIps];
const tls=process.env.RODAJE_TLS_CERT&&process.env.RODAJE_TLS_KEY?{cert:fs.readFileSync(process.env.RODAJE_TLS_CERT),key:fs.readFileSync(process.env.RODAJE_TLS_KEY)}:null,tlsPort=Number(process.env.RODAJE_TLS_PORT||port+1);
const extra=(process.env.RODAJE_HOSTS||'').split(',').map(h=>h.trim()).filter(Boolean).map(h=>/^https?:\/\//.test(h)?h:'http://'+h);
const origins=[...names.map(h=>'http://'+h+':'+port),...(tls?names.map(h=>'https://'+h+':'+tlsPort):[]),...extra],hosts=origins.map(o=>o.replace(/^https?:\/\//,''));
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.mp4':'video/mp4','.wav':'audio/wav','.mp3':'audio/mpeg','.fbx':'application/octet-stream','.glb':'model/gltf-binary','.md':'text/plain','.txt':'text/plain; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
function file(req,res,p){if(!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end();}const size=fs.statSync(p).size;const headers={'Content-Type':mime[path.extname(p)]||'application/octet-stream','X-Content-Type-Options':'nosniff','Cache-Control':'no-cache','Accept-Ranges':'bytes'};if(req.headers.range){const m=/^bytes=(\d+)-(\d*)$/.exec(req.headers.range);if(!m||Number(m[1])>=size){res.writeHead(416,{'Content-Range':`bytes */${size}`});return res.end();}const start=Number(m[1]),end=Math.min(m[2]?Number(m[2]):size-1,size-1);if(end<start){res.writeHead(416);return res.end();}res.writeHead(206,{...headers,'Content-Range':`bytes ${start}-${end}/${size}`,'Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.writeHead(200,{...headers,'Content-Length':size});fs.createReadStream(p).pipe(res);}}
async function body(req){let n=0,chunks=[];for await(const c of req){n+=c.length;if(n>75*1024*1024)throw Error('Archivo demasiado grande (máximo 50 MB)');chunks.push(c);}return JSON.parse(Buffer.concat(chunks).toString()||'{}');}
const handler=async(req,res)=>{const json=(data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};try{if(!hosts.includes(req.headers.host))return json({error:'Host no permitido'},403);const u=new URL(req.url,'http://127.0.0.1:'+port);if(req.method!=='GET'&&req.method!=='HEAD'){if(req.headers['x-rodaje-token']!==token)return json({error:'Sesión no válida'},403);if(req.headers.origin&&!origins.includes(req.headers.origin))return json({error:'Origen no permitido'},403);}let b=req.method==='POST'?await body(req):null;
if(u.pathname==='/api/state'){let ffmpeg=true;try{execFileSync('ffmpeg',['-version'],{stdio:'ignore'});}catch{ffmpeg=false;}return json({token,projects:listProjects(),jobs:[...jobs.values()].map(publicJob),settings:{configured:!!falKey(),textModel:settings().textModel||'google/gemini-2.5-pro'},health:{ffmpeg,chrome:fs.existsSync(chromePath())}});}
if(u.pathname==='/api/settings'&&b){const old=settings();if(b.falKey)old.falKey=b.falKey.trim();if(b.textModel)old.textModel=b.textModel;write(settingsFile,old);fs.chmodSync(settingsFile,0o600);return json({ok:true});}
if(u.pathname==='/api/projects'&&b){const created=create(b.name,b.type);writeActiveProject(created.id);return json(created,201);}
// Proyecto activo para los scripts (lib/cli.mjs): lo fija abrir un proyecto en la vista Proyectos.
if(u.pathname==='/api/active'&&b){writeActiveProject(b.project);return json({ok:true,project:b.project});}
if(u.pathname==='/api/project'){if(b){const old=load(b.id);if(b.revision!==undefined&&old.revision!==b.revision){const base=versionFile(b.id,b.revision);if(!fs.existsSync(base))throw Object.assign(Error('El proyecto cambió. Recarga antes de guardar.'),{status:409});const before=read(base);b=reconcileAudio(before,b,merge(before,b,old));b.revision=old.revision;}for(const e of b.episodes||[])for(const s of e.sequences||[])for(const t of s.shots||[]){let prev;try{prev=shot(old,t.id).shot;}catch{}for(const key of ['approval','preview','keyframe','final','history'])if(prev)t[key]=prev[key];else delete t[key];}return json(save(b,b.revision));}return json(load(u.searchParams.get('id')));}
if(u.pathname==='/api/planta')return json(b?savePlanta(b.project,b.environment,{revision:b.revision,planta:b.planta}):readPlanta(u.searchParams.get('project'),u.searchParams.get('environment')));
if(u.pathname==='/api/lotes')return json(listLotes(u.searchParams.get('project')));
if(u.pathname==='/api/lote')return json(loteDetail(u.searchParams.get('project'),u.searchParams.get('lote')));
if(u.pathname==='/api/lote-review'&&b)return json(review(b.project,b.lote,b.block,{attempt:b.attempt,verdict:b.verdict??null,rules:b.rules||[],notes:b.notes||'',range:b.range||undefined}));
if(u.pathname==='/api/montar'&&b)return json(montar(b.project,b.lote),202);
if(u.pathname==='/api/asset')return file(req,res,safe(dir(u.searchParams.get('project')),u.searchParams.get('file')));
if(u.pathname==='/api/upload'&&b){load(b.project);const ext=path.extname(b.name||'').toLowerCase();if(!['.png','.jpg','.jpeg','.webp','.mp3','.wav','.mp4','.glb'].includes(ext))throw Error('Formato admitido: PNG, JPG, WEBP, MP3, WAV, MP4 o GLB');const buf=Buffer.from(b.data||'','base64');if(!buf.length||buf.length>50*1024*1024)throw Error('Archivo vacío o mayor de 50 MB');const rel='assets/'+uid()+ext;fs.writeFileSync(safe(dir(b.project),rel),buf);let seconds;try{if(['.wav','.mp3','.mp4'].includes(ext))seconds=probeDuration(safe(dir(b.project),rel));}catch{throw Error('No se reconoce el archivo de audio/vídeo');}return json({file:rel,duration:seconds});}
if(u.pathname==='/api/job'&&b)return json(enqueue(b.project,b.type,b.target,b.extra),202);
if(u.pathname==='/api/resume'&&b){const j=jobs.get(b.id);if(!j?.requestId)throw Error('Este trabajo no tiene una solicitud remota recuperable');if(!['failed','interrupted'].includes(j.status))throw Error('El trabajo ya está activo o terminado');j.status='remote';j.error=null;void run(j);return json({ok:true});}
if(u.pathname==='/api/approve'&&b){const p=load(b.project),t=shot(p,b.shot).shot;if(!t.preview||t.preview.hash!==digest(p,b.shot))throw Error('La previsualización está desactualizada');const issues=readiness(p,b.shot);if(issues.length)throw Error(issues.join('; '));t.approval={hash:digest(p,b.shot),preview:t.preview.job,at:new Date().toISOString()};return json(save(p));}
if(u.pathname==='/api/render-data'){const j=jobs.get(u.searchParams.get('job'));if(!j)throw Error('Trabajo no encontrado');const {sequence:s,shot:t}=shot(j.snapshot,j.target);return json({project:stageFallback(j.snapshot,j.snapshot.stage?null:load(j.project)),sequence:s,shot:t,events:j.events||[]});}
if(u.pathname==='/api/shot-state'){const p=load(u.searchParams.get('project'));const id=u.searchParams.get('shot');return json({hash:digest(p,id),approved:approved(p,id),issues:[...previewIssues(shot(p,id).shot),...readiness(p,id)]});}
if(u.pathname.startsWith('/three/'))return file(req,res,safe(path.join(ROOT,'node_modules/three'),u.pathname.slice(7)));
if(u.pathname.startsWith('/viewer/'))return file(req,res,safe(path.join(ROOT,'viewer'),u.pathname.slice(8)));
if(u.pathname==='/assets/y_bot.fbx')return file(req,res,path.join(ROOT,'assets/y_bot.fbx'));
const staticFiles={'/':'index.html','/index.html':'index.html','/app.js':'app.js','/style.css':'style.css','/stage.js':'stage.js','/workflow.mjs':'workflow.mjs','/render.html':'render.html','/sw.js':'sw.js','/manifest.webmanifest':'manifest.webmanifest','/movil.html':'movil.html','/icon.svg':'icon.svg','/icon-192.png':'icon-192.png','/icon-512.png':'icon-512.png'};if(staticFiles[u.pathname])return file(req,res,path.join(ROOT,'app',staticFiles[u.pathname]));return json({error:'No encontrado'},404);
}catch(e){json({error:e.message},e.status||400);}};export const server=http.createServer(handler);
const bind=lan?'0.0.0.0':'127.0.0.1',movil=(tls?origins.filter(o=>o.startsWith('https://')):origins).find(o=>!/127\.0\.0\.1|localhost/.test(o))||origins[0],ready=()=>console.log(origins.map(o=>`Rodaje · ${o}`).join('\n')+`\nCopia para el móvil: ${movil}/movil.html`);
server.listen(port,bind,ready);if(tls)https.createServer(tls,handler).listen(tlsPort,bind);
