import {appearance,rehearsalConfig,exteriorPartAt,gearFor,cameraFollows,propKind,swarmState,propPosition,cartCarrier,lookAt} from './workflow.mjs';
import * as T from 'three';import {OrbitControls} from '/three/examples/jsm/controls/OrbitControls.js';import {FBXLoader} from '/three/examples/jsm/loaders/FBXLoader.js';import {clone} from '/three/examples/jsm/utils/SkeletonUtils.js';import {createKit} from '/viewer/kit.mjs';
let source;const motionCache=new Map();
async function motion(project,file){const key=project+file;if(!motionCache.has(key))motionCache.set(key,new FBXLoader().loadAsync(`/api/asset?project=${project}&file=${encodeURIComponent(file)}`));return motionCache.get(key);}
const palette=['#689fba','#b9a06b','#80a799','#b47b6c','#a1a7bd','#c0b5a2','#887aab'];
export async function createStage(container,data){const {project:p,sequence:s}=data;let t=data.shot;const R=rehearsalConfig(p,t);const world=new T.Scene();world.background=new T.Color('#171e24');world.add(new T.HemisphereLight('#e4edfa','#3d3a30',3));const light=new T.DirectionalLight('#fff5dd',2.5);light.position.set(-4,8,5);world.add(light);const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,logarithmicDepthBuffer:true});renderer.setSize(1280,720,false);renderer.setPixelRatio(1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;container.replaceChildren(renderer.domElement);const camera=new T.PerspectiveCamera(45,16/9,.1,150),controls=new OrbitControls(camera,renderer.domElement);let stopped=false,raf,clock=0,playing=false,start=0,context,sources=[],manualSpeaker=false,liveSpeaker=null;
const mesh=(geo,color,x,y,z)=>{const m=new T.Mesh(geo,new T.MeshStandardMaterial({color,roughness:.85}));m.position.set(x,y,z);world.add(m);return m;};const loc=p.locations.find(l=>l.id===s.location);const floor=mesh(new T.BoxGeometry(Math.max(35,(loc?.modelSpace?.size?.[0]||0)+4),.1,Math.max(35,(loc?.modelSpace?.size?.[2]||0)+4)),loc?.ground||'#4d5551',0,-.06,0);const grid=new T.GridHelper(30,30,'#65756c','#555f5b');grid.position.y=.002;world.add(grid);
if(loc?.kind==='forest')for(let i=0;i<18;i++){const a=i*2.3999,r=6+i*.3;mesh(new T.CylinderGeometry(.13,.25,5,7),'#615144',Math.sin(a)*r,2.5,-5-Math.abs(Math.cos(a)*r));mesh(new T.ConeGeometry(1.2,3,7),'#455c50',Math.sin(a)*r,5,-5-Math.abs(Math.cos(a)*r));}if(loc?.kind==='interior'){const [w,h,d]=loc.modelSpace?.size||[12,4,8];mesh(new T.BoxGeometry(w,h,.15),'#747575',0,h/2,-d/2);mesh(new T.BoxGeometry(.15,h,d),'#626c70',-w/2,h/2,0);for(const part of loc.modelSpace?.kit||[]){const m=mesh(part.shape==='cylinder'?new T.CylinderGeometry(part.radius,part.radius,part.height,12):new T.BoxGeometry(...part.size),part.color,...part.position);if(part.texture){const tex=await new T.TextureLoader().loadAsync('/api/asset?project='+encodeURIComponent(p.id)+'&file='+encodeURIComponent(part.texture));tex.colorSpace=T.SRGBColorSpace;m.material.map=tex;m.material.needsUpdate=true;}}}if(loc?.kind==='city')for(let i=0;i<8;i++)mesh(new T.BoxGeometry(2,3+i%3,2),'#66747e',(i-4)*3,1.5+(i%3)/2,-6);
// Entorno 3D enlazado al ambiente: se construye con el estado de la secuencia y se desplaza para que el lugar elegido quede en el origen del reparto.
const env=loc?.environment&&(p.environments||[]).find(e=>e.id===loc.environment);if(env?.builder&&env?.data){try{const asset=f=>'/api/asset?project='+encodeURIComponent(p.id)+'&file='+encodeURIComponent(f);const envData=await(await fetch(asset(env.data))).json();const mod=await import(asset(env.builder));const cfg=s.environment||{};const preset=(envData.presets||[]).find(x=>x.id===cfg.preset);const model=mod.build(T,envData,createKit(T,{state:{...(preset?.state||{}),...(cfg.state||{})},textures:true,textureUrl:f=>asset(env.data.split('/').slice(0,-1).join('/')+'/'+f)}));const spot=(envData.landmarks||[]).find(l=>l.id===cfg.spot);let origin=new T.Vector3();if(spot){let y=spot.floor;if(y===undefined){model.updateMatrixWorld(true);const ground=model.getObjectByName('suelo')||model;const hit=new T.Raycaster(new T.Vector3(spot.at[0],spot.at[1]+30,spot.at[2]),new T.Vector3(0,-1,0),0,80).intersectObject(ground,true)[0];y=hit?hit.point.y:spot.at[1];}origin.set(spot.at[0],y,spot.at[2]);}model.position.sub(origin);const pivot=new T.Group();pivot.name='entorno';pivot.rotation.y=(cfg.rotation||0)*Math.PI/180;pivot.add(model);world.add(pivot);floor.visible=false;grid.visible=false;world.background=new T.Color('#b9c0c4');camera.far=400;camera.updateProjectionMatrix();}catch(err){console.error('Entorno 3D',err);}}
const animatedProps=[];
for(const prop of s.props||[]){if(propKind(R,prop.type)==='swarm'){for(let i=0;i<65;i++){const m=mesh(new T.SphereGeometry(.085,8,6),prop.color,Math.sin(i*2.4)*3, .3+(i%13)*.2,-3+Math.cos(i*1.8)*3);m.scale.set(1,.7,.8);animatedProps.push({m,origin:m.position.clone(),i});}}else mesh(prop.type==='sphere'?new T.SphereGeometry(prop.size||1,16,12):new T.BoxGeometry(prop.width||prop.size||1,prop.height||(prop.type==='pool'?.05:prop.size||1),prop.depth||prop.size||1),prop.color||'#8e8172',prop.x||0,prop.y||.5,prop.z||0);}
// Exterior del ensayo (stage.rehearsal.exteriors[staging.exterior]): sustituye el decorado por piezas simples que pueden derivar y girar con el tiempo de la secuencia.
const exteriorMeshes=[],exteriorKey=R.exteriorKey;if(R.exterior){grid.visible=false;for(const obj of world.children)if(obj.isMesh)obj.visible=false;world.background=new T.Color(R.exterior.background);for(const part of R.exterior.parts){const geo=part.shape==='cylinder'?new T.CylinderGeometry(part.radius,part.radius,part.height,part.segments??32):part.shape==='sphere'?new T.SphereGeometry(part.radius,...(part.segments??[32,24])):new T.BoxGeometry(...part.size);const m=mesh(geo,part.color,...part.position);if(part.rotation)m.rotation.set(...part.rotation);exteriorMeshes.push({m,origin:m.position.clone(),part});}}
source??=await new FBXLoader().loadAsync('/assets/y_bot.fbx');const actors=[];const aim=(bone,child,dir)=>{world.updateMatrixWorld(true);const old=child.getWorldPosition(new T.Vector3()).sub(bone.getWorldPosition(new T.Vector3())).normalize();const delta=new T.Quaternion().setFromUnitVectors(old,dir.normalize());bone.quaternion.copy(bone.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(delta.multiply(bone.getWorldQuaternion(new T.Quaternion()))));world.updateMatrixWorld(true);};
for(const [i,placement] of s.cast.entries()){const a={...placement,...t.staging?.placements?.[placement.character]};const original=p.characters.find(c=>c.id===a.character);if(!original||original.kind==='voice')continue;const c=appearance(original,{...s,variant:t.variant||s.variant});const group=new T.Group();group.position.set(a.x,0,a.z);group.rotation.y=a.yaw;world.add(group);const model=clone(source);model.scale.setScalar(.01);group.add(model);const bones={};model.traverse(o=>{if(o.isMesh){o.geometry=o.geometry.clone();o.material=new T.MeshStandardMaterial({color:c.color||palette[i%palette.length],roughness:.75,metalness:.1});}if(o.isBone&&!bones[o.name.replace('mixamorig','')])bones[o.name.replace('mixamorig','')]=o;});if(a.pose!=='standing'){bones.Hips.position.y=60;const local=v=>new T.Vector3(...v).applyAxisAngle(new T.Vector3(0,1,0),a.yaw);for(const side of ['Left','Right']){const k=side==='Left'?1:-1;aim(bones[side+'UpLeg'],bones[side+'Leg'],local([k*.07,-.03,.4]));aim(bones[side+'Leg'],bones[side+'Foot'],local([0,-.42,.04]));aim(bones[side+'Arm'],bones[side+'ForeArm'],local([k*.08,-.25,.09]));aim(bones[side+'ForeArm'],bones[side+'Hand'],local([-k*.1,-.1,.24]));}const seat=new T.Mesh(new T.BoxGeometry(.6,.45,.55),new T.MeshStandardMaterial({color:'#5f625d'}));seat.position.set(0,.225,0);group.add(seat);}else{for(const side of ['Left','Right']){const k=side==='Left'?1:-1;const v=new T.Vector3(k*.10,-.4,.02).applyAxisAngle(new T.Vector3(0,1,0),a.yaw);aim(bones[side+'Arm'],bones[side+'ForeArm'],v);}}
if(t.rehearsal){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=48;const ctx=canvas.getContext('2d');ctx.fillStyle='#162b28';ctx.fillRect(0,0,256,48);ctx.fillStyle='white';ctx.font='bold 25px sans-serif';ctx.textAlign='center';ctx.fillText(c.name.split(' ')[0],128,33);const label=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(canvas),depthTest:false}));label.position.set(0,a.pose==='seated'?1.65:2.05,0);label.scale.set(.5,.095,1);group.add(label);}const base={};for(const name of ['Head','Spine2','RightForeArm','LeftForeArm','RightArm','LeftArm'])base[name]=bones[name].quaternion.clone();const gear=gearFor(R,t.variant||s.variant,c.id);if(gear==='helmet'){const helmet=new T.Mesh(new T.SphereGeometry(19,20,16),new T.MeshStandardMaterial({color:'#646f74',transparent:true,opacity:.30,depthWrite:false,roughness:.45}));helmet.position.set(0,8,0);bones.Head.add(helmet);}if(gear==='mask'){const mask=new T.Mesh(new T.BoxGeometry(17,10,9),new T.MeshStandardMaterial({color:'#454b48'}));mask.position.set(0,0,10);bones.Head.add(mask);}const talkLight=new T.Mesh(new T.SphereGeometry(.035,8,6),new T.MeshBasicMaterial({color:'#ffa832'}));talkLight.position.set(0,0,.11);bones.Head.add(talkLight);talkLight.scale.setScalar(100);talkLight.position.set(0,9,11);talkLight.visible=false;const mouth=new T.Mesh(new T.CircleGeometry(1,24),new T.MeshBasicMaterial({color:'#000000',side:T.DoubleSide}));mouth.position.set(0,2.5,14);mouth.scale.set(5.5,.5,1);mouth.visible=false;mouth.renderOrder=20;bones.Head.add(mouth);const chestSignal=new T.Mesh(new T.SphereGeometry(.055,12,8),new T.MeshBasicMaterial({color:'#ffd55a'}));chestSignal.position.set(0,a.pose==='seated'?1.02:1.38,.18);chestSignal.visible=false;group.add(chestSignal);let mixer,actions;
if(R.animations){
 const roles=['idle','talk','walk'];const clips=await Promise.all(roles.map(r=>motion(p.id,R.animations.files[r])));
 mixer=new T.AnimationMixer(model);actions=clips.map((src,j)=>{const clip=src.animations[0].clone();clip.name=R.animations.files[roles[j]].split('/').pop().replace(/\.fbx$/,'');const upper=tr=>/Shoulder|Arm|Hand|Thumb|Index|Middle|Ring|Pinky/.test(tr.name);
 if(roles[j]==='talk'||a.pose==='seated')clip.tracks=clip.tracks.filter(upper);
 for(const tr of clip.tracks)if(tr.name.endsWith('Hips.position')){const ratio=100/(src.getObjectByName('mixamorigHips')?.position.y||100);for(let k=0;k<tr.values.length;k+=3){tr.values[k]=0;tr.values[k+1]*=ratio;tr.values[k+2]=0;}}
 const action=mixer.clipAction(clip);action.play();action.setEffectiveWeight(j===0?1:0);return action;});
}
actors.push({a,c,group,model,bones,base,talkLight,mouth,chestSignal,mixer,actions});}
const director=createDirector(world,actors,s,R);
let events=data.events?.length?data.events:t.lines.map(l=>({...l,end:l.start+(l.audioDuration||l.estimatedDuration||Math.min(3,t.duration-l.start))}));function setCamera(c){camera.position.fromArray(c.position);controls.target.fromArray(c.target);camera.fov=c.fov;camera.updateProjectionMatrix();controls.update();}setCamera(t.camera);if(t.rehearsal&&!t.detail&&actors.length){camera.position.lerp(controls.target,.25);camera.position.y=Math.max(camera.position.y,1.6);camera.fov=46;camera.updateProjectionMatrix();}
function pose(time,moveCamera=true){clock=time;const active=manualSpeaker?(liveSpeaker?[liveSpeaker]:[]):events.filter(l=>time>=l.start&&time<l.end),e=active.find(l=>!l.offscreen&&l.channel!=='pa'),anticipate=e||events.find(l=>!l.offscreen&&l.channel!=='pa'&&time>=l.start-.35&&time<l.end+.2);if(moveCamera){if(t.cameraMotion==='establishing-reveal'){const f=T.MathUtils.smoothstep(Math.min(1,time/(t.duration*.75)),0,1);setCamera({position:t.camera.position.map((v,i)=>T.MathUtils.lerp(v,t.cameraEnd.position[i],f)),target:t.camera.target.map((v,i)=>T.MathUtils.lerp(v,t.cameraEnd.target[i],f)),fov:T.MathUtils.lerp(t.camera.fov,t.cameraEnd.fov,f)});}else if(t.rehearsal&&!t.detail){const subject=cameraFollows(R,e?.character)?actors.find(a=>a.c.id===e?.character):null;const center=t.camera.target.slice();if(subject){center[0]=subject.a.x;center[1]=subject.a.pose==='seated'?1.2:1.45;center[2]=subject.a.z;}controls.target.lerp(new T.Vector3(...center),.045);camera.fov=T.MathUtils.lerp(camera.fov,subject?36:46,.035);camera.updateProjectionMatrix();camera.lookAt(controls.target);controls.update();}else{const f=T.MathUtils.smoothstep(time/t.duration,0,1);setCamera({position:t.camera.position.map((v,i)=>T.MathUtils.lerp(v,t.cameraEnd.position[i],f)),target:t.camera.target.map((v,i)=>T.MathUtils.lerp(v,t.cameraEnd.target[i],f)),fov:T.MathUtils.lerp(t.camera.fov,t.cameraEnd.fov,f)});if(t.coverage?.length){const cut=t.coverage.filter(c=>c.start<=time).at(-1);if(cut?.camera)setCamera(cut.camera);}}}for(const [i,a] of actors.entries()){const motion=t.staging?.moves?.[a.c.id];a.group.position.set(a.a.x,0,a.a.z);a.group.rotation.set(0,a.a.yaw,0);if(motion){const f=T.MathUtils.clamp(time/t.duration,0,1);const delta=new T.Vector3(...motion.delta);if(motion.kind==='glide-out')a.group.position.addScaledVector(delta,f);else a.group.position.addScaledVector(delta,f-1);if(motion.kind==='walk'||motion.kind.startsWith('glide')){a.group.rotation.y=Math.atan2(delta.x,delta.z);a.a.yaw=a.group.rotation.y;}}for(const n in a.base)a.bones[n].quaternion.copy(a.base[n]);
if(a.mixer){const talking=active.some(l=>l.character===a.c.id&&!l.offscreen),walk=t.staging?.moves?.[a.c.id]?.kind==='walk';a.actions[0].setEffectiveWeight(walk?0:1);a.actions[1].setEffectiveWeight(!walk&&talking?.28:0);a.actions[2].setEffectiveWeight(walk?1:0);a.mixer.setTime(walk?time*Math.hypot(...t.staging.moves[a.c.id].delta)/t.duration/1.15:s.shots.slice(0,s.shots.findIndex(x=>x.id===t.id)).reduce((sum,x)=>sum+x.duration,0)+time+i*.71);if(a.a.pose==='standing'){a.model.position.y=0;a.group.updateMatrixWorld(true);const fy=Math.min(...['LeftFoot','RightFoot','LeftToeBase','RightToeBase'].map(n=>a.group.worldToLocal(a.bones[n].getWorldPosition(new T.Vector3())).y));a.model.position.y-=fy-.04;}}
a.bones.Spine2.quaternion.multiply(new T.Quaternion().setFromEuler(new T.Euler(Math.sin(time*1.6+i)*.012,0,0)));const target=anticipate?actors.find(x=>x.c.id===(a.c.id===anticipate.character?(t.listenTo||actors.find(x=>x.c.id!==a.c.id)?.c.id):anticipate.character)):null;if(target){const angle=Math.atan2(target.a.x-a.a.x,target.a.z-a.a.z)-a.group.rotation.y;a.bones.Head.quaternion.multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),T.MathUtils.clamp(Math.atan2(Math.sin(angle),Math.cos(angle)),-.65,.65)));}const speaking=active.find(l=>l.character===a.c.id&&!l.offscreen&&l.channel!=='pa');a.mouth.visible=!!speaking;a.mouth.scale.y=.55+Math.abs(Math.sin(time*12))*2.8;a.chestSignal.visible=!!speaking;a.talkLight.visible=active.some(l=>l.character===a.c.id&&l.channel==='radio'&&!l.offscreen);if(active.some(l=>l.character===a.c.id&&!l.offscreen&&l.channel!=='pa'))a.bones.RightForeArm.quaternion.multiply(new T.Quaternion().setFromEuler(new T.Euler(Math.sin(time*2.4)*.07,0,0)));}if(t.rehearsal){for(const [i,a]of actors.entries()){a.group.visible=!t.detail&&(!t.visibleCast||t.visibleCast.includes(a.c.id));if(t.gravity==='zero'){a.group.position.y=.12;} }for(const {m,origin,i} of animatedProps){const state=swarmState(t.staging)||'none';m.visible=!t.staging?.insert&&state!=='none'&&(state!=='single'||i===0);m.position.copy(origin);if(state==='single'){m.position.set(-.3,.15+Math.min(1,time/t.duration)*.6,.1);}else if(state==='settled'){m.position.y=.10;}else if(state==='leak'){m.visible=i<8;m.position.set(.3+Math.sin(i)*.4,.2+i*.08,-.2+time*.12);}else if(state==='stream'){m.position.z=origin.z+time*.18;}else if(state==='cloud'){m.position.y=origin.y+.04*Math.sin(time*.65+i);}m.rotation.set(time*.1+i,time*.15,0);}}if(exteriorMeshes.length){const elapsed=s.shots.slice(0,s.shots.findIndex(x=>x.id===t.id)).reduce((sum,x)=>sum+x.duration,0)+time;const drift=t.staging?.exterior===exteriorKey;for(const {m,origin,part} of exteriorMeshes){m.position.copy(origin);if(drift){const q=exteriorPartAt(part,elapsed);m.position.fromArray(q.position);if(q.rotation)m.rotation.fromArray(q.rotation);}}}director.update(t,time,camera);renderer.render(world,camera);return e;}
function stop(){playing=false;for(const n of sources)try{n.stop();}catch{}sources=[];}
async function play(){if(t.lines.some(l=>!l.audio))throw Error('Faltan audios de diálogo. Genera o importa las voces antes del ensayo sonoro.');stop();context??=new AudioContext();await context.resume();const tracks=[];const url=f=>'/api/asset?project='+p.id+'&file='+encodeURIComponent(f);for(const l of t.lines)if(l.audio)tracks.push({buffer:await context.decodeAudioData(await(await fetch(url(l.audio))).arrayBuffer()),at:l.start,gain:1,loop:false});if(s.ambience&&!s.silent)tracks.push({buffer:await context.decodeAudioData(await(await fetch(url(s.ambience))).arrayBuffer()),at:0,gain:s.ambienceGain??.18,loop:true});if(stopped)return;start=context.currentTime+.1;for(const tr of tracks){const src=context.createBufferSource(),gain=context.createGain();src.buffer=tr.buffer;src.loop=tr.loop;gain.gain.value=tr.gain;src.connect(gain).connect(context.destination);src.start(start+tr.at,tr.loop?s.shots.slice(0,s.shots.findIndex(x=>x.id===t.id)).reduce((n,x)=>n+x.duration,0)%tr.buffer.duration:0);src.stop(start+t.duration);sources.push(src);}playing=true;}
function loop(){if(stopped)return;if(playing){const time=Math.max(0,context.currentTime-start);pose(Math.min(t.duration,time));if(time>=t.duration)stop();}else renderer.render(world,camera);raf=requestAnimationFrame(loop);}loop();pose(0);
return {updateShot(next){t=next;if(t.staging?.cut)setCamera(t.camera);events=t.lines.map(l=>({...l,end:l.start+(l.estimatedDuration||3)}));clock=0;liveSpeaker=null;pose(0,false);},frame(time){pose(time);return renderer.domElement.toDataURL('image/png');},pose,play,stop,setSpeaker(line){manualSpeaker=true;liveSpeaker=line;pose(clock,false);},speakerState(){return actors.map(a=>({id:a.c.id,visible:a.group.visible,mouth:a.mouth.visible,signal:a.chestSignal.visible,animated:!!a.mixer}));},diagnostics(){return {contacts:director.contacts(),actors:actors.map(a=>({id:a.c.id,position:a.group.position.toArray(),visible:a.group.visible})),swarm:animatedProps.filter(p=>p.m.visible).length};},camera(){return {position:camera.position.toArray(),target:controls.target.toArray(),fov:camera.fov};},setCamera,dispose(){director.dispose();stopped=true;stop();context?.close();cancelAnimationFrame(raf);controls.dispose();world.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){m.map?.dispose();m.dispose();}}});renderer.dispose();},get time(){return clock;}};}

// Shot-authored blocking. All positions are metres; Mixamo bones remain centimetres.
// Atrezo con posición por plano (staging.propMoves); la carga cae por defecto donde la deja el constructor del director.
const CARGO_AT=[.3,0,.05];
function createDirector(world,actors,sequence,R){
 const group=new T.Group();world.add(group);const tools=new Map();let current=null;let cargo=null;let card=null;let insertRig=null;let dog=null;const contacts=[];
 const material=c=>new T.MeshStandardMaterial({color:c,roughness:.85});
 function box(parent,size,pos,color){const m=new T.Mesh(new T.BoxGeometry(...size),material(color));m.position.fromArray(pos);parent.add(m);return m;}
 function ball(parent,r,pos,color){const m=new T.Mesh(new T.SphereGeometry(r,12,8),material(color));m.position.fromArray(pos);parent.add(m);return m;}
 function clear(){group.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});group.clear();tools.clear();cargo=null;card=null;insertRig=null;dog=null;}
 function label(text){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=512;const c=canvas.getContext('2d');c.fillStyle='black';c.fillRect(0,0,1024,512);c.fillStyle='#eee';c.textAlign='center';c.font='52px sans-serif';c.fillText(text,512,265);return new T.MeshBasicMaterial({map:new T.CanvasTexture(canvas),depthTest:false});}
 function rebuild(st){clear();current=st; if(Object.hasOwn(st,'title')){card=new T.Mesh(new T.PlaneGeometry(2,1),label(st.title));card.renderOrder=1000;group.add(card);return;}
 const props=st.props||[],tasks=st.tasks||{};
 if(props.includes('cargo')&&!st.insert){cargo=new T.Group();group.add(cargo);cargo.position.set(.3,0,.05);box(cargo,[2.4,1.7,1.35],[0,.98,0],'#52636b');box(cargo,[2.6,.18,1.65],[0,.18,0],'#282d31');for(const x of [-1,1]){box(cargo,[.07,1.74,1.4],[x,.98,0],'#b9a47b');for(const z of [-.55,.55])ball(cargo,.12,[x,.12,z],'#191e22');}for(const x of [-1,1])box(group,[.07,.035,12],[x,.025,-2],'#8d999b');}
 if(props.includes('cart')&&!cargo){cargo=new T.Group();cargo.userData.cart=true;group.add(cargo);box(cargo,[1,.12,1.4],[0,.25,0],'#898c87');for(const x of [-.4,.4])for(const z of [-.55,.55])ball(cargo,.13,[x,.13,z],'#222729');box(cargo,[1,.05,.05],[0,1.22,-.55],'#abb6b7');for(const x of [-.45,.45])box(cargo,[.04,1,.04],[x,.73,-.55],'#abb6b7');for(let i=0;i<9;i++)ball(cargo,.14,[(i%3)*.25-.25,.42,Math.floor(i/3)*.25-.25],'#96815d');}
 if(props.includes('dog')){dog=new T.Group();group.add(dog);box(dog,[.28,.3,.7],[0,.45,0],'#84735e');ball(dog,.16,[0,.64,.35],'#78624b');box(dog,[.14,.12,.16],[0,.6,.5],'#78624b');for(const x of [-.10,.10])for(const z of [-.25,.25]){const leg=box(dog,[.08,.3,.08],[x,.18,z],'#78624b');leg.userData.leg=true;}}
 for(const a of actors){const g=new T.Group();group.add(g);const item={g};tools.set(a.c.id,item);const task=tasks[a.c.id];
 if(['collect','receive','offer-bag'].includes(task)||props.includes('bags')){item.bag=new T.Group();g.add(item.bag);box(item.bag,[.48,.58,.3],[0,-.18,0],'#909888');}
 if(task==='collect'){item.piece=ball(g,.07,[0,0,0],'#96815d');}
 if(task==='shovel'){item.shovel=new T.Group();g.add(item.shovel);box(item.shovel,[.045,1.4,.045],[0,-.4,0],'#acac94');box(item.shovel,[.32,.38,.045],[0,-1.08,0],'#777f83');}
 if(task==='screen'||task==='count'){item.screen=new T.Group();g.add(item.screen);box(item.screen,[.18,.025,.25],[0,0,0],'#273940');box(item.screen,[.15,.008,.20],[0,.017,0],'#729b91');}
 if(task==='eat'||task==='serve'){item.cup=new T.Group();g.add(item.cup);const cup=new T.Mesh(new T.CylinderGeometry(.06,.05,.12,16),material('#b9b29b'));item.cup.add(cup);}
 if(task==='console'){item.console=new T.Group();g.add(item.console);box(item.console,[.9,.2,.45],[0,0,0],'#3c5159');for(let i=0;i<5;i++)box(item.console,[.08,.015,.10],[-.3+i*.15,.11,0],i===4?'#b67b56':'#8bada5');}
 if(task==='offer-mask'){item.mask=new T.Group();g.add(item.mask);box(item.mask,[.15,.10,.09],[0,0,0],'#495c59');}
 }
 if(props.includes('tied-bags'))for(let i=0;i<8;i++)box(group,[.4,.6,.3],[2,.7,-1-i*.7],'#909888');
 if(props.includes('crate')){box(group,[1.2,.6,.8],[1.8,.35,0],'#8d7956');box(group,[1.23,.07,.85],[1.8,.70,0],'#a99a7c');}
 if(st.insert){const rig=new T.Group();insertRig=rig;group.add(rig);if(st.insert==='broken-screen'){box(rig,[.25,.06,.35],[0,.15,0],'#263b40');for(let i=0;i<3;i++){const crack=box(rig,[.008,.005,.28],[i*.05-.05,.183,0],'#d1dddd');crack.rotation.y=i*.7;}}else{itemInsert(rig,st.insert);}for(const child of rig.children)child.userData.origin=child.position.clone();}
 function itemInsert(rig,type){box(rig,[1.8,.12,1.2],[0,.1,0],'#52636b');for(let i=0;i<16;i++)ball(rig,.08,[(i%4)*.3-.5,.3+Math.floor(i/4)*.22,Math.sin(i)*.4],'#9e8a61');rig.userData.falling=type==='gravity-arrives';}
 }
 const v=()=>new T.Vector3();const q=()=>new T.Quaternion();
 function aim(bone,child,direction){world.updateMatrixWorld(true);const origin=bone.getWorldPosition(v()),old=child.getWorldPosition(v()).sub(origin).normalize();const delta=q().setFromUnitVectors(old,direction.clone().normalize());bone.quaternion.copy(bone.parent.getWorldQuaternion(q()).invert().multiply(delta.multiply(bone.getWorldQuaternion(q()))));world.updateMatrixWorld(true);}
 function reach(a,side,target){const upper=a.bones[side+'Arm'],fore=a.bones[side+'ForeArm'],hand=a.bones[side+'Hand'];world.updateMatrixWorld(true);const p=upper.getWorldPosition(v()),el=fore.getWorldPosition(v()),h=hand.getWorldPosition(v());const l1=p.distanceTo(el),l2=el.distanceTo(h);const dir=target.clone().sub(p),dist=Math.max(.001,Math.min(dir.length(),l1+l2-.003));dir.normalize();const pole=new T.Vector3(side==='Right'?-.7:.7,-1,.15).applyQuaternion(a.group.quaternion);pole.addScaledVector(dir,-pole.dot(dir)).normalize();const along=(l1*l1+dist*dist-l2*l2)/(2*dist),bend=Math.sqrt(Math.max(0,l1*l1-along*along));const elbow=p.clone().addScaledVector(dir,along).addScaledVector(pole,bend);aim(upper,fore,elbow.sub(p));aim(fore,hand,target.clone().sub(fore.getWorldPosition(v())));contacts.push({character:a.c.id,side,error:hand.getWorldPosition(v()).distanceTo(target)});return hand.getWorldPosition(v());}
 function point(a,xyz){return a.group.localToWorld(new T.Vector3(...xyz));}
 function attach(obj,a,side,offset=[0,0,0]){if(!obj)return;world.updateMatrixWorld(true);obj.position.copy(a.bones[side+'Hand'].getWorldPosition(v())).add(new T.Vector3(...offset));obj.quaternion.copy(a.group.quaternion);}
 function update(t,time,camera){const st=t.staging;if(!st)return;if(st!==current)rebuild(st);contacts.length=0;
 const f=T.MathUtils.clamp(time/t.duration,0,1),phase=(sequence.shots.slice(0,sequence.shots.findIndex(x=>x.id===t.id)).reduce((sum,x)=>sum+x.duration,0)+time)*.9;
 if(card){card.position.copy(camera.position).add(camera.getWorldDirection(v()).multiplyScalar(.3));card.quaternion.copy(camera.quaternion);card.scale.setScalar(.66*Math.tan(T.MathUtils.degToRad(camera.fov/2)));return;}
 if(dog){dog.position.fromArray(propPosition(st.propMoves?.dog,f));const gait=st.propMoves?.dog?.gait===true;dog.children.filter(o=>o.userData.leg).forEach((o,i)=>o.rotation.x=gait?Math.sin(f*15+i*Math.PI)*.3:0);}
 if(insertRig){for(const [i,obj]of insertRig.children.entries()){if(!i||!obj.userData.origin)continue;obj.position.copy(obj.userData.origin);if(st.insert==='gravity-arrives')obj.position.y=Math.max(.23,obj.position.y-1.1*f*f);if(st.insert==='cargo-release'){obj.position.z+=f*.8;obj.position.y+=f*.25;obj.rotation.y=f+i;}}}
 if(cargo?.userData.cart){const id=cartCarrier(st,actors.map(x=>x.c.id)),a=actors.find(x=>x.c.id===id);if(a){cargo.position.copy(point(a,[0,0,.88]));cargo.quaternion.copy(a.group.quaternion);}}else if(cargo)cargo.position.fromArray(propPosition(st.propMoves?.cargo,f,CARGO_AT));
 const L=lookAt(st.look,actors.map(x=>x.c.id),R);
 for(const a of actors){const task=(st.tasks||{})[a.c.id],item=tools.get(a.c.id);if(!item)continue;item.g.visible=a.group.visible;const body=a.a.pose==='seated'?1.15:1.4;
 if(task==='push'&&cargo){const target=cargo.userData.cart?point(a,[-.14,1.22,.33]):new T.Vector3(a.group.position.x-.14,1.24,cargo.position.z-.69);reach(a,'Right',target);reach(a,'Left',cargo.userData.cart?point(a,[.14,1.22,.33]):target.clone().add(new T.Vector3(.28,0,0)));}
 if(task==='console'){item.console.position.copy(point(a,[0,body-.27,.32]));item.console.quaternion.copy(a.group.quaternion);reach(a,'Right',point(a,[-.1,body-.15,.32]));reach(a,'Left',point(a,[.16,body-.15,.32]));}
 if(task==='screen'||task==='count'){reach(a,'Left',point(a,[.08,body,.30]));reach(a,'Right',point(a,[.10,body+.04,.32]));attach(item.screen,a,'Left');}
 if(task==='collect'){reach(a,'Left',point(a,[.14,1.25,.30]));reach(a,'Right',point(a,[-.14,1.28+.07*Math.sin(phase),.28+.06*Math.sin(phase)]));attach(item.bag,a,'Left');if(item.piece){attach(item.piece,a,'Right');item.piece.visible=Math.sin(phase)>.05;}}
 if(task==='offer-bag'||task==='receive'||task==='offer-mask'){reach(a,'Right',point(a,[0,1.2,.45]));attach(item.bag||item.mask,a,'Right');}
 if(task==='shovel'){const scoop=Math.sin(phase);const target=point(a,[-.14,1.17+.07*scoop,.24]);reach(a,'Right',target);reach(a,'Left',point(a,[.14,1.35+.07*scoop,.24]));attach(item.shovel,a,'Right');item.shovel.rotateX(-.25+.22*scoop);}
 if(task==='eat'||task==='serve'){const sip=task==='eat'?Math.max(0,Math.sin(phase))*.18:0;reach(a,'Right',point(a,[.08,body+.1+sip,.32-sip*.4]));attach(item.cup,a,'Right');}
 if(task==='hold'||task==='lock'){reach(a,'Right',point(a,[.18,1.22,.38]));if(!item.rail){item.rail=box(item.g,[.035,.8,.035],[0,0,0],'#9ba4a4');}item.rail.position.copy(point(a,[.18,1.22,.38]));item.rail.quaternion.copy(a.group.quaternion);}
 if(L?.tilt)a.bones.Head.rotation.x-=L.ramp?L.tilt*f:L.tilt;
 if(L?.actor||L?.point){const target=L.actor?actors.find(x=>x.c.id===L.actor)?.group.position:new T.Vector3(...L.point);if(target){const delta=target.clone().sub(a.group.position);const angle=Math.atan2(delta.x,delta.z)-a.group.rotation.y;a.bones.Head.rotation.y+=T.MathUtils.clamp(Math.atan2(Math.sin(angle),Math.cos(angle)),-.4,.4);}}
 }
 }
 return{update,dispose:clear,contacts:()=>contacts};
}
