export const variants=[['','Diseño base'],['green','Verde · ropa normal'],['yellow','Amarilla · respirador'],['red','Roja · traje espacial']];
// Texto de aspecto para prompts de imagen/vídeo: el campo `look` si existe; si no, el párrafo "Current visual design" de la descripción; si no, la descripción sin cabeceras ni el bloque de voz (que no aporta nada visual).
export function visualBrief(character){if(character.look?.trim())return character.look.trim();const d=character.description||'';const m=/\*\*Current visual design:?\*\*:?\s*([\s\S]*?)(?:\n\s*\n|$)/.exec(d);if(m)return m[1].replace(/\s+/g,' ').trim();return d.replace(/^#+.*$/gm,'').replace(/\*\*Voice:\*\*[^\n]*/g,'').replace(/\*\*/g,'').replace(/\s+/g,' ').trim();}
export function appearance(character,sequence){const v=sequence.variant&&character.variants?.[sequence.variant];if(!sequence.variant)return {...character,look:visualBrief(character)};return {...character,image:v?.image||null,color:v?.color||character.color,description:character.description+'\n'+(v?.description||''),look:[v?.description?.trim(),visualBrief(character)].filter(Boolean).join(' '),variant:sequence.variant};}
export function validateEvents(events,shot){for(const e of events){if(!Number.isFinite(e.start)||!Number.isFinite(e.end)||e.end<=e.start||e.start<0||e.end>shot.duration+.01)throw Error('Una intervención queda fuera del plano. Ajusta el inicio o alarga el plano.');}for(let i=0;i<events.length;i++)for(let k=i+1;k<events.length;k++){const a=events[i],b=events[k];if(a.start<b.end&&b.start<a.end){if(a.character===b.character)throw Error('Un personaje no puede hablar encima de sí mismo');if(!shot.allowOverlap)throw Error('Hay voces solapadas. Activa el solapamiento intencional o ajusta los inicios.');}}return events;}
export function voiceDirection(p,line){const c=p.characters.find(c=>c.id===line.character);if(line.channel==='pa')return `${c?.name||'PA'} is an OFFSCREEN public-address recording, never a visible person; nobody mouths this line.`;if(line.offscreen)return `${c?.name||'Speaker'} speaks OFFSCREEN; do not add a body or animate another person's lips.`;if(line.channel==='radio')return `${c?.name} speaks by radio; helmet stays sealed, only their talk light activates, no visible lips.`;return `${c?.name} speaks with natural lip movement.`;}

// ---- Storyboards: viñetas con boceto, fotograma generado, referencias y prompt; se convierten en capítulos.
export const zones=[['space','Espacio'],['green','Zona verde · caras'],['yellow','Zona amarilla · respirador'],['red','Zona roja · cascos'],['other','Otro']];
export const channels=[['','Directo · caras'],['radio','RADIO · casco'],['muffled','MUFFLED · respirador'],['ext','EXT · canal externo'],['pa','PA · megafonía']];
export function storyboardShot(p,id){for(const sb of p.storyboards||[])for(const s of sb.sequences||[]){const t=(s.shots||[]).find(t=>t.id===id);if(t)return {storyboard:sb,sequence:s,shot:t};}throw Error('Plano de storyboard no encontrado');}
// Prompt de imagen del plano: el explícito si existe; si no, se compone con boceto, estilo del proyecto, acción, cámara y reparto.
export function storyboardPrompt(p,sb,s,t){if(t.prompt?.trim())return t.prompt.trim();const parts=[];if(t.sketch)parts.push('Image 1 is a rough storyboard line sketch of this exact shot. Follow its framing, subject placement, relative scale and any arrow direction precisely; ignore its line style, paper texture and every annotation or label drawn on it, none of which may appear in the output.');parts.push(p.style||'');if(sb.style?.trim())parts.push(sb.style.trim());parts.push([t.action,t.camera?`Lens and camera: ${t.camera}.`:''].filter(Boolean).join(' '));const cast=(t.cast||[]).map(id=>p.characters.find(c=>c.id===id)).filter(Boolean);if(cast.length)parts.push(`Cast in this frame: ${cast.map(c=>`${c.name}: ${visualBrief(c).slice(0,500)}`).join('; ')}. Every person must match the supplied character reference sheets exactly; do not add people who are not listed.`);else parts.push('No people in this frame unless the shot description names them.');parts.push('Output one single photographic 16:9 frame: no split panels, no borders, no captions, no watermark.'+(t.avoid?` Avoid: ${t.avoid}.`:''));return parts.filter(Boolean).join('\n\n');}
// Convierte un storyboard en un capítulo editable: cada viñeta es un plano; el diálogo se reparte en el tiempo del plano; todas las voces quedan fuera de campo hasta colocar el reparto 3D.
export function storyboardToEpisode(p,sb,newId=()=>crypto.randomUUID()){const speaker=l=>{if(l.character&&p.characters.some(c=>c.id===l.character))return l.character;const who=String(l.who||'').trim().toLowerCase();return p.characters.find(c=>c.id.toLowerCase()===who||c.name.toLowerCase().split(/\s+/)[0]===who||c.name.toLowerCase()===who)?.id;};const cam=()=>({position:[4,2.5,7],target:[0,1,0],fov:45});
return {id:newId(),title:sb.title||'Capítulo desde storyboard',synopsis:sb.description||'',storyboard:sb.id,sequences:(sb.sequences||[]).map(s=>{const shots=(s.shots||[]);return {id:newId(),title:s.title||'Secuencia',location:p.locations.some(l=>l.id===s.location)?s.location:(p.locations[0]?.id||''),variant:{green:'green',yellow:'yellow',red:'red'}[shots[0]?.zone]||'',ambiencePrompt:shots.map(t=>t.sound).filter(Boolean)[0]||'',ambienceGain:.18,silent:false,cast:[],props:[],storyboardSequence:s.id,shots:shots.map(t=>{const duration=Math.max(1,Math.min(15,Number(t.duration)||5));const lines=(t.dialogue||[]).map(l=>({...l,character:speaker(l)})).filter(l=>l.character);const step=lines.length?Math.max(0,(duration-1))/lines.length:0;return {id:newId(),title:[t.code,t.title].filter(Boolean).join(' · ')||'Plano',description:[t.action,t.camera?`Cámara: ${t.camera}`:''].filter(Boolean).join('\n'),duration,camera:cam(),cameraEnd:cam(),lines:lines.map((l,i)=>({id:newId(),character:l.character,text:String(l.text||''),start:Math.min(duration-.5,Math.round((.5+i*step)*10)/10),offscreen:true,...(l.channel?{channel:l.channel}:{})})),history:[],storyboardShot:t.id,...(t.render?{storyboardRender:t.render}:{})};})};})};}
