export const variants=[['','Diseño base'],['green','Verde · ropa normal'],['yellow','Amarilla · respirador'],['red','Roja · traje espacial']];
// Texto de aspecto para prompts de imagen/vídeo: el campo `look` si existe; si no, el párrafo "Current visual design" de la descripción; si no, la descripción sin cabeceras ni el bloque de voz (que no aporta nada visual).
export function visualBrief(character){if(character.look?.trim())return character.look.trim();const d=character.description||'';const m=/\*\*Current visual design:?\*\*:?\s*([\s\S]*?)(?:\n\s*\n|$)/.exec(d);if(m)return m[1].replace(/\s+/g,' ').trim();return d.replace(/^#+.*$/gm,'').replace(/\*\*(Voice|Acting|Voice prompt):\*\*[^\n]*/g,'').replace(/\*\*/g,'').replace(/\s+/g,' ').trim();}
export function appearance(character,sequence){const v=sequence.variant&&character.variants?.[sequence.variant];if(!sequence.variant)return {...character,look:visualBrief(character)};return {...character,image:v?.image||null,color:v?.color||character.color,description:character.description+'\n'+(v?.description||''),look:[v?.description?.trim(),visualBrief(character)].filter(Boolean).join(' '),variant:sequence.variant};}
export function validateEvents(events,shot){for(const e of events){if(!Number.isFinite(e.start)||!Number.isFinite(e.end)||e.end<=e.start||e.start<0||e.end>shot.duration+.01)throw Error('Una intervención queda fuera del plano. Ajusta el inicio o alarga el plano.');}for(let i=0;i<events.length;i++)for(let k=i+1;k<events.length;k++){const a=events[i],b=events[k];if(a.start<b.end&&b.start<a.end){if(a.character===b.character)throw Error('Un personaje no puede hablar encima de sí mismo');if(!shot.allowOverlap)throw Error('Hay voces solapadas. Activa el solapamiento intencional o ajusta los inicios.');}}return events;}
export function voiceDirection(p,line){const c=p.characters.find(c=>c.id===line.character);if(line.channel==='pa')return `${c?.name||'PA'} is an OFFSCREEN public-address recording, never a visible person; nobody mouths this line.`;if(line.offscreen)return `${c?.name||'Speaker'} speaks OFFSCREEN; do not add a body or animate another person's lips.`;if(line.channel==='radio')return `${c?.name} speaks by radio; helmet stays sealed, only their talk light activates, no visible lips.`;return `${c?.name} speaks with natural lip movement.`;}

// ---- Storyboards: viñetas con boceto, fotograma generado, referencias y prompt; se convierten en capítulos.
export const zones=[['space','Espacio'],['green','Zona verde · caras'],['yellow','Zona amarilla · respirador'],['red','Zona roja · cascos'],['other','Otro']];
export const channels=[['','Directo · caras'],['radio','RADIO · casco'],['muffled','MUFFLED · respirador'],['ext','EXT · canal externo'],['pa','PA · megafonía']];
export function storyboardShot(p,id){for(const sb of p.storyboards||[])for(const s of sb.sequences||[]){const t=(s.shots||[]).find(t=>t.id===id);if(t)return {storyboard:sb,sequence:s,shot:t};}throw Error('Plano de storyboard no encontrado');}
// Prompt de imagen del plano: el explícito si existe; si no, se compone con boceto, estilo del proyecto, acción, cámara y reparto.
export function storyboardPrompt(p,sb,s,t){if(t.prompt?.trim())return t.prompt.trim();const parts=[];if(t.sketch)parts.push('Image 1 is a rough storyboard line sketch of this exact shot. Follow its framing, subject placement, relative scale and any arrow direction precisely; ignore its line style, paper texture and every annotation or label drawn on it, none of which may appear in the output.');parts.push(p.style||'');if(sb.style?.trim())parts.push(sb.style.trim());parts.push([t.action,t.camera?`Lens and camera: ${t.camera}.`:''].filter(Boolean).join(' '));const cast=(t.cast||[]).map(id=>p.characters.find(c=>c.id===id)).filter(Boolean);if(cast.length)parts.push(`Cast in this frame: ${cast.map(c=>`${c.name}: ${visualBrief(c).slice(0,500)}`).join('; ')}. Every person must match the supplied character reference sheets exactly; do not add people who are not listed.`);else parts.push('No people in this frame unless the shot description names them.');parts.push('Output one single photographic 16:9 frame: no split panels, no borders, no captions, no watermark.'+(t.avoid?` Avoid: ${t.avoid}.`:''));return parts.filter(Boolean).join('\n\n');}
// Convierte un storyboard en un capítulo editable: cada viñeta es un plano; el diálogo se reparte en el tiempo del plano; todas las voces quedan fuera de campo hasta colocar el reparto 3D.
export function storyboardToEpisode(p,sb,newId=()=>crypto.randomUUID()){const speaker=l=>{if(l.character&&p.characters.some(c=>c.id===l.character))return l.character;const who=String(l.who||'').trim().toLowerCase();return p.characters.find(c=>c.id.toLowerCase()===who||c.name.toLowerCase().split(/\s+/)[0]===who||c.name.toLowerCase()===who)?.id;};const cam=()=>({position:[4,2.5,7],target:[0,1,0],fov:45});
return {id:newId(),title:sb.title||'Capítulo desde storyboard',synopsis:sb.description||'',storyboard:sb.id,sequences:(sb.sequences||[]).map(s=>{const shots=(s.shots||[]);return {id:newId(),title:s.title||'Secuencia',location:p.locations.some(l=>l.id===s.location)?s.location:(p.locations[0]?.id||''),variant:{green:'green',yellow:'yellow',red:'red'}[shots[0]?.zone]||'',ambiencePrompt:shots.map(t=>t.sound).filter(Boolean)[0]||'',ambienceGain:.18,silent:false,cast:[],props:[],storyboardSequence:s.id,shots:shots.map(t=>{const duration=Math.max(1,Math.min(15,Number(t.duration)||5));const lines=(t.dialogue||[]).map(l=>({...l,character:speaker(l)})).filter(l=>l.character);const step=lines.length?Math.max(0,(duration-1))/lines.length:0;return {id:newId(),title:[t.code,t.title].filter(Boolean).join(' · ')||'Plano',description:[t.action,t.camera?`Cámara: ${t.camera}`:''].filter(Boolean).join('\n'),duration,camera:cam(),cameraEnd:cam(),lines:lines.map((l,i)=>({id:newId(),character:l.character,text:String(l.text||''),start:Math.min(duration-.5,Math.round((.5+i*step)*10)/10),offscreen:true,...(l.channel?{channel:l.channel}:{})})),history:[],storyboardShot:t.id,...(t.render?{storyboardRender:t.render}:{})};})};})};}
// Rellena una secuencia ya existente con todas las viñetas de un storyboard (un plano por viñeta, en orden). Conserva el id de los planos que ya venían de la misma viñeta; el reparto se coloca en semicírculo y los hablantes que están en él dejan de ir fuera de campo.
export function storyboardToSequence(p,sb,seq,newId=()=>crypto.randomUUID()){const physical=id=>p.characters.some(c=>c.id===id&&c.kind!=='voice');const shots=(sb.sequences||[]).flatMap(s=>s.shots||[]);const ids=[...new Set(shots.flatMap(t=>t.cast||[]))].filter(physical);const cast=ids.map((character,i)=>{const a=Math.PI*(i+.5)/ids.length;return {character,x:Math.round(Math.cos(a)*300)/100,z:Math.round(-Math.sin(a)*200)/100,yaw:0};});const draft=storyboardToEpisode(p,{...sb,sequences:[{id:sb.id,title:seq.title,location:(sb.sequences||[]).find(s=>s.location)?.location,shots}]},newId).sequences[0];const old=new Map((seq.shots||[]).filter(t=>t.storyboardShot).map(t=>[t.storyboardShot,t]));return {...seq,location:draft.location,cast,storyboard:sb.id,shots:draft.shots.map(t=>{const prev=old.get(t.storyboardShot);const lines=t.lines.map(l=>({...l,offscreen:!ids.includes(l.character)}));return prev?{...t,id:prev.id,history:prev.history||[],lines:lines.map((l,k)=>({...l,id:prev.lines?.[k]?.id||l.id}))}:{...t,lines};})};}

// ---- Producción por bloques (PROCESO.md). Funciones puras, sin dependencias de Node: también se cargan en el navegador.
// Escalera de óptica por FOV horizontal (grados) con su equivalente en mm de paso completo y una frase observable, no metadatos de lente.
export const FOV_LADDER=[
  {mm:70,h:28.8,text:'long lens: background compressed close behind the subject, shallow focus isolates the face, no perspective stretch'},
  {mm:50,h:39.6,text:'normal lens: natural proportions, background at its true distance, no distortion'},
  {mm:35,h:54.4,text:'moderate wide: straight verticals, whole bodies and the near set readable, faces undistorted at arm\'s length'},
  {mm:28,h:65.5,text:'wide: the near foreground reads slightly larger, the set stays visible to the frame edges, straight lines stay straight'},
  {mm:24,h:73.7,text:'wide: immediate foreground large and close, deep focus, the set spreads to every edge, verticals stay rectilinear'},
  {mm:18,h:90,text:'very wide rectilinear: extreme depth, foreground exaggerated, straight lines stay straight out to the edges'}];
// Three.js guarda el FOV vertical; el modelo entiende mejor el horizontal.
export function horizontalFov(vertical,aspect=16/9){const v=vertical*Math.PI/180;return 2*Math.atan(Math.tan(v/2)*aspect)*180/Math.PI;}
export function opticsAnchor(vertical,aspect=16/9){const h=horizontalFov(vertical,aspect);let best=FOV_LADDER[0];for(const a of FOV_LADDER)if(Math.abs(a.h-h)<Math.abs(best.h-h))best=a;return {...best,h:Math.round(h)};}
export function opticsLine(vertical,aspect=16/9){const a=opticsAnchor(vertical,aspect);return `${a.h}° horizontal field of view (about ${a.mm} mm full-frame equivalent), ${a.text}. One lens for the whole take; no zoom or focal drift.`;}
// Reloj real del modelo: ~4 palabras por segundo, más los silencios escritos, más 1 s de cola limpia. Devuelve los segundos que necesita el diálogo del bloque.
export function dialogueBudget(lines,{rate=4,tail=1}={}){let end=0;for(const l of lines||[]){const words=String(l.spokenText||l.text||'').trim().split(/\s+/).filter(Boolean).length;end=Math.max(end,(Number(l.start)||0)+words/rate);}return lines?.length?end+tail:0;}
// Dónde cae un punto del set en el cuadro de una cámara: lado (left/centre/right), profundidad relativa y si entra en el campo horizontal.
export function framePosition(camera,point,aspect=16/9){const [cx,cy,cz]=camera.position,[tx,ty,tz]=camera.target;let fx=tx-cx,fz=tz-cz;const fl=Math.hypot(fx,fz)||1;fx/=fl;fz/=fl;const rx=-fz,rz=fx;const dx=point[0]-cx,dz=point[2]-cz;const depth=dx*fx+dz*fz,lateral=dx*rx+dz*rz;const angle=Math.atan2(lateral,Math.max(depth,1e-6))*180/Math.PI,half=horizontalFov(camera.fov,aspect)/2;const side=Math.abs(angle)<half/3?'centre':angle>0?'right':'left';return {side,depth:Math.hypot(dx,dz),angle,visible:depth>0&&Math.abs(angle)<half};}
function depthLabel(d,all){if(all.length<2)return 'midground';const sorted=[...all].sort((a,b)=>a-b);if(d<=sorted[0]+.01)return 'foreground';if(d>=sorted.at(-1)-.01)return 'background';return 'midground';}
// Nombre corto en mayúsculas para el prompt (primera palabra del nombre, como en los prompts aceptados).
export function shortName(project,id){const c=project?.characters?.find(c=>c.id===id);return String(c?.name||id).trim().split(/\s+/)[0].toUpperCase();}
// Nombre fijo del asset de personaje en el registro.
export function tagFor(id,variant){return `${String(id).toUpperCase()}_${String(variant||'base').toUpperCase()}`;}
export function findAsset(registry,pred){return Object.entries(registry?.assets||{}).find(([,a])=>pred(a));}
// Referencias del bloque, siempre por tag: imágenes de los personajes visibles, la foto de grupo si existe, la plate del ambiente y las voces de quien habla en cuadro.
export function resolveRefs({sequence,block,registry,shots},{maxImages=8}={}){const assets=registry?.assets||{},errors=[];const need=tag=>{const a=assets[tag];if(!a)errors.push(`Falta en el registro: ${tag}`);else if(a.status!=='approved')errors.push(`Asset sin aprobar: ${tag}`);return a;};const cast=block.cast||sequence.cast.map(a=>a.character);const images=cast.map(id=>{const tag=tagFor(id,sequence.variant);const a=need(tag);return {tag,role:'character',character:id,file:a?.file,descriptor:a?.descriptor,proxy:a?.proxy};});const group=findAsset(registry,a=>a.kind==='group'&&a.status==='approved'&&a.variant===sequence.variant&&(a.members||[]).every(m=>images.some(i=>i.tag===m)));if(group)images.push({tag:group[0],role:'group',file:group[1].file,descriptor:group[1].descriptor});const plate=findAsset(registry,a=>a.kind==='location'&&(a.location===sequence.location||(a.aliases||[]).includes(sequence.location)));if(plate){if(plate[1].status!=='approved')errors.push(`Asset sin aprobar: ${plate[0]}`);images.push({tag:plate[0],role:'location',file:plate[1].file,descriptor:plate[1].descriptor});}else errors.push(`Falta la plate del ambiente ${sequence.location} en el registro`);for(const tag of block.extraRefs||[]){const a=need(tag);images.push({tag,role:a?.kind||'extra',file:a?.file,descriptor:a?.descriptor});}if(images.length>maxImages)errors.push(`Demasiadas imágenes de referencia: ${images.length} > ${maxImages}`);const speakers=[...new Set(spokenLines(block,shots).map(l=>l.character))];const audios=speakers.map(id=>{const tag=`${String(id).toUpperCase()}_VOICE`;const a=need(tag);return {tag,character:id,file:a?.file,descriptor:a?.descriptor};});return {images,audios,video:'motion.mp4',errors};}
// Líneas que sí genera el modelo: en cuadro y con cuerpo. PA, fuera de campo y canal externo se producen aparte y se montan en post (R08).
export function spokenLines(block,shots){return (block.parts||[]).flatMap(part=>(part.lines||[]).filter(l=>!l.offscreen&&l.channel!=='pa'&&l.channel!=='ext').map(l=>({...l,start:part.at+l.start})));}
export function offscreenLines(block,shots){return (block.parts||[]).flatMap(part=>(part.lines||[]).filter(l=>l.offscreen||l.channel==='pa'||l.channel==='ext').map(l=>({...l,start:part.at+l.start})));}
const CHANNEL_TEXT={radio:'restrained helmet radio voice',muffled:'voice muffled through a respirator',ext:'external channel',pa:'ship PA',direct:'natural voice, lips visible'};
export const EMOTION_WORDS=['sad','sadly','sadness','angry','angrily','anger','afraid','scared','fear','fearful','happy','happily','nervous','nervously','excited','worried','terrified','furious'];
export function forbiddenEmotionWords(text){const found=new Set();for(const w of EMOTION_WORDS)if(new RegExp(`\\b${w}\\b`,'i').test(text))found.add(w);return [...found];}
// Solo se admiten tres negativos literales; todo lo demás se escribe como resultado (R21).
export const NEGATIVE_WHITELIST=['Do not add any other words','never duplicate those views as extra people','No empty establishing frame','no zoom or focal drift'];
export function strayNegatives(text){const out=[];text=String(text).replace(/<d>[\s\S]*?<\/d>/g,'');for(const m of text.matchAll(/\b(no|never|do not|don't)\b[^.;\n]*/gi)){const s=m[0].trim();if(!NEGATIVE_WHITELIST.some(w=>s.toLowerCase().startsWith(w.toLowerCase())))out.push(s);}return out;}
export function cameraLine(shot){const cov=(shot.coverage||[]).filter(c=>c.camera);if(cov.length>1)return `Video 1 cuts between ${cov.length} locked-off camera stations (cuts at ${cov.slice(1).map(c=>c.start.toFixed(1)+'s').join(', ')}); follow every cut and every station exactly. Every camera move stays one continuous move.`;const a=shot.camera,b=shot.cameraEnd||shot.camera;const same=['position','target'].every(k=>a[k].every((v,i)=>Math.abs(v-b[k][i])<.01));const height=a.position[1].toFixed(1);if(same)return `Locked-off camera at ${height} m above the floor, exactly as in Video 1; the operator does not move.`;const d0=Math.hypot(a.target[0]-a.position[0],a.target[2]-a.position[2]),d1=Math.hypot(b.target[0]-b.position[0],b.target[2]-b.position[2]);const parts=[];if(Math.abs(d1-d0)>.3)parts.push(d1<d0?'ending closer to the subject':'ending farther from the subject');if(Math.abs(b.position[1]-a.position[1])>.2)parts.push(b.position[1]>a.position[1]?'rising':'lowering');return `One continuous handheld move exactly as in Video 1${parts.length?', '+parts.join(' and '):''}: operator on foot, small breathing sway, one unbroken take from first frame to last.`;}
// Frase de primer fotograma: cada cuerpo del reparto con su lado de cuadro, su profundidad y el landmark más cercano del mapa.
export function firstFrameLine({sequence,shot,project,map}){const cast=sequence.cast||[];if(!cast.length)return 'The first visible frame already shows the empty set exactly as framed in Video 1 frame 0. No empty establishing frame is needed: the set itself is the subject.';const cam=(shot.coverage||[]).find(c=>c.camera&&c.start<=0.01)?.camera||shot.camera;const pos=cast.map(a=>framePosition(cam,[a.x,0,a.z]));const depths=pos.map(p=>p.depth);const names=cast.map((a,i)=>{const p=pos[i];const lm=nearestLandmark(map,[a.x,a.z]);return `${shortName(project,a.character)} ${p.visible?`frame-${p.side}, ${depthLabel(p.depth,depths)}`:'just outside the frame edge'}${lm?`, ${lm}`:''}`;});return `The first visible frame already contains ${names.join('; ')}, in the positions of Video 1 frame 0. Exactly ${cast.length} ${cast.length===1?'person':'people'} visible. No empty establishing frame.`;}
export function nearestLandmark(map,xz){const items=map?.landmarks||[];let best=null;for(const l of items)for(const p of l.positions||[]){const d=Math.hypot(p[0]-xz[0],p[1]-xz[1]);if(!best||d<best.d)best={d,label:l.label};}return best?best.d<3.5?`${best.label}`:null:null;}
// Texto de interpretación por personaje: la prosa de la escena si existe; si no, los campos estructurados.
export function actingText(scene,characterIds,project){const out=[];for(const id of characterIds){const c=scene?.characters?.[id];if(!c)continue;const name=shortName(project,id);if(c.paragraph)out.push(c.paragraph.trim());else{const bits=[];if(c.objective)bits.push(`${name} wants to ${c.objective}`);if(c.obstacle)bits.push(`the obstacle is ${c.obstacle}`);if(c.tactics?.length)bits.push(`tactics in order: ${c.tactics.join(', ')}`);if(c.business)bits.push(`hands busy with ${c.business}`);if(c.beats?.length)bits.push(`visible beats: ${c.beats.join('; ')}`);if(c.tic?.trigger)bits.push(`${c.tic.trigger}: ${c.tic.action}`);if(c.mask_crack)bits.push(c.mask_crack);out.push(bits.join('. ')+'.');}}return out.join('\n');}
// Parser mínimo de MAPA.md: el bloque ```prompt``` es el párrafo que se pega; el bloque ```json landmarks``` da posiciones locales por landmark.
export function parseMapa(md){const prompt=/```prompt\s*\n([\s\S]*?)```/.exec(md||'')?.[1]?.trim()||'';const lm=/```json landmarks\s*\n([\s\S]*?)```/.exec(md||'')?.[1];let landmarks=[];try{landmarks=lm?JSON.parse(lm):[];}catch{landmarks=[];}const axis=/^Eje de 180°:\s*(.+)$/m.exec(md||'')?.[1]?.trim()||'';const side=/^Lado de cámara:\s*(.+)$/m.exec(md||'')?.[1]?.trim()||'';return {prompt,landmarks,axis,side};}
const GRAVITY_TEXT={normal:'Gravity normal: boots land with weight, straps and cables hang straight down, a container only moves with hands on it, dropped objects fall.',half:'Half gravity: long slow strides, bodies settle softly, straps sway slowly, anything let go drifts down instead of dropping.',zero:'Zero gravity: every body is anchored by one hand or a boot hook, torsos float free of the floor, hair and straps drift, anything let go stays where it is or drifts slowly.',changing:'Gravity is changing during this block: it starts as the previous block ended and settles into the state written in the timing, with straps, bodies and loose objects answering the change together.'};
const SOUND_TEXT={red:'Native dialogue with the assigned reference voices, intimate helmet-radio intelligibility with subtle radio filtering. Under it, a low continuous ship rumble transmitted through the structure and quiet suit handling. Vacuum outside the helmets: every sound arrives through the suit or the structure.',yellow:'Native dialogue with the assigned reference voices, muffled through respirators but intelligible. Thin pressurised-corridor air: ventilation hiss, distant machinery, close cloth and equipment handling.',green:'Native dialogue with the assigned reference voices, natural room voices with lips visible. Room tone of an old ship interior: ventilation, ticking metal, close handling of objects.'};
export function actionTiming({block,shots,project}){const lines=[];const name=id=>shortName(project,id);for(const part of block.parts||[]){const t=shots[part.shot];if(!t)throw Error(`Plano desconocido en el plan: ${part.shot}`);const from=part.at,to=part.at+(part.to-part.from);const action=(t.action||'').trim()||describeTasks(t,project)||'The same station continues.';lines.push(`[${from.toFixed(2)}s–${to.toFixed(2)}s] ${action}`);for(const l of part.lines||[]){const at=(part.at+l.start).toFixed(2);const off=l.offscreen||l.channel==='pa'||l.channel==='ext';if(off)lines.push(`${at}s: an offscreen ${l.channel==='pa'?'PA announcement':'radio line'} from ${name(l.character)} plays over the helmets (audio laid in post, not generated here); the crew hear it and keep working, nobody mouths it.`);else lines.push(`At approximately ${at}s, ${name(l.character)}, ${CHANNEL_TEXT[l.channel||'direct']||CHANNEL_TEXT.direct}, says exactly: <d>[English] ${(l.spokenText||l.text).trim()}</d>`);}}return lines;}
function describeTasks(t,project){const tasks=t.staging?.tasks||{};const bits=Object.entries(tasks).map(([id,task])=>{const n=shortName(project,id);return task&&task!=='idle'?`${n} is already ${task}`:`${n} keeps working at the same spot, hands on the nearest strap or latch`;});return bits.join('; ')+(bits.length?'.':'');}
// Genera el prompt del bloque en orden fijo. Devuelve el texto (con huecos [[ACTING]] y [[LOCAL]] si la escena no los aporta), las referencias resueltas y avisos.
export function blockPrompt({project,sequence,shots,block,registry,map,scene,mode='block'}){const refs=resolveRefs({sequence,block,registry,shots});const warnings=[...refs.errors];const cast=block.cast||sequence.cast.map(a=>a.character);const nameOf=id=>shortName(project,id);const duration=block.duration??Math.ceil(block.length||5);const requested=Math.max(5,Math.ceil(duration));const spoken=spokenLines(block,shots);const budget=dialogueBudget(spoken);if(spoken.length&&budget>duration-1+.01)warnings.push(`Diálogo de ${budget.toFixed(1)} s no cabe en ${duration} s − 1 s de cola (R12)`);const first=shots[block.parts?.[0]?.shot];if(!first)throw Error('El bloque no tiene planos');const zone=sequence.variant||'green';const subj=[];let n=0;for(const r of refs.images){n++;if(r.role==='character')subj.push(`<Subject ${n}> ${nameOf(r.character)} is Image ${n} (@${r.tag}): ${r.descriptor||'[[DESCRIPTOR]]'} ${r.proxy?r.proxy+' proxy':'Its proxy'} in Video 1.`.replace(/\s+/g,' ').trim());else if(r.role==='group')subj.push(`<Subject ${n}> Image ${n} (@${r.tag}) shows ${(r.descriptor||'the same people together in this set')}; it fixes how they read next to each other, never adds people.`);else if(r.role==='location')subj.push(`<Subject ${n}> Image ${n} (@${r.tag}): ${r.descriptor||'[[DESCRIPTOR]]'}`);else subj.push(`<Subject ${n}> Image ${n} (@${r.tag}): ${r.descriptor||'[[DESCRIPTOR]]'}`);}
subj.push('<Video 1> is the approved 3D guide for this exact segment: framing, camera path, actor positions, paths, prop contact, gravity state and speech timing. Each proxy becomes exactly one person from the first frame.');refs.audios.forEach((a,i)=>subj.push(`<Audio ${i+1}> is the voice identity reference for ${nameOf(a.character)} only; not a recording to paste.`));
const summary=`[reference generation${refs.audios.length?' + audio reference':''}] ${registry?.summary||'Photorealistic live-action drama.'} ${mode==='master'?`MASTER shot of ${sequence.title||sequence.location}: a one-second wide establishing frame, nobody speaks, blocking frozen as in Video 1.`:`Segment ${block.id} of scene ${first.sourceScene||sequence.title||''} (${sequence.location}, ${zone} zone, gravity ${first.gravity||sequence.gravity||'normal'}).`} SINGLE CONTINUOUS TAKE matching Video 1. Exactly ${cast.length} ${cast.length===1?'person':'people'} visible${offscreenLines(block,shots).length?'; every offscreen voice stays offscreen':''}.`;
const retention=`Character images: fully preserve each person's identity, suit and helmet state; each sheet shows several views of ONE person, never duplicate those views as extra people. Location image: geometry, materials, light and atmosphere only, never a frozen camera angle. Video 1: preserve actor locations, paths, prop contact, gravity state and every camera move; replace mannequin geometry with real human anatomy from the first frame; the guide's labels, proxy mouths and chest markers are absent, helmets carry only a small amber talk light. Audio references: each one only for its assigned speaker's timbre. Generate dialogue and physical delivery together, tiny timing adjustments allowed for natural speech, without omissions.`;
const map_=map?.prompt?map.prompt:'[[LOCATION MAP]]';const axis=[map?.side?`Camera side: ${map.side}.`:'',map?.axis?`The 180° line is ${map.axis}; the camera stays on its side of that line for the whole take.`:''].filter(Boolean).join(' ');
const acting=mode==='master'?'Nobody speaks and nobody moves: the crew hold the blocking of Video 1 frame 0 for the whole shot, breathing only, hands on their tasks.':scene?actingText(scene,cast,project):'';const local=mode==='master'?'The whole set is visible edge to edge as in Video 1; the crew are small in frame.':(scene?.local_constraints||[]).join(' ');
const light=registry?.lighting?.[zone]||registry?.lighting?.default||'[[LIGHTING]]';
const detailed=[`LOCATION MAP: ${map_}${axis?' '+axis:''}`,`FIRST FRAME: ${firstFrameLine({sequence,shot:first,project,map})}`,`OPTICS: ${opticsLine(first.camera.fov)}`,`CAMERA: ${cameraLine(first)}`,`ACTION TIMING:\n${actionTiming({block,shots,project}).join('\n')}${spoken.length?`\nFinish all words by ${(duration-1).toFixed(1)}s; the last second is clean tail. Do not add any other words.`:'\nNobody speaks in this segment.'}`,`CHARACTER ACTING: ${acting||'[[ACTING]]'}`,`PHYSICS: ${GRAVITY_TEXT[first.gravity||sequence.gravity]||GRAVITY_TEXT.normal}${first.staging?.potatoes?` Seed potatoes: ${first.staging.potatoes==='none'?'all containers sealed, none visible':first.staging.potatoes}.`:''}`,`LIGHTING: ${light}`,`STYLE: ${project.style||''}`,`QUALITY: Photorealistic from frame zero; identities, suits and set consistent across the whole take; textured materials at believable scale; clean rendering of visors, straps and practical lights.`,`POSITIVE CONSTRAINTS: ${zone==='red'?'Visors stay closed, dark and reflective in every frame; only the speaking character keys the radio, shown by a small amber light. ':zone==='yellow'?'Respirators stay on in every frame; eyes visible above them. ':''}Listeners keep their hands on their task. Eyes lead the head and settle on people, props or landmarks; nobody looks at the lens. Every person 100% matches their reference in every frame. ${local||'[[LOCAL]]'}`].join('\n');
const prompt=`subject_definitions:\n${subj.join('\n')}\nsummary:\n${summary}\nretention_analysis:\n${retention}\ndetailed_description:\n${detailed}\noverall_soundscape:\n${SOUND_TEXT[zone]||SOUND_TEXT.green}${refs.audios.map(a=>a.descriptor?` ${nameOf(a.character)}'s voice: ${a.descriptor}`:'').join('')}\nnon_diegetic_music:\nNone.`;
const emo=forbiddenEmotionWords(acting+' '+local);if(emo.length)warnings.push(`Palabras de emoción en la interpretación: ${emo.join(', ')} (skill interpretacion)`);const neg=strayNegatives(detailed.split('\n').filter(l=>!l.startsWith('STYLE:')).join('\n'));if(neg.length)warnings.push(`Negativos fuera de la lista blanca: ${neg.slice(0,3).join(' | ')}${neg.length>3?' …':''}`);
return {prompt,refs,warnings,duration,requested,budget};}

// Prompt de un bloque en modo «fotograma» (image-to-video): el fotograma del storyboard ES el primer fotograma; no hay vídeo guía ni hojas adjuntas, así que la identidad se sostiene con los descriptores del registro. Los huecos [[CAMERA]] y [[ACTION]] se rellenan con la skill director-h3 salvo que el plano traiga cameraEn/actionEn.
export function framePrompt({project,sequence,shots,block,registry,map,scene,cast=[]}){const warnings=[];const part=block.parts?.[0];const t=shots[part?.shot];if(!t)throw Error('El bloque no tiene planos');if((block.parts||[]).length>1)warnings.push('Modo fotograma: el bloque tiene más de un plano; solo el primero tiene fotograma inicial');const image=t.storyboardRender||null;if(!image)warnings.push(`El plano ${t.title} no tiene fotograma de storyboard`);const duration=block.duration??Math.ceil(block.length||5);const requested=Math.max(5,Math.ceil(duration));const spoken=spokenLines(block,shots);const budget=dialogueBudget(spoken);if(spoken.length&&budget>duration-1+.01)warnings.push(`Diálogo de ${budget.toFixed(1)} s no cabe en ${duration} s − 1 s de cola (R12)`);
const assets=Object.entries(registry?.assets||{});const person=id=>assets.find(([,a])=>a.kind==='character'&&a.character===id&&!a.variant)||assets.find(([,a])=>a.kind==='character'&&a.character===id);const voice=id=>assets.find(([,a])=>a.kind==='voice'&&a.character===id)?.[1];const nameOf=id=>characterName(registry,project,id);
const people=cast.map(id=>{const e=person(id);if(!e)warnings.push(`Sin entrada de registro para ${id}`);else if(e[1].status!=='approved')warnings.push(`Tag sin aprobar: ${e[0]}`);return e?e[1].descriptor||'[[DESCRIPTOR]]':`${nameOf(id)}: [[DESCRIPTOR]]`;});
const lines=[];for(const p of block.parts||[])for(const l of p.lines||[]){const at=(p.at+l.start).toFixed(2);if(l.offscreen)lines.push(`${at}s: ${nameOf(l.character)} is heard offscreen; nobody in frame mouths the words.`);else lines.push(`At approximately ${at}s, ${nameOf(l.character)} says exactly: <d>[English] ${(l.spokenText||l.text).trim()}</d>`);}
const axis=[map?.side?`Camera side: ${map.side.replace(/\.+$/,'')}.`:'',map?.axis?`The 180° line is ${map.axis.replace(/\.+$/,'')}; the camera stays on its side of that line.`:''].filter(Boolean).join(' ');const acting=scene?actingText(scene,cast,project):'';const local='';const light=registry?.lighting?.default||'[[LIGHTING]]';
const summary=`[image-to-video, first frame supplied${spoken.length?', dialogue':''}] ${registry?.summary||'Photorealistic live-action drama.'} Shot ${String(t.title).split(' · ')[0]}. The supplied image IS frame zero: the take starts exactly on it and moves on in one continuous take. Exactly ${cast.length} ${cast.length===1?'person':'people'} in the scene${cast.length?`: ${cast.map(nameOf).join(', ')}`:''}.`;
const retention='Keep every face, beard, hair, costume, animal and prop exactly as in the first frame for the whole take. Nobody new appears unless the action says so; nobody is duplicated; nobody changes clothes or weapons. Keep the location, the light and the colour of the first frame.';
const detailed=[`LOCATION MAP: ${map?.prompt||'[[LOCATION MAP]]'}${axis?' '+axis:''}`,'FIRST FRAME: the supplied image, unchanged.',`CAMERA: ${t.cameraEn||'[[CAMERA]]'}`,`ACTION TIMING:\n[0.00s–${duration.toFixed(2)}s] ${t.actionEn||'[[ACTION]]'}${lines.length?'\n'+lines.join('\n'):''}${spoken.length?`\nFinish all words by ${(duration-1).toFixed(1)}s; the last second is clean tail. Do not add any other words.`:'\nNobody speaks in this shot.'}`,`PEOPLE: ${people.join(' || ')||'No people in frame.'}`,`CHARACTER ACTING: ${acting||'[[ACTING]]'}`,'PHYSICS: Real weight: feet sink into soft mud and crack frozen ruts, breath steams, cloth and gear move with the body; any animal already in the first frame shifts its weight and blows.',`LIGHTING: ${light}`,`STYLE: ${registry?.summary||''}`,'QUALITY: Photorealistic from frame zero; identities, costumes and animals consistent across the whole take; natural motion blur; no morphing.',`POSITIVE CONSTRAINTS: Eyes lead the head and settle on people or landmarks; nobody looks at the lens. Only the people and animals of the first frame appear; nobody enters the frame unless the action says so. Every person 100% matches the first frame in every frame. [[LOCAL]]`].join('\n');
const sound=[sequence.ambiencePrompt||'Natural exterior sound.',...[...new Set(spoken.map(l=>l.character))].map(id=>voice(id)?.descriptor?`${nameOf(id)}'s voice: ${voice(id).descriptor}`:'')].filter(Boolean).join(' ');
const prompt=`summary:\n${summary}\nretention_analysis:\n${retention}\ndetailed_description:\n${detailed}\noverall_soundscape:\n${sound}\nnon_diegetic_music:\nNone.`;
const emo=forbiddenEmotionWords(acting+' '+local);if(emo.length)warnings.push(`Palabras de emoción en la interpretación: ${emo.join(', ')} (skill interpretacion)`);
return {prompt,image,warnings,duration,requested,budget,names:cast.map(nameOf)};}

// ---- Escaleta: secuencias en orden con número, minutos y una carátula (imagen) por secuencia.
export function outlineSequence(p,id){for(const e of p.episodes||[])for(const s of e.sequences||[])if(s.id===id)return {episode:e,sequence:s};throw Error('Secuencia no encontrada');}
export function outline(p){const rows=[];let n=0,start=0;for(const e of p.episodes||[])for(const s of e.sequences||[]){n++;const minutes=Number(s.minutes)||0;rows.push({episode:e,sequence:s,number:n,code:String(n).padStart(2,'0'),minutes,start});start+=minutes;}return rows;}
// Prompt de la carátula: el explícito de la secuencia tal cual; si no, estilo del proyecto, título y texto de escaleta, y un solo fotograma 16:9 sin texto.
export const COVER_TAIL='One single cinematic 16:9 film still. No text, no captions, no borders, no watermark.';
export function coverPrompt(p,e,s){if(s.coverPrompt?.trim())return s.coverPrompt.trim();return [p.style||'',`Key image for the sequence "${s.title}"${e?.title?` (${e.title})`:''}${s.text?': '+s.text:'.'}`,COVER_TAIL].filter(Boolean).join('\n\n');}


// ---- Copia para el móvil (PWA de solo lectura). El service worker (sw.js) y la página movil.html usan estas reglas; aquí viven para poder probarlas.
export const CACHES={shell:'rodaje-shell-v1',data:'rodaje-datos-v1'};
const FILE_RE=/^(?!\/)(?!.*(^|\/)\.\.(\/|$))[\w][\w ./()+-]*\.(png|jpe?g|webp|gif|mp4|webm|wav|mp3|ogg|glb|gltf|fbx|json|md|srt)$/i;
// Ficheros relativos que referencia un proyecto (cualquier cadena con extensión de imagen, audio, vídeo, 3D o datos). Se ignoran rutas absolutas, URLs y escapes con «..».
export function projectFiles(p){const out=new Set();(function walk(o){if(typeof o==='string'){if(FILE_RE.test(o))out.add(o);}else if(o&&typeof o==='object')Object.values(o).forEach(walk);})(p);return [...out].sort();}
// Especificadores de los imports estáticos de un módulo ES (import … from 'x', import 'x', export … from 'x'); no incluye import() dinámicos.
export function moduleImports(source){const out=[],re=/\b(?:import|export)\s*(?:[\w*{}\s,$]*?\s*from\s*)?['"]([^'"]+)['"]/g;let m;while((m=re.exec(source)))if(!out.includes(m[1]))out.push(m[1]);return out;}
// Resuelve un especificador a la ruta que pedirá el navegador: primero el import map (clave exacta o prefijo acabado en «/»), luego rutas relativas o absolutas; un nombre suelto desconocido devuelve null.
export function resolveModule(spec,from,imports={}){if(imports[spec])return imports[spec];for(const [k,v] of Object.entries(imports))if(k.endsWith('/')&&spec.startsWith(k))return v+spec.slice(k.length);if(/^(\.{1,2})?\//.test(spec))return new URL(spec,'http://x'+from).pathname;return null;}
// Estrategia por petición: escrituras siempre a red; librerías inmutables (three, y_bot) primero de caché; el resto primero de red y, sin servidor, de la copia guardada.
export function offlineRoute(pathname,method='GET'){if(method!=='GET'&&method!=='HEAD')return 'network';if(pathname.startsWith('/three/')||pathname.startsWith('/assets/'))return 'cache-first';return 'network-first';}
export function cacheName(pathname){return pathname.startsWith('/api/')?CACHES.data:CACHES.shell;}
// Clave de caché: la página principal se guarda una sola vez sin importar la ruta abierta (?project=…&view=…); el resto conserva la query (proyecto y fichero).
export function cacheKey(url){const u=typeof url==='string'?new URL(url,'http://x'):url;if(u.pathname==='/'||u.pathname==='/index.html')return '/';return u.pathname+u.search;}
export function assetUrl(project,file){return '/api/asset?project='+project+'&file='+encodeURIComponent(file);}
// Peticiones GET que la app hace al recorrer un proyecto: sus datos, el estado de cada plano (vista de estudio) y todos sus ficheros.
export function projectRequests(id,p){const shots=(p.episodes||[]).flatMap(e=>e.sequences||[]).flatMap(s=>s.shots||[]);return ['/api/state','/api/project?id='+id,...shots.map(t=>'/api/shot-state?project='+id+'&shot='+t.id),...projectFiles(p).map(f=>assetUrl(id,f))];}

// ---------- Pendientes (tablero kanban) ----------
// Un pendiente es un fallo de guion, una decisión abierta o una tarea. Vive en p.issues; el orden del array es el orden dentro de cada columna.
export const ISSUE_STATES=[['abierto','Pendiente'],['en-curso','En curso'],['cerrado','Cerrado']];
export const ISSUE_SEVERITIES=[['grave','Grave'],['medio','Medio'],['ritmo','Ritmo'],['nota','Nota']];
export function issueBoard(p){const by=Object.fromEntries(ISSUE_STATES.map(([k])=>[k,[]]));for(const i of p.issues||[])(by[i.status]||by.abierto).push(i);return ISSUE_STATES.map(([key,label])=>({key,label,items:by[key]}));}
// Mueve un pendiente a una columna; con beforeId lo deja delante de ese otro, si no al final de la columna. Marca la fecha de cierre al entrar en «cerrado».
export function moveIssue(p,id,status,beforeId,now=()=>new Date().toISOString()){const list=p.issues||(p.issues=[]);if(!ISSUE_STATES.some(([k])=>k===status))throw Error('Estado no válido');const i=list.findIndex(x=>x.id===id);if(i<0)throw Error('Pendiente no encontrado');if(beforeId===id)return false;const [item]=list.splice(i,1);const was=item.status;item.status=status;if(status==='cerrado'){if(was!=='cerrado')item.closed=now();}else delete item.closed;let at=beforeId?list.findIndex(x=>x.id===beforeId):-1;if(at<0){at=list.length;for(let k=list.length-1;k>=0;k--)if(list[k].status===status){at=k+1;break;}}list.splice(at,0,item);return true;}
// Lee un análisis crítico en Markdown: «**A2. Título.** texto» bajo «### Graves/Medios/Ritmo» son pendientes abiertos; «- **C14. Título.** texto» bajo «## Cerrado» son cerrados.
export function parseIssues(md){const out=[];let closed=false,severity='medio';for(const raw of String(md||'').split('\n')){const line=raw.trimEnd();if(/^## /.test(line)){closed=/cerrad/i.test(line);continue;}if(/^### /.test(line)){severity=/grave/i.test(line)?'grave':/ritmo/i.test(line)?'ritmo':/medio/i.test(line)?'medio':'nota';continue;}const m=/^(?:- )?\*\*([A-Z]\d+)\. (.+?)\.?\*\*\s*(.*)$/.exec(line);if(m){out.push({code:m[1],title:m[2].trim(),text:m[3].trim(),status:closed?'cerrado':'abierto',severity:closed?'nota':severity});continue;}if(out.length&&line&&!/^#/.test(line)&&!/^---$/.test(line)){const last=out[out.length-1];if(!/^(?:- )?\*\*/.test(line))last.text+=(last.text?'\n':'')+line;}}return out;}
// Vuelca pendientes con código en el proyecto: los nuevos se añaden; los existentes actualizan título, texto y gravedad. El estado del documento solo manda cuando dice «cerrado».
export function upsertIssues(p,items,{newId=()=>crypto.randomUUID(),now=()=>new Date().toISOString()}={}){const list=p.issues||(p.issues=[]);let added=0,updated=0;for(const it of items){const found=it.code&&list.find(x=>x.code===it.code);if(found){Object.assign(found,{title:it.title,text:it.text,severity:it.severity});if(it.status==='cerrado'&&found.status!=='cerrado'){found.status='cerrado';found.closed=now();}found.updated=now();updated++;}else{list.push({id:newId(),code:it.code,title:it.title,text:it.text,status:it.status||'abierto',severity:it.severity||'medio',created:now(),...(it.status==='cerrado'?{closed:now()}:{})});added++;}}return {added,updated};}
// Entornos 3D de un proyecto: los de p.environments (shipModel ya no es un entorno: la nave es uno más desde #14).
// Visor de un entorno, en orden de transición: viewer como ruta → visor propio del proyecto (tolerado hasta #36);
// constructor y datos → visor genérico /viewer/mount.mjs (con viewer.plugins si los hay); solo GLB → /viewer/glb.mjs.
export function environmentViewer(e){if(typeof e?.viewer==='string'&&e.viewer)return {kind:'legacy',module:e.viewer};if(e?.builder&&e?.data)return {kind:'mount'};if(e?.glb)return {kind:'glb',url:e.glb};return {kind:'none'};}
// Editor de plantas (viewer/planta.html): para entornos con constructor y datos; la planta vive en data → dims.planta.
export const hasPlantaEditor=e=>!!(e?.builder&&e?.data);
export const plantaEditorUrl=(projectId,envId)=>'/viewer/planta.html?project='+encodeURIComponent(projectId)+'&env='+encodeURIComponent(envId);
const VIEWER_KINDS={legacy:'visor',mount:'constructor',glb:'glb',none:'vacío'};
export function environmentList(p){return (p?.environments||[]).map(e=>({id:e.id,name:e.name||e.id,description:e.description||'',image:e.image||'',glb:e.glb||'',viewer:typeof e.viewer==='string'?e.viewer:'',kind:VIEWER_KINDS[environmentViewer(e).kind],action:'env-open:'+e.id}));}
// Entorno con constructor cuyos datos son los de un location.modelSpace (modelSpace.model === environment.data), o null.
export function modelSpaceEnvironment(p,modelSpace){const m=modelSpace?.model;return m?(p?.environments||[]).find(e=>e.builder&&e.data&&e.data===m)||null:null;}
// Vista pedida en la URL: la antigua vista de la nave (?view=ship) lleva a la lista de entornos.
export const routeView=v=>v==='ship'?'environments':v;
// Entorno 3D enlazado a un ambiente (location.environment), o null.
export function locationEnvironment(p,locationId){const l=(p?.locations||[]).find(l=>l.id===locationId);return l?.environment?(p.environments||[]).find(e=>e.id===l.environment)||null:null;}
// Elección de entorno de una secuencia a partir del formulario: lugar, estado por secuencia y giro en grados. Vacío → sin elección.
export function environmentChoice(f){const spot=String(f.envSpot||'').trim(),preset=String(f.envPreset||'').trim(),rotation=Number(f.envRotation)||0;return spot||preset||rotation?{...(spot?{spot}:{}),...(preset?{preset}:{}),...(rotation?{rotation:((rotation%360)+360)%360}:{})}:undefined;}
// Montaje de un lote (vista Montaje y scripts/bloques/montar.mjs).
// Toma que usa el montaje en un bloque: la última aceptada; si no hay, la última generada sin rechazar, pendiente de revisión.
export function chosenAttempt(list,has=()=>true){const ok=a=>a.video&&has(a);const accepted=[...list].reverse().find(a=>a.verdict==='accepted'&&ok(a));if(accepted)return {attempt:accepted,pending:false};const last=[...list].reverse().find(a=>ok(a)&&a.verdict!=='rejected');return last?{attempt:last,pending:true}:{attempt:null,pending:false};}
// Tramo de cada bloque en el vídeo montado: `at`/`length` del cut.json o, en cortes antiguos, la suma de usedRange (o la duración del plan).
export function cutTimeline(cut,plan=[]){let at=0;return (cut?.blocks||[]).map(b=>{const length=b.length??(b.usedRange?.length?b.usedRange.reduce((n,[s,e])=>n+e-s,0):plan.find(x=>x.id===b.block)?.length||0);const start=b.at??at;at=start+length;return {...b,start,end:at};});}
export const blockAt=(timeline,t)=>timeline.find(b=>t>=b.start&&t<b.end)||(t>=(timeline.at(-1)?.end??0)?timeline.at(-1):timeline[0])||null;
// Reglas de REGLAS.md: «### R04 · Nadie mira a cámara».
export function parseRules(md){return [...String(md||'').matchAll(/^###\s+([A-Z]\d+)\s*·\s*(.+)$/gm)].map(m=>({id:m[1],title:m[2].trim()}));}
// Veredicto de un intento (como estado.mjs --verdict). accepted deja de aceptar las demás tomas del bloque; null borra la revisión.
// Un rechazo cita al menos una regla conocida. Rango: tramos [inicio, fin] en segundos del vídeo generado.
export function reviewAttempt(list,{attempt,verdict,rules=[],notes='',range,length,known=[]},now=new Date().toISOString()){
 const out=structuredClone(list),a=out.find(x=>x.n===Number(attempt));if(!a)throw Error(`No existe el intento ${attempt}`);if(!a.video)throw Error(`El intento ${a.n} no tiene vídeo descargado`);
 if(![null,'accepted','rejected'].includes(verdict))throw Error('Veredicto: accepted, rejected o null');rules=rules.map(r=>String(r).trim()).filter(Boolean);
 if(verdict==='rejected'&&!rules.length)throw Error('Un rechazo cita al menos una regla de REGLAS.md');for(const r of rules)if(known.length&&!known.includes(r))throw Error(`Regla desconocida ${r}`);
 const max=a.durationReturned||a.durationRequested||Infinity;
 if(range){if(!Array.isArray(range)||!range.length||range.some(x=>!Array.isArray(x)||x.length!==2||!x.every(Number.isFinite)||x[0]<0||x[1]<=x[0]||x[1]>max+.05))throw Error('Rango no válido: tramos [inicio, fin] dentro del vídeo');}
 if(verdict===null){for(const k of ['verdict','failedRules','notes','reviewedAt','usedRange'])delete a[k];a.verdict=null;return out;}
 if(verdict==='accepted')for(const x of out)if(x!==a&&x.verdict==='accepted'){x.verdict=null;x.replacedBy=a.n;}
 Object.assign(a,{verdict,failedRules:verdict==='rejected'?rules:[],notes,reviewedAt:now});
 if(range)a.usedRange=range.map(([s,e])=>[Math.round(s*100)/100,Math.round(e*100)/100]);else if(verdict==='accepted'&&!a.usedRange)a.usedRange=[[0,Math.min(max,length||max)]];
 return out;}
// Copia con las claves de los objetos ordenadas en todos los niveles; los arrays conservan su orden.
export const sortKeys=v=>Array.isArray(v)?v.map(sortKeys):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sortKeys(v[k])])):v;

// ---- Ensayo 3D: configuración por proyecto en stage.rehearsal ({animations:{library,clips}, exteriors, voicePitch}).
const REHEARSAL_ROLES=['idle','talk','walk'];
const isObj=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
// Idioma del proyecto → base para filtrar voces del navegador y locale del SpeechSynthesisUtterance.
export function speechLocale(language){const l=String(language||'').trim().replace('_','-');if(!l)return {base:'en',locale:'en-US'};const base=l.split('-')[0].toLowerCase();return {base,locale:l.includes('-')?l:({en:'en-US',es:'es-ES'}[base]||base+'-'+base.toUpperCase())};}
// Lo que el ensayo necesita del proyecto para un plano (o para el capítulo, sin plano). Nunca lanza: una configuración mal formada se trata como ausente.
export function rehearsalConfig(project,shot=null){const c=isObj(project?.stage?.rehearsal)?project.stage.rehearsal:{};const lib=c.animations?.library,clips=c.animations?.clips;
 const animations=typeof lib==='string'&&isObj(clips)&&REHEARSAL_ROLES.every(r=>typeof clips[r]==='string')&&(!shot||shot.rehearsal)?{files:Object.fromEntries(REHEARSAL_ROLES.map(r=>[r,lib+'/'+clips[r]+'.fbx']))}:null;
 const key=shot?.rehearsal&&typeof shot.staging?.exterior==='string'?shot.staging.exterior:null;const ext=key&&isObj(c.exteriors)&&Object.hasOwn(c.exteriors,key)&&isObj(c.exteriors[key])&&Array.isArray(c.exteriors[key].parts)?c.exteriors[key]:null;
 return {animations,exterior:ext?{background:ext.background,parts:ext.parts}:null,exteriorKey:ext?key:null,voicePitch:isObj(c.voicePitch)?{...c.voicePitch}:{},speech:speechLocale(project?.language)};}
export function rehearsalStageErrors(cfg){const errors=[];if(cfg===undefined||cfg===null)return errors;if(!isObj(cfg))return ['stage.rehearsal debe ser un objeto'];
 const vec3=v=>Array.isArray(v)&&v.length===3&&v.every(Number.isFinite),color=v=>typeof v==='string'&&/^#[0-9a-f]{6}$/i.test(v);
 if(cfg.animations!==undefined){const a=cfg.animations;if(!isObj(a))errors.push('animations debe ser un objeto');else{if(typeof a.library!=='string'||!a.library)errors.push('animations.library debe ser una ruta');for(const r of REHEARSAL_ROLES)if(typeof a.clips?.[r]!=='string'||!a.clips[r])errors.push(`animations.clips.${r} debe ser un nombre de clip`);}}
 if(cfg.exteriors!==undefined){if(!isObj(cfg.exteriors))errors.push('exteriors debe ser un objeto');else for(const [k,e] of Object.entries(cfg.exteriors)){const at=`exteriors.${k}`;if(!isObj(e)){errors.push(at+' debe ser un objeto');continue;}if(!color(e.background))errors.push(at+'.background debe ser #rrggbb');if(!Array.isArray(e.parts)){errors.push(at+'.parts debe ser una lista');continue;}
  e.parts.forEach((p,i)=>{const w=`${at}.parts[${i}]`;if(!isObj(p))return errors.push(w+' debe ser un objeto');if(!['box','cylinder','sphere'].includes(p.shape))errors.push(w+'.shape debe ser box, cylinder o sphere');if(!color(p.color))errors.push(w+'.color debe ser #rrggbb');if(!vec3(p.position))errors.push(w+'.position debe tener 3 números');for(const f of ['rotation','drift','spin'])if(p[f]!==undefined&&!vec3(p[f]))errors.push(`${w}.${f} debe tener 3 números`);
   if(p.shape==='box'&&!vec3(p.size))errors.push(w+'.size debe tener 3 números');if((p.shape==='cylinder'||p.shape==='sphere')&&!(Number.isFinite(p.radius)&&p.radius>0))errors.push(w+'.radius debe ser mayor que 0');if(p.shape==='cylinder'&&!(Number.isFinite(p.height)&&p.height>0))errors.push(w+'.height debe ser mayor que 0');});}}
 if(cfg.voicePitch!==undefined){if(!isObj(cfg.voicePitch))errors.push('voicePitch debe ser un objeto');else for(const [k,v] of Object.entries(cfg.voicePitch))if(!(Number.isFinite(v)&&v>=0&&v<=2))errors.push(`voicePitch.${k} debe ser un número entre 0 y 2`);}
 return errors;}
// Posición y giro de una pieza de exterior tras `elapsed` segundos de secuencia: position + drift·t; rotation + spin·t solo si gira.
export function exteriorPartAt(part,elapsed){return {position:part.position.map((v,i)=>v+(part.drift?.[i]??0)*elapsed),rotation:part.spin?part.spin.map((v,i)=>(part.rotation?.[i]??0)+v*elapsed):null};}
// Instantánea de un lote o trabajo anterior a stage: se completa con la configuración del proyecto vivo.
export function stageFallback(snapshot,live){return snapshot?.stage?snapshot:{...snapshot,stage:live?.stage};}

// ── Dirección por lote (assets/<lote>/direccion.json, modo fotograma) y estados de personaje del registro ──
// Nombre en mayúsculas del personaje: prefijo «NOMBRE:» de su descriptor (base antes que variante); si no, shortName.
const characterAsset=(registry,id)=>{const assets=Object.entries(registry?.assets||{});return assets.find(([,a])=>a.kind==='character'&&a.character===id&&!a.variant)||assets.find(([,a])=>a.kind==='character'&&a.character===id)||null;};
export function characterName(registry,project,id){return /^([A-Z][A-Z' -]+):/.exec(characterAsset(registry,id)?.[1]?.descriptor||'')?.[1]||shortName(project,id);}
const DIR_TEXT=['camera','action','acting','local','people'];
// Rellena los huecos del esqueleto de framePrompt con la entrada del bloque. [[LOCAL]] = frase de reparto + local + locks aplicables.
export function applyDireccion(prompt,d,{names=[],locks=[],image=null}={}){const warnings=[];let p=prompt;const who=d.people||names.join(', ');
 if(d.people)p=p.replace(/Exactly \d+ (people|person) in the scene[^.]*\./,()=>`People in the scene: ${d.people}.`);
 const L=(locks||[]).map(l=>typeof l==='string'?{text:l}:l).filter(l=>l.when!=='cast'||names.length).map(l=>l.text);
 const local=[who?`The people in the scene are only ${who}; nobody else enters the frame.`:'',d.local,...L].filter(Boolean).join(' ');
 for(const [k,h,v] of [['camera','[[CAMERA]]',d.camera],['action','[[ACTION]]',d.action],['local','[[LOCAL]]',local]]){if(!v)continue;if(p.includes(h))p=p.replace(h,()=>v);else if(d[k])warnings.push(`direccion.${k} no se aplica: el esqueleto ya trae ${k.toUpperCase()}`);}
 if(d.acting){const re=/^CHARACTER ACTING: [\s\S]*?(?=^PHYSICS: )/m;if(re.test(p))p=p.replace(re,()=>`CHARACTER ACTING: ${d.acting}\n`);else warnings.push('direccion.acting no se aplica: falta CHARACTER ACTING antes de PHYSICS');}
 if(d.fin&&!image)warnings.push('direccion.fin sin fotograma: no hay endImage');
 const emo=forbiddenEmotionWords((d.acting||'')+' '+(d.local||''));if(emo.length)warnings.push(`Palabras de emoción en la dirección: ${emo.join(', ')} (skill interpretacion)`);
 return {prompt:p,refsPatch:d.fin?{endImage:image}:{},warnings};}
export function direccionErrors(d){if(!isObj(d))return ['debe ser un objeto'];const errors=[];
 if(d.blocks===undefined&&Object.keys(d).some(k=>/^b\d+$/.test(k)))return ['formato antiguo: mueve los bloques a "blocks" y las coletillas a "locks"'];
 if(d.blocks!==undefined&&!isObj(d.blocks))errors.push('blocks debe ser un objeto {bNN: {...}}');
 for(const [id,b] of Object.entries(isObj(d.blocks)?d.blocks:{})){if(!isObj(b)){errors.push(`blocks.${id} debe ser un objeto`);continue;}for(const k of DIR_TEXT)if(b[k]!==undefined&&typeof b[k]!=='string')errors.push(`blocks.${id}.${k} debe ser texto`);if(b.fin!==undefined&&typeof b.fin!=='boolean')errors.push(`blocks.${id}.fin debe ser true o false`);}
 if(d.locks!==undefined){if(!Array.isArray(d.locks))errors.push('locks debe ser una lista');else d.locks.forEach((l,i)=>{if(typeof l==='string')return;if(!isObj(l)||typeof l.text!=='string'||(l.when!==undefined&&!['cast','always'].includes(l.when)))errors.push(`locks[${i}] debe ser texto o {text, when: "cast"|"always"}`);});}
 return errors;}
// Entrada de un bloque; lee también el formato antiguo (bNN en la raíz) para la vista Montaje.
export function direccionBlock(d,blockId){return d?.blocks?.[blockId]??(d?.blocks?null:d?.[blockId])??null;}
// Dónde escribe prompt.mjs: con direccion.json, un bloque sin entrada y con prompt.txt no se toca salvo que se nombre.
export function promptTargets({exists,force,hasDireccion,directed,named}){if(hasDireccion&&!directed&&exists&&!named)return {skip:true,promptFile:null,writeRefs:false};return {skip:false,promptFile:exists&&!force?'prompt.generated.txt':'prompt.txt',writeRefs:true};}
// refs.json nuevo: con dirección manda fin; sin dirección se conserva el endImage anterior. endImage siempre al final.
export function mergeRefs(fresh,old,{directed=false,patch={}}={}){const {endImage:_,...out}=fresh||{};const end=directed?patch.endImage:old?.endImage;return end?{...out,endImage:end}:out;}
export function parseCastRef(ref){const s=String(ref||''),i=s.indexOf('@');return i<0?{id:s,state:null}:{id:s.slice(0,i),state:s.slice(i+1)};}
// Estados en el asset del personaje: "states": {"a-pie": {"drop": [", on horseback"], "note": "on foot, …"}}. Sin herencia.
function applyState(descriptor,st){let d=descriptor;const missing=[];for(const x of st.drop||[]){if(d.includes(x))d=d.replace(x,'');else missing.push(x);}if(st.note)d=d.replace(/\.\s*$/,'')+'; '+st.note;return {descriptor:d,missing};}
export function resolveDescriptor(registry,ref){const {id,state}=parseCastRef(ref);const e=characterAsset(registry,id);const out={id,state,tag:e?.[0]||null,name:characterName(registry,null,id),descriptor:e?.[1]?.descriptor||'',errors:[]};
 if(!e){out.errors.push(`Sin entrada de registro para ${id}`);return out;}if(!state)return out;
 const st=e[1].states?.[state];if(!isObj(st)){out.errors.push(`${e[0]}: estado desconocido «${state}»${Object.keys(e[1].states||{}).length?` (hay ${Object.keys(e[1].states).join(', ')})`:''}`);return out;}
 const r=applyState(out.descriptor,st);for(const x of r.missing)out.errors.push(`${e[0]}@${state}: no se encuentra «${x}» en el descriptor`);out.descriptor=r.descriptor;return out;}
export function stateErrors(tag,asset){const errors=[];if(asset?.states===undefined)return errors;if(!isObj(asset.states))return [`${tag}: states debe ser un objeto`];
 for(const [s,st] of Object.entries(asset.states)){if(!isObj(st)){errors.push(`${tag}@${s}: debe ser un objeto {drop, note}`);continue;}if(st.drop!==undefined&&(!Array.isArray(st.drop)||st.drop.some(x=>typeof x!=='string'||!x)))errors.push(`${tag}@${s}: drop debe ser una lista de textos`);if(st.note!==undefined&&typeof st.note!=='string')errors.push(`${tag}@${s}: note debe ser texto`);if(!st.drop?.length&&!st.note)errors.push(`${tag}@${s}: sin drop ni note`);
  if(Array.isArray(st.drop))for(const x of applyState(asset.descriptor||'',{drop:st.drop.filter(x=>typeof x==='string'&&x)}).missing)errors.push(`${tag}@${s}: no se encuentra «${x}» en el descriptor`);}
 return errors;}
